### ISSUE TITLE
Use of find_library

### ISSUE THREAD

**Issue by msieben** [Metrological/WebKitForWayland#1]
In certain files at https://github.com/Metrological/WebKitForWayland/tree/master/Source/cmake the find_library function is used with hardcoded names. Although the names might be commonly accepted,  wouldn't it be better to extract the name from the .pc, i.e. the name given by -l? This allows for less conventional names.

Example: https://github.com/Metrological/WebKitForWayland/blob/master/Source/cmake/FindOpenGLES2.cmake#L18-20

**Comment by zdobersek** [comment]
What are the contents of the .pc file? What's the actual name of the library?

Don't know off the top of my head whether something like this is extractable from the .pc file via CMake.

**Comment by msieben** [comment]
The actual contents depends on what is put in the file.  The cmake documentation [1] mentions support for extracting flags and names. For example:

	<XPREFIX>_FOUND          ... set to 1 if module(s) exist
	<XPREFIX>_LIBRARIES      ... only the libraries (w/o the '-l')
	<XPREFIX>_LIBRARY_DIRS   ... the paths of the libraries (w/o the '-L')
	<XPREFIX>_LDFLAGS        ... all required linker flags
	<XPREFIX>_LDFLAGS_OTHER  ... all other linker flags
	<XPREFIX>_INCLUDE_DIRS   ... the '-I' preprocessor flags (w/o the '-I')
	<XPREFIX>_CFLAGS         ... all required cflags

[1] http://www.cmake.org/cmake/help/v3.0/module/FindPkgConfig.html gives

**Comment by msieben** [comment]
An example

	prefix=/usr
	exec_prefix=${prefix}
	libdir=${exec_prefix}/lib
	includedir=${prefix}/include

	Name: glesv2
	Description: NAME implementation of OpenGL ESv2
	Version: 1.0
	Libs: -L${libdir} -lLIBNAME
	Cflags: -I${includedir} -I${includedir}/LIBPATH

If LIBNAME would be extracted and used,  it would be more flexible.

**Comment by zdobersek** [comment]
Would it be possible to create a libGLESv2.so symlink, that points to whatever library should be used?

**Comment by msieben** [comment]
That's currently being done.

**Comment by zdobersek** [comment]
I think that's sufficient, and perhaps even common, but I'm not against searching for the specific library names.

In the find_library() call in FindOpenGLES2.cmake that you linked before, change 'GLESv2' to '${PC_OPENGLES2_LIBRARIES}' and test it out. It might work, not sure (and can't test it myself). If it does, we can easily commit the change.

**Comment by msieben** [comment]
${PC_OPENGLES2_LIBRARIES} is more in agreement with the, already implemented, use of pkg-config. If it works, we should indeed adopt it (imho). I will keep you updated.
