### ISSUE TITLE
[JSC] Webprocess crash with BinarySwitch signature de to SIGSEGV

### ISSUE THREAD

**Issue by Shiva367** [Metrological/WebKitForWayland#1002]
This issue happens in both MIPS and ARM devices (Arris XG1v4, Arris Xi6, Xione-US[Realtek], Xione-US[BCOM], Tech Xi6]). 
**Apps:** Amazon prime(more frequency), appleTV, Disney+.

Field frequency: 0.07%

**Scenario:**
1. Play any asset in Amazon 
2. Do trick play and check for crash(also try different assets also)

wpe-commit:
55b51e9b8c7a2cc7030e6f984fa317f3bf1bdc41

full StackTrace:
[StackTrace.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10368432/StackTrace.txt)

**Comment by guijemont** [comment]
It looks like one of the vectors maintained by the `BinarySwitch` is triggering an overflow crash. Most likely it is inside `BinarySwitch::caseIndex()`, which means that the instance is not in a consistent state.
I can't really deduce the reason for that with only this stack trace. To go further, I would need one of the following (ordered most preferred first):
 - a reduced test case that I can run on e.g. a raspberry pi 3
 - a way to run on one of the devices I have the reproduction scenario, with the ability to recompile WebKit with different options (especially with debug symbols) and attach a debugger
 - a core file, as well as the sources and build files of WebKit that were used to generate the binary from which the core file comes, so that I can investigate the state of memory at the time of the crash. This is useful only if debugging symbols are provided in the build.
 - the output of the gdb command `bt thread apply all` ran at the time of the crash, with the gdb having access to debugging symbols

**Comment by Shiva367** [comment]
Reproduction scenario:
Launch Amazon App -> Play any assets -> Do some trick play

Issue reproduction: This issue was not able to reproduce from our side, the exact scenario was observed from the logs.

**symbol_debug or Minidump:** 
[minidump.zip](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10401896/minidump.zip)
**Threads_state:**
[Thread_states.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10401903/Thread_states.txt)

**Comment by guijemont** [comment]
Could you provide symbols that match the minidump? (e.g. using dump_syms from breakpad)

**Comment by Shiva367** [comment]
I have resolved the debug symbols with the crashed minidump using breakpad,

The exact crashed symbols,
**Thread 0 (crashed)
 0  libWPEWebKit-0.1.so.2.2.6!WTFCrash [Assertions.cpp : 255 + 0xc]
 1  libWPEWebKit-0.1.so.2.2.6!JSC::BinarySwitch::BinarySwitch(JSC::ARMRegisters::RegisterID, WTF::Vector<long long, 0u, WTF::CrashOnOverflow, 16u> const&, JSC::BinarySwitch::Type) [CheckedArithmetic.h : 85 + 0x3]
 2  libWPEWebKit-0.1.so.2.2.6!JSC::linkPolymorphicCall(JSC::ExecState*, JSC::CallLinkInfo&, JSC::CallVariant) [Repatch.cpp : 1139 + 0xb]
 3  libWPEWebKit-0.1.so.2.2.6!operationLinkPolymorphicCall [JITOperations.cpp : 1209 + 0x7]
 4  0xb27febd1**

**CallStack:**
**WTFCrash
/usr/src/debug/wpe-webkit/2.22.6+gitAUTOINC+55b51e9b8c-r0/git/Source/WTF/wtf/Assertions.cpp:255

BinarySwitch
/usr/src/debug/wpe-webkit/2.22.6+gitAUTOINC+55b51e9b8c-r0/build/DerivedSources/ForwardingHeaders/wtf/CheckedArithmetic.h:85

linkPolymorphicCall
/usr/src/debug/wpe-webkit/2.22.6+gitAUTOINC+55b51e9b8c-r0/git/Source/JavaScriptCore/jit/Repatch.cpp:1139

operationLinkPolymorphicCall
/usr/src/debug/wpe-webkit/2.22.6+gitAUTOINC+55b51e9b8c-r0/git/Source/JavaScriptCore/jit/JITOperations.cpp:1209

:
**

**Both crashed and other threads stack:** 
[Stackwalk_Result.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10445255/Stackwalk_Result.txt)

the crash symbols are resolved, please let me know if you need any help.

**Comment by Shiva367** [comment]
@guijemont 

Do you have any updates on this issue?

**Comment by guijemont** [comment]
> @guijemont
> 
> Do you have any updates on this issue?

My apologies, I missed your previous comment as it came right as I was starting my vacations.

What I need is more than a stack trace with symbols resolved: I need to be able to explore the state of the memory (at the very least: the value of function arguments and of local variables). The above Stackwalk_Result.txt does not seem to provide more information than the previously provided Thread_states.txt, it's just formatted differently, thus I don't have anything more to analyse than previously and I'm unable to do anything more at this time.

I should be able to do further analysis with one of the  4 solutions proposed in [this comment](https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1002#issuecomment-1377770439). I *think* that providing me with what `dump_syms` generates in an environment that has the debug symbols matching the generation of the provided minidump file should give me what I need.

**Comment by guijemont** [comment]
@Shiva367 Is the issue still happening?
If yes, could you provide a core file and symbols files with debug info, or a minidump and matching symbol files with debug info?

> I _think_ that providing me with what `dump_syms` generates in an environment that has the debug symbols matching the generation of the provided minidump file should give me what I need.

I think I was wrong here. What I need is the symbol files generated while building.

**Comment by GlebNovodranPE** [comment]
The issue is not observed with 2.28. I think it can be closed.
