### ISSUE TITLE
Crash in pixman/cairo - subsurface bigger than surface

### ISSUE THREAD

**Issue by jaroslaw-bojko-red** [Metrological/WebKitForWayland#1044]
Hi!
Lately in our browser (wpe-webkit_2.22.1), we have encountered a crash in pixman during VTM go app, the main menu exploring (switching tv shows tiles for from 30 min to 6 h)

The crash happens in the pixman convert_a8r8g8b8 method. In pixman we create a custom iterator that goes through all pixels from cairo_image_it. The crash happens when we try to read outside allocated memory for cairo_surface_t.

For example: 
In the wpeWebkit browser, we created a cairo_surface_t by method cairo_image_surface_create_for_data with a data pointer data=0x5ec6a000, image_size: 320x480, total buffer size: 0x96000.
convert_a8r8g8b8 tries to read from an address: 0x5ED00000 (a first address outside the buffer).

I spotted pixman state bits_width: 320, bits_height: 481 (note a bigger height by 1) where we created a buffer 320x480), the row pointer is exactly the same that we created for 320x480 - 0x5ec6a000.

I checked that the size is changed in Cairo, method: 
`static pixman_image_t *
_pixman_image_for_surface (cairo_image_surface_t *dst,
			   const cairo_surface_pattern_t *pattern,
			   cairo_bool_t is_mask,
			   const cairo_rectangle_int_t *extents,
			   const cairo_rectangle_int_t *sample,
			   int *ix, int *iy)
{`
exac in this method:
`		    pixman_image = pixman_image_create_bits (source->pixman_format,
							     sub->extents.width,
							     sub->extents.height,
							     data,
							     source->stride);`

Cairo states that the surface has a subsurface with a size bigger by one row ( sub->extents.height: 481 vs height 480) and passes a pointer to the original buffer 0x5ec6a000 (which was allocated for 480) which I think causes the problem.

Does anyone with cairo experience know the concept of subsurface, and why cairo could state that it is bigger than the surface? Did we encounter similar problems with cairo?

**Comment by magomez** [comment]
Hi @jaroslaw-bojko-red 

Thanks for the report and the investigation. I don't have a clear idea about what could be happening here, other than cairo deciding that it needs a surface bigger than the size passed in order to store the image. I'll have to investigate it to find out what's happening exactly. Would it be possible to get a complete backtrace of the crash (a testcase to reproduce the crash would be awesome)? Or at least so you know where in the webkit code that cairo_surface_t is created and where the crash happens trying to read it? Also, which version of cairo are you using?

**Comment by jaroslaw-bojko-red** [comment]
Backtrace: [backtrace.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10851077/backtrace.txt)
Cairo version: 1.16

**Crash reproduction:**
1. Launch VTM go app: url: https://stv.vtmgo.be/vtmgo/release/eos/index.html?appTileLocation=[object%20Object]]
2.  Enter a tv show tail from main menu
3. Click back on tv remote
4. Click right on tv remote
5.  Enter another tv show tail from main menu
6. Click back
7. Click left

Do the above steps from 30 min to 6 hours. 

I tried to create a simplified TC with a HTML that shows image: https://images0.persgroep.net/rcs/3xuiZ8IAJrY477AFWvSHN_N1iLc/diocontent/227502709/_fitwidth/320?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8 but the problem with height: sub->extents.height: 481 does not occure (in simple TC pixman receives proper value 480. I don't know what VTM go do with an image that the issue reproduces)

**Important logs:**
Feb 24 01:35:00 3C36E4-EOSSTB-003356429500 wpe.sh[8609]: JJ: ImageBackingStore::image, this: 0x7b699370, surface_data: 0x5ec6a000, bufferSize: 614400
Feb 24 01:35:00 3C36E4-EOSSTB-003356429500 wpe.sh[8609]: JJ: BitmapImage::draw before drawNativeImage: 0x5ec6a000, threadID: 1146441575
Feb 24 01:35:00 3C36E4-EOSSTB-003356429500 wpe.sh[8609]: JJ: BitmapImage::draw after drawNativeImage: 0x5ec6a000, threadID: 1146441575
Feb 24 01:35:00 3C36E4-EOSSTB-003356429500 wpe.sh[8609]: JJ: cairoOperations::drawNativeImage before draw, surface_data: 0x5ec6a000, buffersize: 614400, threadID: 612606417

Logs are from the same reproduction as a stack trace.

**Crash case:**
1. We enter the main menu
5. App decides to render https://images0.persgroep.net/rcs/3xuiZ8IAJrY477AFWvSHN_N1iLc/diocontent/227502709/_fitwidth/320?appId=038a353bad43ac27fd436dc5419c256b&quality=0.8
9. After downloading image we decode it via libJPEGTurbo and save the output fo m_pixelsPtr from git/Source/WebCore/platform/graphics/ImageBackingStore.h (in ImageBackingStore::clear we create a buffer for 320 *480 *sizeof(RGBA32) (4)
10. We create a cairo surface for these pixels in: git/Source/WebCore/platform/image-decoders/cairo/ImageBackingStoreCairo.cpp
11. In git/Source/WebCore/platform/graphics/BitmapImage.cpp we order to render this surface via:     drawNativeImage(image, context, destRect, srcRect, IntSize(size()), op, mode, orientation);
12. Rendering is scheduled to NicosiaPainingThread: surface_data: 0x5ec6a000, buffersize: 614400, (buffer size still for 320x480 pixels)
13. Rest is in the backTrace

**Comment by magomez** [comment]
> Backtrace: [backtrace.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10851077/backtrace.txt) 

Do you have the webkit bracktrace as well? I'm interested in the exact operation that webkit is doing that's causing cairo to behave that way.

**Comment by jaroslaw-bojko-red** [comment]
The crash always happens  with the same stack in NicosiaThread while wpewebkit stack is often different:
I paste 4 stacks from different reproductions into [backtrace_wpewebkit.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10851381/backtrace_wpewebkit.txt)

Additional note:
I added link to vtm go app: [https://stv.vtmgo.be/vtmgo/release/eos/index.html?appTileLocation=[object%20Object]]](https://stv.vtmgo.be/vtmgo/release/eos/index.html?appTileLocation=%5Bobject%20Object%5D%5D) (registration is free)
I checked that cairo_surface_t destructor is not called before crash (checked by adding a log into functor that is called beofre surface destruction: 
`cairo_surface_set_user_data(surface.get(), &s_surfaceDataKey, m_pixels.get(), [](void* data) { static_cast<SharedBuffer*>(data)->deref(); });`

**Comment by magomez** [comment]
> The crash always happens with the same stack in NicosiaThread while wpewebkit stack is often different: I paste 4 stacks from different reproductions into [backtrace_wpewebkit.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10851381/backtrace_wpewebkit.txt)
> 

Sorry, I guess I didn't explain myself properly. What I'm interested in is exactly the backtrace of the crashing nicosia thread. The traces from the other threads are not interesting (as you say, they will be doing different things in different executions).

**Comment by jaroslaw-bojko-red** [comment]
This backtrace: [backtrace.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10851077/backtrace.txt) (from previous comment https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1044#issuecomment-1448241540) Does not come from NicosiaThread? I did not checked the thread id, I suspected that the cairo/pixman executes in NicosiaThread.

This backtrace: [backtrace.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10851077/backtrace.txt) - this backtrace is the same in all crash reproductions

The other threads than [backtrace.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10851077/backtrace.txt) and [backtrace_wpewebkit.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10851381/backtrace_wpewebkit.txt) are in the __libc_do_syscall:

(gdb) info threads
  Id   Target Id         Frame 
 11683 LWP 53            0xb335d724 in convert_a8r8g8b8 (x=<optimized out>, row=<error reading variable: Cannot access memory at address 0x81>) at ../pixman-0.38.4/pixman/pixman-fast-path.c:3077
  11684 LWP 16            0xb5e69160 in WTF::StringImpl::deref () at DerivedSources/ForwardingHeaders/wtf/text/StringImpl.h:1050
  11685 LWP 19            __libc_do_syscall () at libc-do-syscall.S:48
  11686 LWP 21            __libc_do_syscall () at libc-do-syscall.S:48
  11687 LWP 23            __libc_do_syscall () at libc-do-syscall.S:48
  11688 LWP 26            syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37
  11689 LWP 27            __libc_do_syscall () at libc-do-syscall.S:48
  11690 LWP 29            __libc_do_syscall () at libc-do-syscall.S:48
  11691 LWP 30            __libc_do_syscall () at libc-do-syscall.S:48
  11692 LWP 31            __libc_do_syscall () at libc-do-syscall.S:48
  11693 LWP 35            0xb447f1d8 in ioctl () at ../sysdeps/unix/syscall-template.S:120
  11694 LWP 36            __libc_do_syscall () at libc-do-syscall.S:48
  11695 LWP 37            __libc_do_syscall () at libc-do-syscall.S:48
  11696 LWP 38            __libc_do_syscall () at libc-do-syscall.S:48
  11697 LWP 39            __libc_do_syscall () at libc-do-syscall.S:48
  11698 LWP 40            __libc_do_syscall () at libc-do-syscall.S:48
  11699 LWP 41            __libc_do_syscall () at libc-do-syscall.S:48
  11700 LWP 42            __libc_do_syscall () at libc-do-syscall.S:48
  11701 LWP 43            __libc_do_syscall () at libc-do-syscall.S:48
  11702 LWP 44            __libc_do_syscall () at libc-do-syscall.S:48
  11703 LWP 46            __libc_do_syscall () at libc-do-syscall.S:48
  11704 LWP 47            __libc_do_syscall () at libc-do-syscall.S:48
  11705 LWP 48            __libc_do_syscall () at libc-do-syscall.S:48
  11706 LWP 50            __libc_do_syscall () at libc-do-syscall.S:48
  11707 LWP 51            __libc_do_syscall () at libc-do-syscall.S:48
  11708 LWP 52            __libc_do_syscall () at libc-do-syscall.S:48
  11709 LWP 54            __libc_do_syscall () at libc-do-syscall.S:48
  11710 LWP 328           __libc_do_syscall () at libc-do-syscall.S:48
  11711 LWP 2148          __libc_do_syscall () at libc-do-syscall.S:48
  11712 LWP 5379          __libc_do_syscall () at libc-do-syscall.S:48
  11713 LWP 5381          __libc_do_syscall () at libc-do-syscall.S:48
  11714 LWP 5385          __libc_do_syscall () at libc-do-syscall.S:48
  11715 LWP 5386          syscall () at ../sysdeps/unix/sysv/linux/arm/syscall.S:37

**Comment by jaroslaw-bojko-red** [comment]
Backtrace dump from all threads: [output.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10851743/output.txt)

**Comment by magomez** [comment]
> This backtrace: [backtrace.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10851077/backtrace.txt) (from previous comment [#1044 (comment)](https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1044#issuecomment-1448241540)) Does not come from NicosiaThread? I did not checked the thread id, I suspected that the cairo/pixman executes in NicosiaThread.
> 

Yes, that's probably coming from the nicosia thread, but it doesn't include the calls from wpe, just the ones from cairo, that's why I was asking for the wpe part. I thought maybe you were missing the wpe symbols and were only using the cairo ones, but if the other threads belong to the same crash and they have the wpe symbols then there's probably some error when trying to create the complete backtrace for this thread. Let's see if I'm able to reproduce the issue then.

**Comment by jaroslaw-bojko-red** [comment]
Ok, understand now. Yes this backtrace show only calls from cairo/pixman, not the wpe. I don't know why there is no calls from wpe, but in all reproduction stack lacks of wpe calls

**To reproduce the problem with different heights**
There is no need to reproduce the crash (30 min to 6 hours of tile switch) - the problem is visible in first main menu load.

**To reproduce the crash:**
Steps reproduction in the video:
https://user-images.githubusercontent.com/108721265/221897892-716a164a-16da-42f6-a25c-fd592c7b27c8.mp4
Unfortunately there is another problem with vtm go app. The site has the memory leaks in JS and in our device after one hour of tile switch, the kernel kills whole wpe container because it allocates too much memory. I created an separate issue for this for app creators and we waiting for the reponse.
To bypass this problem after some time I load about:blank to clear the memory and then again go to https://stv.vtmgo.be/vtmgo/release/eos/index.html?appTileLocation=%5Bobject%20Object%5D%5D to reproduce steps.

I suspect that the crash is caused by reading not allocated memory (because cairo states a bigger height).

**Comment by jaroslaw-bojko-red** [comment]
In the cairo code i changed (_pixman_image_for_surface method 1.16.0-r0/cairo-1.16.0/src/cairo-image-source.c file, line 1375 in my code)
pixman_image = pixman_image_create_bits (source->pixman_format, sub->extents.width, sub->extents.height, data, source->stride);
to:
pixman_image = pixman_image_create_bits (source->pixman_format, source->width, source->height, data, source->stride);

as source->height state proper height (480). 

And after 9 hours there was no crash, everything looks ok.

Note: It was only a test, I know that I cannot commit this without understanding the context, but I wanted to get additional confirmation that the improper height is connected to a crash.

**Comment by jaroslaw-bojko-red** [comment]
I tracked down the problematic code:
The height differences started in wpe-webkit not cairo.

We pass srcRect into a drawSurface method from Source/WebCore/platform/graphics/cairo/CairoOperations.cpp

In this method:
srcRect.size().height() returns : 480.000031 not 480

Because of this difference, we enter the if:
if (srcRect.x() || srcRect.y() || srcRect.size() != cairoSurfaceSize(surface)) {
which creates IntRect expandedSrcRect(enclosingIntRect(srcRect));

This expandedSrcRect returns a rect with width 481 which later in pixman causes a problem. We should not enter this if as this creates an invalid pattern from which later cairo creates a subsurface bigger than the surface.
(On the other side even after entering this if we should not create a pattern bigger than surface)

@magomez If you find the time please check my findings if they look solid to you. I think that the problem is because we do an implicit conversion from IntSize (from cairoSurfaceSize) to FloatRect and then we compare two floats. Comparing floats are fishy so we state that they are not equal. 

Tomorrow I will think about how exactly fix this.

**Comment by jaroslaw-bojko-red** [comment]
I created a pull request to lgi-master with a fix: https://github.com/LibertyGlobal/WPEWebKit/pull/242
With this commit, I successfully switched the main menu tiles for 14 hours without the crash.

**Comment by jaroslaw-bojko-red** [comment]
I found a similar solution in wpe-webkit 2.28: https://bugs.webkit.org/show_bug.cgi?id=201755 
The difference is that in the solution from 2.28  subsurface is still created but later also browser executes:
expandedSrcRect.intersect({ { }, cairoSurfaceSize(surface) });
Which takes only common parts from two surfaces. I think that creating a subsurface is an unnecessary overhead (as it has the same size as the surface), but it should not slow down the web browser in a noticeable way as the surface is the only x,y, width, and height with the same pointer to data.
I will use a solution from wpe2.28 as we would not need to maintain a separate solution.
