### ISSUE TITLE
WebKitURISchemeRequest API does not set the HTTP status code upon error

### ISSUE THREAD

**Issue by mikepantazoglou** [Metrological/WebKitForWayland#1050]
When calling the void webkit_uri_scheme_request_finish_error API method of WebKitURISchemeRequest the HTTP status code is not set in the corresponding response. It would be expected that the formulated ResourceError is somehow used to properly set the response, e.g. in case of an HTTP 404 Not Found error.

**Comment by magomez** [comment]
Which wpe version are you trying? Is it 2.38?

**Comment by modeveci** [comment]
@magomez I think it is wpe-2.28, wpe-2.38 is not available for RDK images. @mikepantazoglou can you confirm?

**Comment by mikepantazoglou** [comment]
@magomez We're using wpe-2.28.

**Comment by mikepantazoglou** [comment]
Some further background info on the use case, which might be helpful:

We have implemented custom URI scheme request handling for dvb:// URLs, as part of our HbbTV solution. One of the formal HbbTV tests asserts the following:

The status property will return value 404 when trying to
access non-existing DSM-CC objects in a mounted
carousel with XMLHttpRequest.

So in our case, the status property of the XHR is always set to 0, regardless of the GError parameter we pass on to the `webkit_uri_scheme_request_finish_error` API.

**Comment by magomez** [comment]
I've just pushed 9d72c0b33bfc9bd564ab8ae6bcce0fa8a53ffe20 to the wpe-2.28 branch with the fix that was added upstream for this. This change introduces a new class WebKitURISchemeResponse that needs to be used by the app to provide the appropriate status code.

How to use this? First, keep using webkit_uri_scheme_request_finish_error to report system errors like network not available and such.

When it comes to reporting http errors, you should use this new WebKitURISchemeResponse class. Once the handler has the http response, you should do something like this:

```
        auto response = adoptGRef(webkit_uri_scheme_response_new(inputStream, lenght));
        webkit_uri_scheme_response_set_status(response.get(), statusCode, statusString);
        webkit_uri_scheme_response_set_content_type(response.get(), contentType);
        webkit_uri_scheme_request_finish_with_response(request, response.get());
```

That way the http status will be stored in the ResourceResponse.

Please, give it a test and tell me if it works fine for you (and close this issue) or whether there's any problem.

**Comment by mikepantazoglou** [comment]
@magomez Thanks for the fix. We confirm it works as expected. This issue may now be closed.
