### ISSUE TITLE
wpe-2.38: texImage2D() doesn't work with accelerated canvas

### ISSUE THREAD

**Issue by asurdej-comcast** [Metrological/WebKitForWayland#1069]
Withe the latest wpe-2.38 branch accelerated canvas was included by 8c56a4ebcaff57cec77de3145e59c02f5d9f4deb

There is an issue with copying accelerated canvas data into webgl texture with texImage2D as it breaks with

Source/WebCore/html/canvas/WebGLRenderingContextBase.h:validateTexImageSubRectangle

        if (!subRect.isValid() || subRect.x() < 0 || subRect.y() < 0
            || subRect.maxX() > imageWidth || subRect.maxY() > imageHeight
            || subRect.width() < 0 || subRect.height() < 0) {
            synthesizeGLError(GraphicsContextGL::INVALID_OPERATION, functionName,
                "source sub-rectangle specified via pixel unpack parameters is invalid");
            return false;
        }

ImageWidht and imageHeight are zeros.

As a result we have a black box instead of source canvas content.
Some dev test case: https://asurdej-comcast.github.io/tests/canvas_text.html
Scenario:
1) Create canvas 2d context with some content/text
2) Create another canvas with webgl context
3) Use 1) as a source for a gl texture and paint that texture

This can be partially solved by bringing ImageBufferCairo:
bool ImageBuffer::copyToPlatformTexture(GraphicsContextGLOpenGL&, GCGLenum target, PlatformGLObject destinationTexture, GCGLenum internalformat, bool premultiplyAlpha, bool flipY)

into ImageBufferGLSurfaceBacknd but alpha doesn't seem to work well (and alpha is used to render text)...

**Comment by asurdej-comcast** [comment]
@magomez can you please take a look. Unfortunately this is heavily used by some of our devices and breaks UI completely.

**Comment by magomez** [comment]
@asurdej-comcast, I've pushed some commits related to the canvas to the 2.38 branch. Could you pull and check whether they fix the problem for you? Thanks!

**Comment by asurdej-comcast** [comment]
@magomez It works fine with the latest wpe-2.38 branch. Closing this ticket, thank you
