### ISSUE TITLE
Overlapping audio segments after quality change in Pluto

### ISSUE THREAD

**Issue by jaroslaw-bojko-red** [Metrological/WebKitForWayland#1081]
In Liberty in WPeWebkit 2.22 we encounter a problem with the Pluto TV app.

For the user, the issue is visible as regular hiccupps/blips in playback of the Live channels.

After analysis, we track down the issue to below sequence:
1. During playback there is a video quality switch. 
2. We change the video quality to lower or higher quality. 
3. After changing the video quality we fetch new audio data via MSE path.
4. New audio segment overlaps with the audio segment that we previously get from the JS app.
5. We have to restart the decoder as it already decoded the previous segment and decoded data overlaps with the new segment.

For example, before the quality change, we received an audio buffer till 0:40.0 and after the quality change, we receive again the time 0:35:0 to 0.40.0. Decoder needs DTS to be continuous so with an overlapping segment we perform a decoder restart which causes short freezes.

**Question:**
I received the information that you already delivered Pluto App. Did you encounter a similar problem with overlapping audio segments? If yes how you handled this case?

Logs from the device:
[logs_final.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/11342460/logs_final.txt)

Overlapping segments:
`Apr 26 15:58:04 3C36E4-EOSSTB-003356429500 WPEWebProcess[3353]: 230426-13:58:04.917359 [mod=MediaSourceSamples, lvl=INFO] [tid=16] SourceBuffer::sourceBufferPrivateDidReceiveSample(0x7c51fc00) - sample({PTS({40000000/1000000 = 40.000000}), DTS({40000000/1000000 = 40.000000}), duration({21333/1000000 = 0.021333}), flags(sync), trackId(A1), presentationSize(0.000000x0.000000)})`

`Apr 26 15:58:07 3C36E4-EOSSTB-003356429500 WPEWebProcess[3353]: 230426-13:58:07.150428 [mod=MediaSourceSamples, lvl=INFO] [tid=16] SourceBuffer::sourceBufferPrivateDidReceiveSample(0x7c51fc00) - sample({PTS({40000000/1000000 = 40.000000}), DTS({40000000/1000000 = 40.000000}), duration({21333/1000000 = 0.021333}), flags(sync), trackId(A1), presentationSize(0.000000x0.000000)})`

**Comment by calvaris** [comment]
Just pushed some commits into https://github.com/WebPlatformForEmbedded/WPEWebKit/tree/calvaris/wpe-2.22-key-rotation . Maybe not all of them are need but it might be that some of them help with the issue. Could you please try and report back, please?

**Comment by jaroslaw-bojko-red** [comment]
Thank you for the info.
I tried to check the commits, but the Pluto app decided to change the playback and they switched to DASH playback and abandon the previous code base. I cannot check the patches on the code that causes the issues.
