### ISSUE TITLE
[wpe-2.28] CSS transormation starts from invalid position

### ISSUE THREAD

**Issue by asurdej-comcast** [Metrological/WebKitForWayland#1086]
There seems to be an issue with CSS animations when new "transform" property is set at the moment of previous transformation end. As a result new animation is started from previous animation starting point instead of current position causing jerk of animated element.

Here is an example code to demonstrate:
`<div id="diva" style="width: 60px; height: 60px; background-color: skyblue; transition: transform .2s linear">TextExample</div>`
JS:
`diva.style.transform = "translateX(480px)"; setTimeout(()=>{ diva.style.transform = "translateX(16px)"; }, 200);`

If both transitionDuration and setTimeout() are the same value (or very close) the second transition starts again from 0,0 position, instead of (almost) finished "480px".

Here is a page to demonstrate: https://asurdej-comcast.github.io/tests/transform.html
blue square should move smoothly but is jumping. (I can reproduce the same with Firefox PC browser)

The same test cases work fine with 2.38 so possibly it was fixed there but it's hard to find exact fix for this issue. It works fine with x86 2.38 WPEwebKit build as well as linux PC Epiphany browser 2.38 based

From what I can see so far is that from WebCore perspective, the previous animation is finished already but for some reason it again uses the same starting point for the next transformation.

We have two applications that uses .style.transform = "translateX(newPosition)" to handle seek bar during video playbacks and both have the same issue that seekbar is not smooth but is jerking.

Some logs:
WebAnimation 0x7f46ec7c2b00 play(autoRewind 1) (current time is nullopt)
  blending transform from translateX(0px, 0px, 0px) to translateX(480px, 0px, 0px) at 0 -> translateX(0px, 0px, 0px)
WebAnimation 0x7f46ec7c2b00 runPendingPlayTask (current time is 0.00s)
  blending transform from translateX(0px, 0px, 0px) to translateX(480px, 0px, 0px) at 0 -> translateX(0px, 0px, 0px)
  blending transform from translateX(0px, 0px, 0px) to translateX(480px, 0px, 0px) at 0 -> translateX(0px, 0px, 0px)
  blending transform from translateX(0px, 0px, 0px) to translateX(480px, 0px, 0px) at 0 -> translateX(0px, 0px, 0px)
  blending transform from translateX(0px, 0px, 0px) to translateX(480px, 0px, 0px) at 0.02 -> translateX(9.60px, 0px, 0px)
WebAnimation 0x7f46ec7c2b00 cancel(silently 0) (current time is 0.20s)
WebAnimation 0x7f46ec7c2e20 play(autoRewind 1) (current time is nullopt)
  blending transform from translateX(0px, 0px, 0px) to translateX(16px, 0px, 0px) at 0 -> translateX(0px, 0px, 0px)
WebAnimation 0x7f46ec7c2e20 runPendingPlayTask (current time is 0.00s)
  blending transform from translateX(0px, 0px, 0px) to translateX(16px, 0px, 0px) at 0 -> translateX(0px, 0px, 0px)
  blending transform from translateX(0px, 0px, 0px) to translateX(16px, 0px, 0px) at 0 -> translateX(0px, 0px, 0px)
  blending transform from translateX(0px, 0px, 0px) to translateX(16px, 0px, 0px) at 0 -> translateX(0px, 0px, 0px)
  blending transform from translateX(0px, 0px, 0px) to translateX(16px, 0px, 0px) at 0.07 -> translateX(1.04px, 0px, 0px)

First transformation from 0,0,0 to 480,0,0 is almost/done and second tranlation to 16px is again stated from 0,0,0 instead of 480,0,0 (or close)

**Comment by pgorszkowski-igalia** [comment]
I have checked that first working release version is webkitgtk/2.30(https://github.com/WebKit/WebKit/tree/webkitgtk/2.30) (webkit in gtk port can be built with jhbuild)

**Comment by asurdej-comcast** [comment]
From what I checked the flow it looks like at the moment of creating keyframes for second transition, the first one is already finished (it's progress is NaN and phase is "After") but transition completed callbacks were not yet triggered. Because progress is NaN KeyframeEffect doesn't compute new animation position so old values are used.

Currently as a workaround we disabled WebAnimations setting and this seems to help

**Comment by pgorszkowski-igalia** [comment]
Good news, I found from which commit it works: [679d2b61717c66d066a587364af1c0a25d99ba19](https://github.com/WebKit/WebKit/commit/679d2b61717c66d066a587364af1c0a25d99ba19)

Bad news: it can't be easily applied on 2.28 branch, probably more commits have to be cherry picked.

**Comment by magomez** [comment]
> Good news, I found from which commit it works: [679d2b61717c66d066a587364af1c0a25d99ba19](https://github.com/WebKit/WebKit/commit/679d2b61717c66d066a587364af1c0a25d99ba19)
> 
> Bad news: it can't be easily applied on 2.28 branch, probably more commits have to be cherry picked.

Yes, I've been studying the animation changes and suspected that that commit could be related, but it's not easily backported, as there are a lot of other commits that need to be picked as well. But after some investigation about what's happening, I think that this small change could be enough to fix the problem. At leas it works for me. @asurdej-comcast, could you give this patch a test?

[1086.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/11415178/1086.patch.txt)

**Comment by asurdej-comcast** [comment]
@pgorszkowski-igalia  @magomez 
Thanks for you help. Tested [1086.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/11415178/1086.patch.txt) with x86 build and I don't see this issue any more. I will run more verification later today.

As a fallback we still have option to disable webanimations feature so we should be good with current findings.
Thanks

**Comment by pgorszkowski-igalia** [comment]
@asurdej-comcast : We are still waiting for your confirmation before merge the patch.

**Comment by asurdej-comcast** [comment]
@pgorszkowski-igalia Sorry for delay. 1086 patch looks fine and  fixes the issue. I think we can merge it and close this ticket

**Comment by pgorszkowski-igalia** [comment]
The fix is merged: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1089
