### ISSUE TITLE
Localhost mixed-content whitelisting

### ISSUE THREAD

**Issue by jacek-skiba-red** [Metrological/WebKitForWayland#1095]
In Webkt upstream localhost connection are all the time treated as mixed content (https://bugs.webkit.org/show_bug.cgi?id=171934). In our WPE port we have API to enable/disable mixed content. eg on 2.38 branch: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1035

In our specific project have some applications which must block mixed content, but which also are using HTTP/WS connections to locahost services. Those sevices are by default blocked by mixed content rules. 

We think that changing internal communication from HTTP/WS to HTTPS/WSS in an overhead. 

Would it be possible to provide PR (for branch WPE 2.38) with the chance of merging, which would whitelist localhost connections? Solution would be under environment variable and would be treated as other WPE specific features (eg. non-composited mode) which are not upstreamable to Webkit .

FYI: @magomez

**Comment by magomez** [comment]
Have you tried using the whitelist API? Using that there's the option to bypass security checks for certain protocols and hosts. Maybe it's possible to use it to allow HTTP/WS connections to localhost without having to change anything in the code.

Not sure whether you're using WPEFramework. If you are, then those exceptions can be set through the json config file (not sure about the syntax though, you need to check that from the code).

**Comment by jacek-skiba-red** [comment]
We use WPEFramework, and I see whitelist property in webkitbrowser-plugin. I will check that. 
Thanks for quick support.

**Comment by jacek-skiba-red** [comment]
Unfortunately whitelist property only enables CORS origin-domain pairs. We will try to extend whitelisting mechanism with mixed-content checks. @magomez do you have something against it?

Looking at available Webkit API, `webkit_security_manager_register_uri_scheme_as_secure()` probably can be used:

https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.38/Source/WebKit/UIProcess/API/glib/WebKitSecurityManager.cpp#L250

**Comment by magomez** [comment]
> Unfortunately whitelist property only enables CORS origin-domain pairs. We will try to extend whitelisting mechanism with mixed-content checks. @magomez do you have something against it?
> 
> Looking at available Webkit API, `webkit_security_manager_register_uri_scheme_as_secure()` probably can be used:
> 
> https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.38/Source/WebKit/UIProcess/API/glib/WebKitSecurityManager.cpp#L250

mmmm if you use webkit_security_manager_register_uri_scheme_as_secure to register HTTP and WS as secure, that may fix your problem, but it will allow access to all HTTP and WS requests, which may not be what you want. Extending the whitelist feature seems probably better, so you can allow only the localhost HTTP and WS requests.

**Comment by jacek-skiba-red** [comment]
We extended WS/HTTP whitelisting and provided PR to 2.38: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1128
