### ISSUE TITLE
Polling an object property using setInterval - WPE-2.28

### ISSUE THREAD

**Issue by alkis-gkouzias-obs** [Metrological/WebKitForWayland#1097]
**Issue**
In the process of testing our HbbTV implementation in WebKit, we have encountered a scenario where the test polls for a specific property that belongs to an object (object tag) each 200ms.
This is performed by setting up an interval, using javascript setInterval. We can see that the callback of the interval is called correctly, every 200ms for the first 3 to 4 times; however the rest of the calls are happening between intervals of 1 second.

**Workarounds**
We have tried replacing the object tag with a simple div and this resulted in the correct behavior. We have also tried to change the test so that it polls a single variable instead, and this also worked as expected. 
It seems that querying the property of an object tag will cause the interval to bottleneck at 1 sec. 

**Code**
We are attaching the following test page which can be used to reproduce the issue
[testObj.cehtml.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/11612736/testObj.cehtml.txt)

**Comment by modeveci** [comment]
Hi @magomez , could you please look at this issue? It is a blocker for HBBTV certification.

**Comment by magomez** [comment]
Yes, I'm already looking into it. I've found that it's fixed in newer releases, so I'm trying to find the fix.

**Comment by magomez** [comment]
I've just pushed commit 1609d7b752d1e5534a401abdda42940158152ee4 to the wpe-2.28 with a fix for this.

@alkis-gkouzias-obs please verify that it works for you and close this if everything is ok. Thanks!

**Comment by alkis-gkouzias-obs** [comment]
Hello @magomez. I confirm that the throttling issue is resolved with your commit. Thanks!
