### ISSUE TITLE
[wpe-2.38] `systemMemoryUsedAsPercentage()` of `MemoryPressureMonitor` is invalid when swap enabled in container

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#1100]
At some point (https://bugs.webkit.org/show_bug.cgi?id=209186) the `systemMemoryUsedAsPercentage()` function of `MemoryPressureMonitor` was extended (https://github.com/WebKit/WebKit/commit/c6a6f7b0bb85be0462be59ea1b4a8dcbd8c2a41e) to account for cgroup-based measurements so that WK processes associated to a cgroup with memory controller or ran inside the container are calculating the "sandbox" memory usage more precisely.
The above change works well when swap memory is not used, but it struggles when it's enabled.

Let's imagine the following scenario:
 - WK processes are being run within container (hence associated to a cgroup with memory controller)
 - memory limit is 400M (visible in `memory.limit_in_bytes`)
 - memory limit including swap is 600M (visible in `memory.memsw.limit_in_bytes`)
 - memory usage at the moment is 400M (visible in `memory.usage_in_bytes`)
 - memory usage including swap is 600M (visible in `memory.memsw.usage_in_bytes`) because 200M is swapped out at the moment.

The problem with the above is - the current implementation will report `66.66% (400M/600M)` memory usage because it does not use the `memory.memsw.usage_in_bytes` file at all. In other words - when calculating the percentage, the implementation accounts for swap memory in the denominator while it does not in the numerator.

In my opinion the above can be fixed two ways:

1. By not using any `*.memsw.*` files
2. By accounting for swap memory properly i.e. reading `memory.memsw.usage_in_bytes` for calculating current usage
3. By using `memory.memsw.usage_in_bytes` for calculating current usage while not using `memory.memsw.limit_in_bytes` for calculating overall limit (usage >100% would be allowed then)

I'm not sure what scenarios the author (Pablo Saavedra from Igalia) had in mind but in my opinion, the option (3) would be the best in practice as having anything swapped usually means severe performance degradation therefore there's no point delaying any memory pressure events in case we still have some swap space left.

@pgorszkowski-igalia could you please loop Pablo in?

**Comment by pgorszkowski-igalia** [comment]
@Scony I forwarded your comment to Pablo.

**Comment by pgorszkowski-igalia** [comment]
@Scony please take a look: https://github.com/WebKit/WebKit/pull/14783

**Comment by psaavedra** [comment]
Hi. @Scony  did you have the opportunity of verifying if this patch satisfies 
 the problem reported here https://github.com/WebKit/WebKit/pull/14783 ?

**Comment by Scony** [comment]
Haven't tested, but the change looks good to me. I'll give it a try in couple days

**Comment by Scony** [comment]
Did a quick test - all good.

**Comment by psaavedra** [comment]
Nice. Thanks for verifying it.

**Comment by modeveci** [comment]
As it has been upstreamed, @psaavedra , @pgorszkowski-igalia  can we bring that change to wpe-2.38 downstream and then close this issue? Thank you

**Comment by psaavedra** [comment]
> As it has been upstreamed, @psaavedra , @pgorszkowski-igalia can we bring that change to wpe-2.38 downstream and then close this issue? Thank you

Added in https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1100#issuecomment-1697275529 butI dont know if there are going to be new releases for 2.38.x. However notice that this was already applied in 2.40.X: https://github.com/WebKit/WebKit/wiki/GLib-Stable-Branches#proposed-merges-1

**Comment by psaavedra** [comment]
> > As it has been upstreamed, @psaavedra , @pgorszkowski-igalia can we bring that change to wpe-2.38 downstream and then close this issue? Thank you
> 
> Added in [#1100 (comment)](https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1100#issuecomment-1697275529) butI dont know if there are going to be new releases for 2.38.x. However notice that this was already applied in 2.40.X: https://github.com/WebKit/WebKit/wiki/GLib-Stable-Branches#proposed-merges-1

Maybe I am confused. Probably what you want is to backport this  https://commits.webkit.org/265527@main in https://github.com/WebPlatformForEmbedded/WPEWebKit  in this case    @pgorszkowski-igalia can be the best one to do this task.

**Comment by modeveci** [comment]
Yes, that I meant :) @pgorszkowski-igalia could you please back-port that change and then close this ticket? Thank you!

**Comment by pgorszkowski-igalia** [comment]
Yes, I am preparing a PR for wpe-2.38 with that commit
