### ISSUE TITLE
[wpe-2.38] ParsingFailed error with "closedcaption/x-cea-608" using MSE

### ISSUE THREAD

**Issue by filipe-norte-red** [Metrological/WebKitForWayland#1101]
When playing back a stream with closed captions using MSE, AppendPipeline::parseDemuxerSrcPadCaps() (called from AppendPipeline::tryCreateTrackFromPad()) is returning an invalid stream type upon not finding a suitable decoder, which leads to a "parsing failed" error, causing the playback to be aborted. However, even if a suitable decoder would be present, the remaining code in parseDemuxerSrcPadCaps() only handles Video, Audio and Text caps, which would cause the "unknown" stream type to be returned and consequently a black hole probe to be used rather then having closed captions correctly handled.

Note: in wpe 2.22 and 2.28 this error does not occur because a black hole probe is used, consequence of "m_demux->numsrcpads > 1" holding true in connectDemuxerSrcPadToAppsinkFromStreamingThread().

**Comment by emutavchi** [comment]
Hi @modeveci, we see this on AppleTV content. As temporary workaround we plan to fallback to wpe-2.28 behavior (i.e. black hole probe for track with closedcaption/x-cea-608 caps).

**Comment by rawoul** [comment]
I have the following patches on 2.38 to fix the issue, I can create an MR if you think they are acceptable:

https://github.com/rawoul/WebKit/commit/9cf04dee2d02cf8feb7f260f354c0b6a0a599f01
https://github.com/rawoul/WebKit/commit/03d2ef2e18964426a308eb5a0770272de37a2446

**Comment by philn** [comment]
> I have the following patches on 2.38 to fix the issue, I can create an MR if you think they are acceptable:
> 
> [rawoul/WebKit@9cf04de](https://github.com/rawoul/WebKit/commit/9cf04dee2d02cf8feb7f260f354c0b6a0a599f01) [rawoul/WebKit@03d2ef2](https://github.com/rawoul/WebKit/commit/03d2ef2e18964426a308eb5a0770272de37a2446)

Yes please, can you submit this for review in upstream WebKit?

**Comment by philn** [comment]
I don't have access to Apple TV... Can you provide an append pipeline graph dump please?

I think one way to handle CEA-608 here would be to plug a `cea608tott` element, that converts CEA-608 to WebVTT. The problem then is that element is part of gst-plugins-rs, so you'd need build that in your platform (Rust is supported in Yocto nowadays, but no idea about buildroot).

**Comment by modeveci** [comment]
@emutavchi , Could you please elaborate questions you raised about source buffer mechanism? then we can get feedback from @philn

**Comment by philn** [comment]
i suspect the append pipeline parses some mp4 container that is multiplexing A/V and also CEA608. is this correct? That's why i'm asking the append pipeline dump.

also is this a regression compared to 2.28? was apple TV CC working fine there? Or is this a new feature you need in 2.38?

**Comment by rawoul** [comment]
![image](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/1200552/ac41c703-155c-4aa5-8aeb-5a99472db118)

Here's the pipeline dump, unfortunately on failure the actual subtitle caps are not shown. As you suspect the CEA608 captions are embedded in the video mp4 stream. The following message is also displayed in the logs:

```
webkitmse AppendPipeline.cpp:772:tryCreateTrackFromPad:<append-pipeline-video-mp4-0> Unsupported track codec: closedcaption/x-cea-608, format=(string)s334-1a
```

**Comment by philn** [comment]
Ok, so what i suggested about `cea608tott` still stands, unless we can feed the playback pipeline with CEA608 payloads directly and that would be handled internally there.

**Comment by emutavchi** [comment]
> @emutavchi , Could you please elaborate questions you raised about source buffer mechanism? then we can get feedback from @philn

@philn @modeveci we created this issue to start discussion around multi-track (of different types) support with single source buffer in WPE MSE implementation. The immediate use case is AppleTV. It appends muxed data (video and CC) to source buffer. The change proposed by @rawoul  workarounds the playback error (similar to how it was done with wpe-2.28) by dropping the CC data.  the doubt is whether it is the right approach.

**Comment by philn** [comment]
Ideally we shouldn't drop CCs, as I already commented.
Is `cea608tott` a usable element on your platforms?

**Comment by philn** [comment]
CCs should be parsed by the append pipeline and then the MSE src element should make those buffers available using one text track per detected CC stream.

**Comment by rawoul** [comment]
I'm not sure about OP (@filipe-norte-red) but I'm not pushing for my patches to be merged as they are easy to maintain. I don't plan to use the cea608tott elements for multiple reasons:
- we don't need the cea608 captions in our case and dropping them is fine.
- integrating gstreamer-rs and the additional rust plugins is not trivial.

**Comment by philn** [comment]
Totally agreed, I think we could make this element optional, if it's not found either drop the CC or forward it to the player as-is.

**Comment by philn** [comment]
> Ideally we shouldn't drop CCs, as I already commented. Is `cea608tott` a usable element on your platforms?

@emutavchi @modeveci Can you answer this question?

**Comment by modeveci** [comment]
Hi @philn ,
I think the main question here is the one below, AppleTv / x-cea608 is one of use-cases as mentioned by Eugene.   

_@philn @modeveci **we created this issue to start discussion around multi-track (of different types) support with single source buffer in WPE MSE implementation.** The immediate use case is AppleTV. It appends muxed data (video and CC) to source buffer._

**Comment by philn** [comment]
Yes, and you can re-read my answers: https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1101#issuecomment-1609622678 https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1101#issuecomment-1609625715

The problem is that if we want to handle CC data, we need a parser, that's why I'm asking if you guys are able to build `cea608tott` from gst-plugins-rs, which is currently, AFAIK, the only cea-608 parser available.

**Comment by philn** [comment]
So the CEA608 demo on http://reference.dashif.org/dash.js/latest/samples/#SubtitlesandCaptions doesn't work, right? Just making sure (I don't have access to Apple TV).

**Comment by calvaris** [comment]
Is this still a problem? Can we close this?

**Comment by filipe-norte-red** [comment]
@calvaris , based on further discussion with @emutavchi , we can close this.
