### ISSUE TITLE
In case of not valid URL, why decide-policy is not signalled.

### ISSUE THREAD

**Issue by modeveci** [Metrological/WebKitForWayland#1107]
There is already domain.com being loaded.

- When loading wrong/not-valid url from a new domain:
1. notify-uri with wrong not_valid_url
2. load-changed with WEBKIT_LOAD_STARTED
3. notify-uri with current url (domain.com) as the new url is wrong
4. load-failed with wrong not_valid_url

decide-policy is not triggered when internally it tries to load domain.com back again as not-valid-url is wrong.

This is how we are handling HTTPstatus in decide-policy callback:

static gboolean decidePolicyCallback(WebKitWebView*, WebKitPolicyDecision* decision, WebKitPolicyDecisionType type, WebKitImplementation* browser)
        {
            if (type == WEBKIT_POLICY_DECISION_TYPE_RESPONSE) {
                auto *response = webkit_response_policy_decision_get_response(WEBKIT_RESPONSE_POLICY_DECISION(decision));
                browser->SetResponseHTTPStatusCode(webkit_uri_response_get_status_code(response));
            }
            webkit_policy_decision_use(decision);
            return TRUE;
        }

Can you explain why decide-policy is not triggered when it tries to return back initial URL?

**Comment by magomez** [comment]
@modeveci, which wpe version is this?

**Comment by modeveci** [comment]
wpe-2.38 and prior versions

**Comment by magomez** [comment]
In the case of an invalid URL, decide-policy is not emitted when falling back to the previous page because we're nor reloading it. The load of the new page has failed, so we stay in the page that was loaded before, but nothing is really loaded. It's the same effect than not trying to load the invalid URL at all.

**Comment by modeveci** [comment]
Thank you @magomez for info. Closing the ticket!
