### ISSUE TITLE
[wpe-2.38] [RDK-42811] Crash in `JSC::CallLinkStatus::CallLinkStatus()`

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#1119]
Hi,

while integrating highbrow app we've encountered such a crash:
```
Core was generated by `/usr/libexec/wpe-webkit-1.1/WPEWebProcess 11 39'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  WTF::Vector<JSC::CallVariant, 1u, WTF::CrashOnOverflow, 16u, WTF::FastMalloc>::Vector () at WTF/Headers/wtf/Vector.h:964
964    WTF/Headers/wtf/Vector.h: No such file or directory.
[Current thread is 1 (Thread 0xae779ae0 (LWP 44))]
#0  WTF::Vector<JSC::CallVariant, 1u, WTF::CrashOnOverflow, 16u, WTF::FastMalloc>::Vector () at WTF/Headers/wtf/Vector.h:964
#1  0xb2007466 in JSC::CallLinkStatus::CallLinkStatus () at ../git/Source/JavaScriptCore/bytecode/CallLinkStatus.h:44
#2  JSC::DFG::ByteCodeParser::handleGetById () at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:4816
#3  0xb2007f32 in JSC::DFG::ByteCodeParser::parseGetById<JSC::OpGetById> () at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:5374
#4  0xb1ffb930 in JSC::DFG::ByteCodeParser::parseBlock () at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:6580
#5  0xb2004f96 in JSC::DFG::ByteCodeParser::parseCodeBlock () at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:8844
#6  0xb20057f8 in inlineCall<JSC::DFG::ByteCodeParser::handleCallVariant(JSC::DFG::Node*, JSC::Operand, JSC::CallVariant, int, JSC::VirtualRegister, int, JSC::BytecodeIndex, JSC::InlineCallFrame::Kind, JSC::SpeculatedType, unsigned int&, JSC::DFG::BasicBlock*, bool)::<lambda(JSC::CodeBlock*)> > () at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:1863
#7  JSC::DFG::ByteCodeParser::handleCallVariant () at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:1955
#8  0xb2006828 in JSC::DFG::ByteCodeParser::handleInlining () at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:2130
#9  0xb2006ba4 in JSC::DFG::ByteCodeParser::handleCall () at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:1358
#10 0xb20091ee in JSC::DFG::ByteCodeParser::handleCall<JSC::OpCall> () at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:1332
#11 0xb1ff8c00 in JSC::DFG::ByteCodeParser::parseBlock () at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:7198
#12 0xb2004f96 in JSC::DFG::ByteCodeParser::parseCodeBlock () at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:8844
#13 0xb20098ec in JSC::DFG::ByteCodeParser::parse () at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:9046
#14 0xb200a466 in JSC::DFG::parse () at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:9182
#15 0xb20c54c2 in JSC::DFG::Plan::compileInThreadImpl () at ../git/Source/JavaScriptCore/dfg/DFGPlan.cpp:201
#16 0xb22d2038 in JSC::JITPlan::compileInThread () at ../git/Source/JavaScriptCore/jit/JITPlan.cpp:172
#17 0xb22d5d78 in JSC::JITWorklist::enqueue () at ../git/Source/JavaScriptCore/jit/JITWorklist.cpp:84
#18 0xb20519dc in compileImpl () at ../git/Source/JavaScriptCore/dfg/DFGDriver.cpp:90
#19 JSC::DFG::compile () at ../git/Source/JavaScriptCore/dfg/DFGDriver.cpp:106
#20 0xb22d2bce in operationOptimize () at ../git/Source/JavaScriptCore/jit/JITOperations.cpp:2028
#21 0xab5ffc5a in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?) 
```
[taabtfull.log](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12000844/taabtfull.log)
[taabt.log](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12000846/taabt.log)

Steps to reproduce:

1. Run highbrow
2. After it started, run the video highlighted by default
3. Once playback started click DOWN and then RIGHT RCU buttons
4. Observe the crash

I'm not sure if I can provide the app URL here. Please reach out to @emutavchi if this is required. The URL is mentioned in RDK-42811.

**Comment by guijemont** [comment]
Hi and thanks for the report!

What exact version of WebKit are you using (ideally a commit reference on this repo)? It's hard to make sense of the code location in the stack trace without that information.

Also, for reproduction:
 - Does the crash happen everytime when following the reproduction steps, or is it an occasional thing?
 - @modeveci is the app in which it reproduces something I could get access to?

If reproduction on my side is not feasible, then I'd need a core file (or equivalent, e.g. a minidump), along with the matching binaries (ideally with debugging symbols included) to be able to investigate further.

**Comment by Scony** [comment]
@guijemont 

- the stacktrace is from 2.38 @ 47f4f3f68c85587553e6a8942547978335b232a9
- the issue happens 95% of the time if steps mentioned above are followed (on arm32 arch)

**Comment by jacek-skiba-red** [comment]
Similar crash we have on Broadcom based device on WPE 2.38:
```
Core was generated by `/appmodule/wpe/usr/libexec/wpe-webkit-1.0/WPEWebProcess 10 20'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  WTF::Vector<JSC::CallVariant, 1u, WTF::CrashOnOverflow, 16u, WTF::FastMalloc>::Vector () at WTF/Headers/wtf/Vector.h:964
964    WTF/Headers/wtf/Vector.h: No such file or directory.
[Current thread is 1 (Thread 0xf2b35010 (LWP 14))]
#0  WTF::Vector<JSC::CallVariant, 1u, WTF::CrashOnOverflow, 16u, WTF::FastMalloc>::Vector () at WTF/Headers/wtf/Vector.h:964
#1  0xf4cea47a in JSC::CallLinkStatus::CallLinkStatus () at /usr/src/debug/lib32-wpe-webkit/1_2.38+git-r0/git/Source/JavaScriptCore/bytecode/CallLinkStatus.h:44
#2  JSC::DFG::ByteCodeParser::handleGetById () at /usr/src/debug/lib32-wpe-webkit/1_2.38+git-r0/git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:4816
#3  0xf4ceb01a in JSC::DFG::ByteCodeParser::parseGetById<JSC::OpGetById> () at /usr/src/debug/lib32-wpe-webkit/1_2.38+git-r0/git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:5374
#4  0xf4cddc96 in JSC::DFG::ByteCodeParser::parseBlock () at /usr/src/debug/lib32-wpe-webkit/1_2.38+git-r0/git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:6580
#5  0xf4ce7ede in JSC::DFG::ByteCodeParser::parseCodeBlock () at /usr/src/debug/lib32-wpe-webkit/1_2.38+git-r0/git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:8844
#6  0xf4cecbe4 in JSC::DFG::ByteCodeParser::parse () at /usr/src/debug/lib32-wpe-webkit/1_2.38+git-r0/git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:9046
#7  0xf4ced790 in JSC::DFG::parse () at /usr/src/debug/lib32-wpe-webkit/1_2.38+git-r0/git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:9182
#8  0xf4db00ba in JSC::DFG::Plan::compileInThreadImpl () at /usr/src/debug/lib32-wpe-webkit/1_2.38+git-r0/git/Source/JavaScriptCore/dfg/DFGPlan.cpp:201
#9  0xf4fd65c4 in JSC::JITPlan::compileInThread () at /usr/src/debug/lib32-wpe-webkit/1_2.38+git-r0/git/Source/JavaScriptCore/jit/JITPlan.cpp:172
#10 0xf4fda488 in JSC::JITWorklist::enqueue () at /usr/src/debug/lib32-wpe-webkit/1_2.38+git-r0/git/Source/JavaScriptCore/jit/JITWorklist.cpp:84
#11 0xf4d3641e in compileImpl () at /usr/src/debug/lib32-wpe-webkit/1_2.38+git-r0/git/Source/JavaScriptCore/dfg/DFGDriver.cpp:90
#12 JSC::DFG::compile () at /usr/src/debug/lib32-wpe-webkit/1_2.38+git-r0/git/Source/JavaScriptCore/dfg/DFGDriver.cpp:106
#13 0xf4fd719e in operationOptimize () at /usr/src/debug/lib32-wpe-webkit/1_2.38+git-r0/git/Source/JavaScriptCore/jit/JITOperations.cpp:2028
```

Repoduction steps: start and quit few times Wikipedia app. WPEWebProcess crash usually after second/third attept.

Wikipedia URL: https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.metrological.app.Wikipedia==[x]route:home

**Comment by guijemont** [comment]
@Scony thanks for the information. Looking at the code where it crashes, I can't really understand what exactly is happening looking at the [crash location](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/47f4f3f68c85587553e6a8942547978335b232a9/Source/WTF/wtf/Vector.h#L964). I suspect it's a case of compiler optimization that's obfuscating a bit the stack trace.
So, from here, I have several questions to try to advance:
 - do you know how is the memory usage at the time of crash? Since it's crashing around the creation of a vector, an out of memory issue may be the underlying reason, though to understand it, I'd still need to go with one of the following 2 points below.
  - @modeveci are you able to provide me access to one of the apps shown to crash for reproduction?
  - if the above is not possible, @Scony or @jacek-skiba-red, are you able to provide me with a core file or minidump, with matching binaries with symbol files?
  
  Many thanks!

**Comment by jacek-skiba-red** [comment]
@guijemont From our side issue is reproducing mosty on Lightning apps. 

As mentioned above, crash is seen for Wikipedia app which is based on Lightning 2.4. However this URL can only be launched on our specific setup. App requires access to some internal ports.

Crash is not related to OOM issue. We have memory in system at that time. 

Issue also is visible in different scenario:
- play movie in videoland app (credentials are required):https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.videoland.ziggo==[x]route:app/alias/home
- play move from CNN app: 
https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.metrological.app.CNN
- during CNN playback start crash happends

Due to security issues we cannot share binaries (coredumps, symbols) with third parties, but we are happy to help via remote debug session. Ping me directly to arrange one: jacek.skiba@consult.red

**Comment by emutavchi** [comment]
@guijemont we see this crash randomly in different apps: Paramount+, PrimeVideo, YouTube, and others.

Sometimes it works without any issues for more than 12 hours (for example no issues were observed in playback endurance test). Sometimes it crashes after few minutes. I was able to reproduce it with key input stress test: https://ytlr-cert.appspot.com/latest/main.html?&test_type=manual-test&tests=18 (it took few hours in this case, and you'll need to use YT certified user agent if you want to reproduce it yourself).

> do you know how is the memory usage at the time of crash?

I don't have exact usage at the crash. According to device logs the memory usage was normal just before the crash
```
2023 Aug 02 15:26:13.950833 sh[5937]:    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
2023 Aug 02 15:26:13.951128 sh[5937]:   6755 root      20   0  609460 136916  41756 S   5.0  6.7  74:48.91 WPEWebProc+
```

> you able to provide me with a core file or minidump, with matching binaries with symbol files?

I can share one with @modeveci, and probably he can share it with you. The core dump is generated from build with reduced debugging symbols (webkit built with -g1), so it might not be that helpful.

**Comment by modeveci** [comment]
@guijemont I have shared binaries @emutavchi provided.
You can also use the url https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.metrological.app.CNN provided by @jacek-skiba-red  which does not require any credentials, it can launch on any reference platforms (I could launch on Safari).
If you need any other assistance please let me know.

**Comment by emutavchi** [comment]
@guijemont I've got a reproduction on build with more debug symbols enabled, and additional release assert check added to ByteCodeParser::handleGetById:

```
--- a/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp
+++ b/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp
@@ -4812,7 +4812,9 @@ void ByteCodeParser::handleGetById(
     // We've set some locals, but they are not user-visible. It's still OK to exit from here.
     m_exitOK = true;
     addToGraph(ExitOK);
-    
+
+    RELEASE_ASSERT(variant.callLinkStatus() != nullptr);
+
     handleCall(
         destination, Call, InlineCallFrame::GetterCall, osrExitIndex,
         getter, numberOfParameters - 1, registerOffset, *variant.callLinkStatus(), prediction);
```

crash callstack:
```
(gdb) bt
#0  __libc_do_syscall () at libc-do-syscall.S:49
#1  0xb16e3d14 in __libc_signal_restore_set (set=...) at ../sysdeps/unix/sysv/linux/internal-signals.h:86
#2  __GI_raise (sig=...) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0xb16d76dc in __GI_abort () at abort.c:79
#4  0xb1fb2238 in WTFCrashWithInfo () at WTF/Headers/wtf/Assertions.h:754
#5  JSC::DFG::ByteCodeParser::handleGetById (this=..., destination=..., prediction=..., base=..., identifier=..., identifierNumber=..., getByStatus=..., type=..., osrExitIndex=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:4816
#6  0xb1fb2942 in JSC::DFG::ByteCodeParser::parseGetById<JSC::OpGetById> (this=..., currentInstruction=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:5376
#7  0xb1fa3370 in JSC::DFG::ByteCodeParser::parseBlock (this=..., limit=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:6582
#8  0xb1faf982 in JSC::DFG::ByteCodeParser::parseCodeBlock (this=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:8846
#9  0xb1fb01e8 in JSC::DFG::ByteCodeParser::inlineCall<JSC::DFG::ByteCodeParser::handleCallVariant(JSC::DFG::Node*, JSC::Operand, JSC::CallVariant, int, JSC::VirtualRegister, int, JSC::BytecodeIndex, JSC::InlineCallFrame::Kind, JSC::SpeculatedType, unsigned int&, JSC::DFG::BasicBlock*, bool)::<lambda(JSC::CodeBlock*)> > (insertChecks=..., continuationBlock=..., kind=..., argumentCountIncludingThis=..., registerOffset=..., callee=..., result=..., callTargetNode=..., this=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:1863
#10 JSC::DFG::ByteCodeParser::handleCallVariant (this=..., callTargetNode=..., result=..., callee=..., registerOffset=..., thisArgument=..., argumentCountIncludingThis=..., osrExitIndex=..., kind=..., prediction=..., inliningBalance=..., continuationBlock=..., needsToCheckCallee=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:1955
#11 0xb1fb121c in JSC::DFG::ByteCodeParser::handleInlining (this=..., callTargetNode=..., result=..., callLinkStatus=..., registerOffset=..., thisArgument=..., argumentCountIncludingThis=..., osrExitIndex=..., callOp=..., kind=..., prediction=..., ecmaMode=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:2130
#12 0xb1fb159c in JSC::DFG::ByteCodeParser::handleCall (this=..., result=..., op=..., kind=..., osrExitIndex=..., callTarget=..., argumentCountIncludingThis=..., registerOffset=..., callLinkStatus=..., prediction=..., ecmaMode=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:1358
#13 0xb1fb3c20 in JSC::DFG::ByteCodeParser::handleCall<JSC::OpCall> (this=..., pc=..., op=..., callMode=..., osrExitIndex=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:970
#14 0xb1fa3a5a in JSC::DFG::ByteCodeParser::parseBlock (this=..., limit=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:7200
#15 0xb1faf982 in JSC::DFG::ByteCodeParser::parseCodeBlock (this=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:8846
#16 0xb1fb4358 in JSC::DFG::ByteCodeParser::parse (this=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:9048
#17 0xb1fb4f12 in JSC::DFG::parse (graph=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:9184
#18 0xb206fef6 in JSC::DFG::Plan::compileInThreadImpl (this=...) at ../git/Source/JavaScriptCore/dfg/DFGPlan.cpp:201
#19 0xb227aca0 in JSC::JITPlan::compileInThread (this=..., thread=...) at ../git/Source/JavaScriptCore/jit/JITPlan.cpp:172
#20 0xb227eaac in JSC::JITWorklist::enqueue (this=..., plan=...) at ../git/Source/JavaScriptCore/jit/JITWorklist.cpp:84
#21 0xb1ffc650 in JSC::DFG::compileImpl (callback=..., mustHandleValues=..., osrEntryBytecodeIndex=..., mode=..., profiledDFGCodeBlock=..., codeBlock=..., vm=...) at ../git/Source/JavaScriptCore/dfg/DFGDriver.cpp:90
#22 JSC::DFG::compile (vm=..., codeBlock=..., profiledDFGCodeBlock=..., mode=..., osrEntryBytecodeIndex=..., mustHandleValues=..., callback=...) at ../git/Source/JavaScriptCore/dfg/DFGDriver.cpp:106
#23 0xb227b846 in JSC::operationOptimize (vmPointer=..., bytecodeIndexBits=...) at ../git/Source/JavaScriptCore/jit/JITOperations.cpp:2028
#24 0xacd7517a in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) f 5
```

I'll share core dump via @modeveci  again.

**Comment by guijemont** [comment]
> @guijemont I've got a reproduction on build with more debug symbols enabled, and additional release assert check added to ByteCodeParser::handleGetById:
> 
> ```
> --- a/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp
> +++ b/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp
> @@ -4812,7 +4812,9 @@ void ByteCodeParser::handleGetById(
>      // We've set some locals, but they are not user-visible. It's still OK to exit from here.
>      m_exitOK = true;
>      addToGraph(ExitOK);
> -    
> +
> +    RELEASE_ASSERT(variant.callLinkStatus() != nullptr);
> +
>      handleCall(
>          destination, Call, InlineCallFrame::GetterCall, osrExitIndex,
>          getter, numberOfParameters - 1, registerOffset, *variant.callLinkStatus(), prediction);
> ```
> 
> crash callstack:
> 
> ```
> (gdb) bt
> #0  __libc_do_syscall () at libc-do-syscall.S:49
> #1  0xb16e3d14 in __libc_signal_restore_set (set=...) at ../sysdeps/unix/sysv/linux/internal-signals.h:86
> #2  __GI_raise (sig=...) at ../sysdeps/unix/sysv/linux/raise.c:48
> #3  0xb16d76dc in __GI_abort () at abort.c:79
> #4  0xb1fb2238 in WTFCrashWithInfo () at WTF/Headers/wtf/Assertions.h:754
> #5  JSC::DFG::ByteCodeParser::handleGetById (this=..., destination=..., prediction=..., base=..., identifier=..., identifierNumber=..., getByStatus=..., type=..., osrExitIndex=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:4816
> #6  0xb1fb2942 in JSC::DFG::ByteCodeParser::parseGetById<JSC::OpGetById> (this=..., currentInstruction=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:5376
> #7  0xb1fa3370 in JSC::DFG::ByteCodeParser::parseBlock (this=..., limit=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:6582
> #8  0xb1faf982 in JSC::DFG::ByteCodeParser::parseCodeBlock (this=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:8846
> #9  0xb1fb01e8 in JSC::DFG::ByteCodeParser::inlineCall<JSC::DFG::ByteCodeParser::handleCallVariant(JSC::DFG::Node*, JSC::Operand, JSC::CallVariant, int, JSC::VirtualRegister, int, JSC::BytecodeIndex, JSC::InlineCallFrame::Kind, JSC::SpeculatedType, unsigned int&, JSC::DFG::BasicBlock*, bool)::<lambda(JSC::CodeBlock*)> > (insertChecks=..., continuationBlock=..., kind=..., argumentCountIncludingThis=..., registerOffset=..., callee=..., result=..., callTargetNode=..., this=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:1863
> #10 JSC::DFG::ByteCodeParser::handleCallVariant (this=..., callTargetNode=..., result=..., callee=..., registerOffset=..., thisArgument=..., argumentCountIncludingThis=..., osrExitIndex=..., kind=..., prediction=..., inliningBalance=..., continuationBlock=..., needsToCheckCallee=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:1955
> #11 0xb1fb121c in JSC::DFG::ByteCodeParser::handleInlining (this=..., callTargetNode=..., result=..., callLinkStatus=..., registerOffset=..., thisArgument=..., argumentCountIncludingThis=..., osrExitIndex=..., callOp=..., kind=..., prediction=..., ecmaMode=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:2130
> #12 0xb1fb159c in JSC::DFG::ByteCodeParser::handleCall (this=..., result=..., op=..., kind=..., osrExitIndex=..., callTarget=..., argumentCountIncludingThis=..., registerOffset=..., callLinkStatus=..., prediction=..., ecmaMode=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:1358
> #13 0xb1fb3c20 in JSC::DFG::ByteCodeParser::handleCall<JSC::OpCall> (this=..., pc=..., op=..., callMode=..., osrExitIndex=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:970
> #14 0xb1fa3a5a in JSC::DFG::ByteCodeParser::parseBlock (this=..., limit=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:7200
> #15 0xb1faf982 in JSC::DFG::ByteCodeParser::parseCodeBlock (this=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:8846
> #16 0xb1fb4358 in JSC::DFG::ByteCodeParser::parse (this=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:9048
> #17 0xb1fb4f12 in JSC::DFG::parse (graph=...) at ../git/Source/JavaScriptCore/dfg/DFGByteCodeParser.cpp:9184
> #18 0xb206fef6 in JSC::DFG::Plan::compileInThreadImpl (this=...) at ../git/Source/JavaScriptCore/dfg/DFGPlan.cpp:201
> #19 0xb227aca0 in JSC::JITPlan::compileInThread (this=..., thread=...) at ../git/Source/JavaScriptCore/jit/JITPlan.cpp:172
> #20 0xb227eaac in JSC::JITWorklist::enqueue (this=..., plan=...) at ../git/Source/JavaScriptCore/jit/JITWorklist.cpp:84
> #21 0xb1ffc650 in JSC::DFG::compileImpl (callback=..., mustHandleValues=..., osrEntryBytecodeIndex=..., mode=..., profiledDFGCodeBlock=..., codeBlock=..., vm=...) at ../git/Source/JavaScriptCore/dfg/DFGDriver.cpp:90
> #22 JSC::DFG::compile (vm=..., codeBlock=..., profiledDFGCodeBlock=..., mode=..., osrEntryBytecodeIndex=..., mustHandleValues=..., callback=...) at ../git/Source/JavaScriptCore/dfg/DFGDriver.cpp:106
> #23 0xb227b846 in JSC::operationOptimize (vmPointer=..., bytecodeIndexBits=...) at ../git/Source/JavaScriptCore/jit/JITOperations.cpp:2028
> #24 0xacd7517a in ?? ()
> Backtrace stopped: previous frame identical to this frame (corrupt stack?)
> (gdb) f 5
> ```
> 
> I'll share core dump via @modeveci again.

Thank you, I got the files. Is that with https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/47f4f3f68c85587553e6a8942547978335b232a9 + your patch above?

**Comment by emutavchi** [comment]
@guijemont it is 07fdc0799c2f5a1c1b636531cf8f8d260d967e94 + patch above.  

Here is CR for the recipes that includes mentioned change: https://code.rdkcentral.com/r/c/rdk/components/generic/rdk-oe/meta-rdk-ext/+/89554

**Comment by emutavchi** [comment]
Hi @guijemont, do you have any updates?

**Comment by modeveci** [comment]
Hi @emutavchi,
We have been following this issue, but so far we could not reproduce as reported. Due to not being able to reproduce and based on provided data, it guides multiple possible suspected area and It makes hard to investigate. We are continuing to replicate based on provided use-cases. I hope that we can eventually have a crash here then it will be easier for us to investigate. If there is an easy way to reproduce, it will be very appreciated. 

In the meantime, Is it possible to optimize memory pressure values for Webprocess? And try with that setting. Because, as you might know, there was a crash reported for 2.22 on RDK for a prima app when there is endurance playback for long hours. As a workaround, webprocess pressure value reduced to 250M (from +350M), and it worked. If that is the case, then I think for @guijemont it can be a valuable input. 

Regards,
Ozgur

**Comment by emutavchi** [comment]
@modeveci 

> Because, as you might know, there was a crash reported for 2.22 on RDK for a prima app when there is endurance playback for long hours. 

are you referring to the crash seen on mips devices? I believe that is still observed with wpe-2.22 . but the reproduction rate for that is much lower comparing to this.

> As a workaround, webprocess pressure value reduced to 250M (from +350M), and it worked. 

I'm not aware of this. Could you please share the link to the ticket? I can try running an experiment with lower pressure settings. but that might hide the problem. browser instance running constantly under pressure may not even reach the DFG tier.

**Comment by modeveci** [comment]
Hi @emutavchi ,
I meant this ticket: https://jira.rdkcentral.com/jira/browse/WPEBROWSER-19
Ozgur

**Comment by emutavchi** [comment]
@modeveci thanks for sharing the link. We haven't seen this issue on our devices. Perhaps because we run a slightly different version of the app with a different player...

The suggestion to lower the memory pressure limits indeed helps to work around this crash in 2.38 case as well(I couldn't reproduce it yet). But, it doesn't look like the right solution.  I suspect it just hides the problem, by dropping code caches and effectively disabling DFG JIT.

**Comment by modeveci** [comment]
@emutavchi No I did not mean to see as a solution or workaround. It may help @guijemont to narrow down the suspected components. 

@guijemont , could you please take this into account? Basically, this problem comes from at least wpe-2.22 and observable on wpe-2.38, kicking in memory pressure mech. frequently hides the problem. 
Thanks

**Comment by guijemont** [comment]
Our investigations using the provided core file have advanced. Our understanding of the issue is now better, we have a simple reproduction case and an idea for a fix, which we're working on.
We've filed an [upstream issue](https://bugs.webkit.org/show_bug.cgi?id=260908) where you can find more information and the reproduction case.

**Comment by modeveci** [comment]
@guijemont , Great to hear that one! Please keep us updated. Thank you very much!

**Comment by guijemont** [comment]
The patch is [in review](https://github.com/WebKit/WebKit/pull/17232) upstream. I'm working on a backport to 2.38 in parallel.

**Comment by guijemont** [comment]
@emutavchi Here is the [patch](https://github.com/guijemont/WebKit/commit/ef8ff0f2a4ced1517b484d3c215eb19db4c4fa18), backported to wpe-2.38. It has seen only limited testing, so I recommend that, if possible, you only deploy this to a small subset of devices, big enough to confirm that the patch solves the issue, keeping an eye for potential regressions (though I think the risk is quite limited).

I'll wait for the patch to be landed upstream before merging it to [wpe-2.38](https://github.com/WebPlatformForEmbedded/WPEWebKit/tree/wpe-2.38).

**Comment by jacek-skiba-red** [comment]
The patch was verified on our side, and we don't any JSC crashes in Lightning apps. We don't see also other regressions.

**Comment by emutavchi** [comment]
@guijemont test result looks good from our side as well. We're testing on 32 bit targets. There are platforms where we built 64 bit target, that we haven't verified yet, and it may take a while. The discussion in 17232 suggests that the change may have regression on 64 bit system. Do you plan to refresh you patch before landing to wpe-2.38?

**Comment by guijemont** [comment]
> @guijemont test result looks good from our side as well. We're testing on 32 bit targets. There are platforms where we built 64 bit target, that we haven't verified yet, and it may take a while. The discussion in 17232 suggests that the change may have regression on 64 bit system. Do you plan to refresh you patch before landing to wpe-2.38?

My backport patch as linked above already includes the correction to the 64-bit issue raised in the upstream review.

**Comment by emutavchi** [comment]
> My backport patch as linked above already includes the correction to the 64-bit issue raised in the upstream review.

Great. Thanks for confirming. Any ETA for when it will land in wpe-2.38 branch?

**Comment by guijemont** [comment]
> > My backport patch as linked above already includes the correction to the 64-bit issue raised in the upstream review.
> 
> Great. Thanks for confirming. Any ETA for when it will land in wpe-2.38 branch?

I should hopefully be able to do that tomorrow.

**Comment by guijemont** [comment]
I just [pushed](https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/b19f56a9372318fbc3918beffded45c5bf652228) the backport to [wpe-2.38](https://github.com/WebPlatformForEmbedded/WPEWebKit/tree/wpe-2.38).
I'm going to close the issue, please reopen if there is an issue with the fix.
