### ISSUE TITLE
[wpe-2.38] media_content_types_requiring_hardware_support and audio decoders

### ISSUE THREAD

**Issue by jakub-gocol-red** [Metrological/WebKitForWayland#1122]
WPE-2.38 has webkit_settings_set_media_content_types_requiring_hardware_support function which allows to set pattern that is matched against codecs provided in MediaSource.isTypeSupported api. If there's a match, such codec will only by marked as supported, if there is hardware decoder available for it.

In rdk based projects such as mine, pattern is set [here](https://github.com/rdkcentral/rdkservices/blob/sprint/23Q3/WebKitBrowser/CMakeLists.txt#L66) to "video/*". I guess the idea was to require hardware decoder for all video codecs.

But it's very common for applications to call MediaSource.isTypeSupported with 'video/mp4; codecs="avc1.42E01E,mp4a.40.2"' as parameter. This matches "video/*" pattern for both codecs so both of them are required to have hardware decoder. But in [here](https://github.com/LibertyGlobal/WPEWebKit/blob/lgi-wpe-2.38/Source/WebCore/platform/graphics/gstreamer/GStreamerRegistryScanner.cpp#L342), where browser precomputes what codecs are supported and which of them have hardware decoders, it's just assumed that audio codecs don't have hardware decoders and MediaSource.isTypeSupported('video/mp4; codecs="avc1.42E01E,mp4a.40.2"') returns false.

1. Requiring hardware decoders for all video codecs and nothing else seem like the most common use case. With current implementation setting pattern to "video/*" is not working as intended. Is there any recommended pattern that we should use?
2. Should this pattern even be checked against audio codecs? Based on [this](https://github.com/LibertyGlobal/WPEWebKit/blob/lgi-wpe-2.38/Source/WebCore/platform/graphics/gstreamer/GStreamerRegistryScanner.cpp#L342) code, noone expects them to have hardware decoding.

**Comment by eocanha** [comment]
This feature was added when there was still no support for SourceBuffers with more than one stream (and therefore multiple codecs). Let me think of a way to make it compatible with multiple streams and I'll comment about it.

**Comment by eocanha** [comment]
I've been experimenting a bit with how the media_content_types_requiring_hardware_support evaluation works and I've come up with a string that works in your specific case. The corresponding WPEFramework/plugins/WebKitBrowser.json line should remain like this:

```
    "mediacontenttypesrequiringhardwaresupport": "video/*; codecs=\"avc*\":video/*; codecs=\"vp*\":video/*; codecs=\"av1*\"",
```

You should add any other codec that your hardware may support.

This setting gives the following result on my Raspberry Pi 3 here, which only supports h264 on hardware. I think this matches with your expectations:

-  MediaSource.isTypeSupported('video/mp4; codecs="avc1.42E01E"') = true
-  MediaSource.isTypeSupported('video/mp4; codecs="avc1.42E01E,mp4a.40.2"') = true
-  MediaSource.isTypeSupported('video/mp4; codecs="mp4a.40.2,avc1.42E01E"') = true
-  MediaSource.isTypeSupported('video/webm; codecs="vp09.00.50.08"') = false
-  MediaSource.isTypeSupported('video/webm; codecs="vp09.00.50.08,opus"') = false
-  MediaSource.isTypeSupported('video/webm; codecs="opus,vp09.00.50.08"') = false

**Comment by jakub-gocol-red** [comment]
thanks, it's a bit tedious process, but it indeed will work.
