### ISSUE TITLE
[wpe-2.38] WPEWebProcess crash in AXObjectCache::handleAttributeChange

### ISSUE THREAD

**Issue by filipe-norte-red** [Metrological/WebKitForWayland#1123]
Under certain circumstances, the following line inside AXObjectCache::handleAttributeChange() causes a crash:
```
if (!attrName.localName().string().startsWith("aria-"_s))
```

The crash is caused by the following sequence:
1. performDeferredCacheUpdate() calls handleAttributeChange() with a reference to an instance from m_deferredAttributeChange

_AXObjectCache::performDeferredCacheUpdate()_
```
    for (const auto& attributeChange : m_deferredAttributeChange)
        handleAttributeChange(attributeChange.first, attributeChange.second);
```
2. handleAttributeChange() calls handleRoleChanged(Element* element) using the instance passed to it in performDeferredCacheUpdate()

_AXObjectCache::handleAttributeChange()_
```
    if (attrName == roleAttr) {
        handleRoleChanged(element);
    }
```
3. handleRoleChanged() calls remove(*element) which removes the attribute from m_deferredAttributeChange vector

_AXObjectCache::handleRoleChanged()_
```
    if (is<AccessibilityARIAGrid>(object)
        || is<AccessibilityARIAGridRow>(object)
        || is<AccessibilityARIAGridCell>(object)) {
        // These classes instances are created based on the role attribute of the underlying Element.
        // Thus when the role changes, remove the object and force a ChildrenChanged on the parent so that the object is re-created.
        auto* parent = object->parentObject();
        remove(*element);
        childrenChanged(parent);
        return;
    }
```

_AXObjectCache::remove()_
```
        m_deferredAttributeChange.removeAllMatching([&node] (const auto& entry) {
            return entry.first == &node;
        });
```

As handleAttributeChange() was called with a reference to an instance that was now removed from m_deferredAttributeChange vector, the original reference is now invalid and accessing it leads to undefined behavior. 

This implies actually 2 problematic situations:
1. The code in handleAttributeChange() is using a reference that is likely to be invalidated 
3. The handleAttributeChange() method is called from a loop over m_deferredAttributeChange while elements in this vector may be invalidated

**Comment by filipe-norte-red** [comment]
Pull request with fix: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1124

**Comment by magomez** [comment]
Thanks for the detailed report @filipe-norte-red , and thanks for taking the time to find the fix! I've just merged it. Feel free to close the issue when you have verified that the fix works.

**Comment by filipe-norte-red** [comment]
Thanks, @magomez.
