### ISSUE TITLE
[2.38] Crash when destroying the web view

### ISSUE THREAD

**Issue by magomez** [Metrological/WebKitForWayland#1134]
I'm creating this to handle the issue reported in https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1129, and I'll close that PR as this should be handled in a different way.

There is a change in 2.38 that makes WebProcess exit cleaner by calling exit handlers (registered with atexit()) instead of using _exit() that skips handlers execution.
Unfortunately this causes a crash inside NicosiaGCGLLayer.cpp:

terminateWindowContext()
~GLContextEGL():

    if (m_surface)
        eglDestroySurface(display, m_surface);
Surface destruction crashes as WPE compositor and native window are closed because UIProcess exited already.

This revert brings back wpe-2.28 behavior.

But there is another part of this issue. How to make sure that at the point of the UIProcess exit WebProcess (all child processes basically) are closed so it is safe to close compositor and clean up native parts? Currently we use g_clear_object(view) that destroys WebKitWebView obj but WebProcess seems to be running still
https://github.com/rdkcentral/rdkservices/blob/sprint/23Q3/WebKitBrowser/WebKitImplementation.cpp#L2963

Do you have any suggestion here?

**Comment by magomez** [comment]
@asurdej-comcast the crash that you're reporting is happening with nonCompositedWebGL enabled. Does this happens if you do exactly the same operations (open the same page and then close) without nonCompositedWebGL enabled?  Or is it working  properly?

I've been looking into how the WebProcess is destroyed and doing a sync close is not an easy feat as it's not designed to work that way. What I'm thinking instead is to try to ensure that the compositor assets are released before the view is destroyed.

**Comment by asurdej-comcast** [comment]
IIRC the same crash happens with noncomposited webgl disabled also. Crashes at the exact same place (exit handler that destroys this static eglSurface).

In general we have two cases that we wan't to handle more or less correctly:
1) Correct shutdown: we receive deactivation request in UIProcess (WPE webkit browser plugin) and we clear webkitwebview. After this compositor is destroyed (but WebProcess is still there sometimes so it will be useful to have EGL stuff destroyed synchronously)
2) Compositor kill/crash shutdown: in such case we are not able to do much other than kill UIProcess and WebProcess

**Comment by magomez** [comment]
> IIRC the same crash happens with noncomposited webgl disabled also. Crashes at the exact same place (exit handler that destroys this static eglSurface).

That shouldn't be the case, as that atexit() callback is only created when nonCompositedWebGL is enabled. When nonCompositedWebGL is disabled, the glContext that renders to the compositor surface is in another place, and it's not static.
But there's the possibility that a similar crash happens when we're releasing that glContext if the compositor assets have been destroyed.

> In general we have two cases that we wan't to handle more or less correctly:
> 
> 1. Correct shutdown: we receive deactivation request in UIProcess (WPE webkit browser plugin) and we clear webkitwebview. After this compositor is destroyed (but WebProcess is still there sometimes so it will be useful to have EGL stuff destroyed synchronously)

This is what I'm trying to fix now. I won't be able to do a sync close, but I should be able to ensure that the WebProcess releases the compositor assets before the UIProcess is finished.

> 2. Compositor kill/crash shutdown: in such case we are not able to do much other than kill UIProcess and WebProcess

There's not much that we can do in this case. If the compositor is killed or crashes, and the surface that the WebProcess is using gets invalidated, the WebProcess is probably going to crash (depends on the gl implementation). Even if WPEFramework detected the problem with the compositor and tried to notify the browser somehow, that's going to take time, and the browser is going to try to render a frame to the invalidated surface before that.

**Comment by magomez** [comment]
@asurdej-comcast I've created a patch that forces the WebProcess to destroy the compositor surface before the UIProcess is finished. This should fix the crash when nonCompositedWebGL is enabled and the browser plugin is stopped. I'm attaching the patch here, please give it a try and tell me whether it really fixes the problem.

When not using nonCompositedWebGL the compositor surface is destroyed in a different place, and not in the atexit handler, so it's a different case. But it could lead to a crash as well because that destruction may happen after the UIProcess is finished. Please, try an execution with nonCompositedWebGL disabled and tell me whether there's a crash as well, and I can modify this patch to fix that case as well.

[1134.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12269956/1134.patch.txt)

**Comment by asurdej-comcast** [comment]
@magomez Sorry for the delay. Tested your patch and it looks good. Platform surface is destroyed synchronously with web_view close  and offscreen surface doesn't crash on destruction. Tested with Amlogic device (same as before). This part works fine.

Regarding nonCompositedWebGL, there is also a crash but, as you said, surface destruction is not triggered from atexit() handler but somewhere else. Not really sure where exactly as I don't have full stacktrace

**Comment by magomez** [comment]
@asurdej-comcast I understand this is fixed now, after merging https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1230 ?

**Comment by asurdej-comcast** [comment]
@magomez Yes, I think all the shutdown crashes should be fixed now. We can close this issue. Thank you for your support
