### ISSUE TITLE
[WPE-2.22] Launching of Teletext app is not smooth

### ISSUE THREAD

**Issue by suresh-khurdiya-epam** [Metrological/WebKitForWayland#1137]
Hi All,

We are having an issue with teletext application. When we are launching the teletext application then we are seeing first flickering of black screen or jumble or Junk character screen and after that actual teletext page is loaded.
It is happening with minimal test application as well.

We are using cairo version 1.16 with some customise patch on our platform.
As per the initial investigation, It seems like that flavour version is downgraded to CAIRO_GL_FLAVOR_ES2 and this is the root cause. Having CAIRO_GL_FLAVOR_ES3 we don't see this teletext issue, but then Gfx memory is seen

We have below patch which is added to fix the Memory leak issue for GFX (graphics).
[ARRISAPOL-2854-Fix-device-errors-for-GLESv2-contexts.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12250709/ARRISAPOL-2854-Fix-device-errors-for-GLESv2-contexts.txt)

Please find attached picture\video as a reference
![scramble_504_eos](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/136487900/0d6756ac-8a03-485a-b5d5-5d5d3eae3daa)
![scrambled](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/136487900/fd30a1d3-c2eb-47f9-adf9-28b9cd984d76)
https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/136487900/2e97bbfc-987c-4524-9af6-76f8097e4c0a

And,I am also attaching a test application for a reference.
[canvasDrawing.html.zip](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12250744/canvasDrawing.html.zip)

**Comment by jacek-skiba-red** [comment]
Issue was fixed by disabling 2dcanvas hardware acceleration on WPE 2.22.
With disabling on HW acceleration we lost rendering performance, but for that kind of not demanding apps this problem can be skipped.
