### ISSUE TITLE
[wpe-2.38] Regression in SVG lightning filter

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#1145]
To reproduce, run ACT-1345 test case from BBC cert suite, for that run:

- https://certification.bbctvapps.co.uk/act/client/ in the WPE-WebKit-based browser
- https://certification.bbctvapps.co.uk/act/portal/ locally and pair the two

### 2.28

![228](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/1207385/1ff54567-a749-4e1a-b041-cf09533b7ee2)

### 2.38

![238](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/1207385/e0370a34-5e91-458b-a7b4-fb0eaa0c39f1)

Please note that the issue happens regardless of LBSE being used or not (`ENABLE_LAYER_BASED_SVG_ENGINE` option).

**Comment by Scony** [comment]
> Please add a wpe-x.xx version label to the issue.

I can't add labels...

**Comment by woutermeek** [comment]
Oh, well that is not good :) Let me check that.

**Comment by Scony** [comment]
Direct link to problematic SVG: https://certification.bbctvapps.co.uk/act/test/ui/187/svg-supports-filter-lighting/actual-lighting.svg

**Comment by pgorszkowski-igalia** [comment]
I backported the fix from the upstream which implements the same thing in clearer and proper way:
wpe-2.38: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1235
wpe-2.42: https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1236

**Comment by Scony** [comment]
Thanks! I'll give it a try in upcoming week or two.

**Comment by amol-virnodkar-infosys** [comment]
I ported the fix(https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1235) with WPE 2.38 and tested the fix on a Broadcom based device, we are observing the issue in WPE 2.38 as below. The shades are bit darker in colour.

![svg](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/148946627/5610319c-0c09-446b-b3ce-56347ffe4556)

We will be verifying this fix on a reference video accelerator device soon. 
@pgorszkowski-igalia  Could you please check the behavior in the above image and provide your inputs.

**Comment by Scony** [comment]
@amol-virnodkar-infosys in the Firefox the shades are bit darker as well.

**Comment by Scony** [comment]
@pgorszkowski-igalia I forgot to mention - few weeks ago I was testing your changes and it's all good.

**Comment by rychem** [comment]
@pgorszkowski-igalia in context of darker 'actual rendering' reported by @amol-virnodkar-infosys - test results for wpe2.22 are the same as indicated above for 2.28 (expected=actual)

**Comment by pgorszkowski-igalia** [comment]
@amol-virnodkar-infosys , @rychem :  I can confirm that in case of wpe 2.38 the actual results are a bit darker (RPi3B+).

It seems that also in upstream FELighting does not work correctly for ARM NEON. It is another part which does not work after refactoring change (similar to the FEComposite things). The fix will be provided in upstream and then backported.

@amol-virnodkar-infosys: nice finding, thanks

**Comment by rychem** [comment]
Thanks @pgorszkowski-igalia for confirmation. 
Is this ticket supposed to be reopened or other ticket is created for trackability ... ?

**Comment by pgorszkowski-igalia** [comment]
@rychem : maybe it would be better to create a separate ticket for it. Thanks.

**Comment by amol-virnodkar-infosys** [comment]
@pgorszkowski-igalia Created a new ticket - https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1274 as suggested by you. Thanks.
