### ISSUE TITLE
Shoutcast live streams spend too much time buffering

### ISSUE THREAD

**Issue by jacek-manko-red** [Metrological/WebKitForWayland#1148]
In case of some shoutcast live streams - e.g this one:
https://media-ssl.musicradio.com/SmoothLondon
buffering can take about one minute before the playback starts.

Buffering level is based on the state of gstqueue2 element - yet it's also being drained but downstream elements. We've seen it filled to e.g 40%, then drained back to 0%.

We have a workaround for this - https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1147
though there's probably a better way to handle it.

**Comment by calvaris** [comment]
From what I see after investigating this with that very stream, the queue gets the `max-size-bytes` property set by uridecodebin after acting upon a tag event created by aacparse. This is:

1. aacparse emits a tag event with the bitrate
2. uridecodebin captures that message in a probe and sets the queue to the proper value around 12000 bytes

Playback always starts instantly both on the rpi and the reference box which uses broadcom plugins.

Can you please share a pipeline dump SVG file?

**Comment by jacek-skiba-red** [comment]
Our WPE 2.38 Broadcom based pipeline from "Smooth London" shoutcast stream dont contain AACParse plugin:
![smooth_london_pipeline](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/42027818/b6ece33c-fc7a-437e-881b-da1f3aca8a04)

**Comment by calvaris** [comment]
Is aacparse present in your system?

**Comment by suresh-khurdiya-epam** [comment]
Yes,
aacparse: Factory Details:
aacparse:   Rank                     primary + 1 (257)
aacparse:   Long-name                AAC audio stream parser
aacparse:   Klass                    Codec/Parser/Audio
aacparse:   Description              Advanced Audio Coding parser
aacparse:   Author                   Stefan Kost <stefan.kost@nokia.com>
aacparse: 
aacparse: Plugin Details:
aacparse:   Name                     audioparsers
aacparse:   Description              Parsers for various audio formats
aacparse:   Filename                 /usr/lib/gstreamer-1.0/libgstaudioparsers.so
aacparse:   Version                  1.18.5
aacparse:   License                  LGPL
aacparse:   Source module            gst-plugins-good
aacparse:   Source release date      2021-09-08
aacparse:   Binary package           GStreamer Good Plug-ins source release
aacparse:   Origin URL               Unknown package origin
aacparse: 
aacparse: GObject
aacparse:  +----GInitiallyUnowned
aacparse:        +----GstObject
aacparse:              +----GstElement
aacparse:                    +----GstBaseParse
aacparse:                          +----GstAacParse
aacparse: 
aacparse: Pad Templates:
aacparse:   SRC template: 'src'
aacparse:     Availability: Always
aacparse:     Capabilities:
aacparse:       audio/mpeg
aacparse:                  framed: true
aacparse:             mpegversion: { (int)2, (int)4 }
aacparse:           stream-format: { (string)raw, (string)adts, (string)adif, (string)loas }
aacparse:

**Comment by jacek-manko-red** [comment]
We've retested the above Shoutcast stream, and it's now working without issues. Lets close this.
