### ISSUE TITLE
Cairo opengl backend removal

### ISSUE THREAD

**Issue by jacek-skiba-red** [Metrological/WebKitForWayland#1149]
Cairo in version 1.17.8 removed opengl accelerated backend: https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/287?commit_id=b5793081d095a13517e157d793b367e4527fd39d#9cb48bb94f56cc85e3425240fcf144669a65844f

Reasons:
> The GL support in Cairo has always been a prototype, and nothing happened in the past 10 years to make it work as it was meant to.

Cairo in WPE integration by default is using opengl backend:
https://github.com/WebPlatformForEmbedded/meta-wpe/blob/main/recipes-wpe/wpewebkit/wpewebkit.inc#L37

During integration of latest versions of WPE, we had several bugs related to Cairo OpenGL backend (where most of WPE deployments in RDK word are based on yocto 3.1, which is using Cairo 1.16): 
* https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1137
* https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1131
* https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1105
* https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/973

Having those arguments in mind, WPE should consider disabling opengl backend in Cairo versions below 1.17.8?

**Comment by magomez** [comment]
WPE in WebPlatformForEmbedded is using cairo 1.16 for the implementation of the accelerated canvas, and it's going to continue doing so until there is an alternative implementation to it.
If you don't require the accelerated canvas in your platform, feel free to disable it and upgrade cairo. But if you require the accelerated canvas functionality, you need to stay with cairo 1.16.

**Comment by jacek-skiba-red** [comment]
Our platforms have GPU (based on VideoCore), and when we run Lightning apps then (having opengl hardwave acceleration enabled) we see GPU memory usage in WPE. 

Based on side by side tests, comparing the same WPE with and without opengl acceleration, we not observed any performance differences. 

@magomez are you aware of any testcases/scenarios which require in WPE (2.22, 2.38) hardware acceleration?

**Comment by magomez** [comment]
Any application that uses a canvas that's bigger than 1/4 of the display, which is when the canvas becomes accelerated. You can check, for example http://www.smashcat.org/av/canvas_test/ which is way faster with accelerated canvas enabled.

Also, don't confuse Lightning, which is based on WebGL, with accelerated canvas, which is used for 2D canvas. WebGL is always hw accelerated.

**Comment by jacek-skiba-red** [comment]
In general Lightning has possibility to render with 2d or 3d (https://github.com/rdkcentral/Lightning/blob/master/src/platforms/browser/WebPlatform.mjs#L360), but in our case it's always using webgl. 

Thanks @magomez for detailed explanation.
