### ISSUE TITLE
Newest version doesn't builds with punch hole gstreamer set

### ISSUE THREAD

**Issue by sarkanyi** [Metrological/WebKitForWayland#115]
I get this error:
../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp: In member function 'void WebCore::MediaPlayerPrivateGStreamerBase::pushTextureToCompositor()':
../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:684:70: error: cannot bind 'WTF::RefPtr<WebCore::GraphicsContext3D>' lvalue to 'WTF::RefPtr<WebCore::GraphicsContext3D>&&'
         RefPtr<BitmapTexture> texture = adoptRef(new BitmapTextureGL(m_context3D));
                                                                      ^
In file included from ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:80:0:

The lines may be shifted as I have some own patches also, but basically the problem is that m_context3D.copyRef() has to be used as it was before.

**Comment by zdobersek** [comment]
Should be fixed with https://github.com/Metrological/WebKitForWayland/commit/444fe103b60b2a20bb48409df385faa9ab663c9f.
