### ISSUE TITLE
[WPE-2.38] Images with loading="lazy" attribute are flushing when element is recreated from scratch

### ISSUE THREAD

**Issue by jakub-gocol-red** [Metrological/WebKitForWayland#1165]
Images with loading="lazy" attribute are flushing when element is recreated from scratch.

Issue originally came up on Blue TV application (https://apps.sctv.ch/ottbigscreen-upc/) where video thumbnails are flashing when scrolling horizontally. This app requires account, so I reduced it to minimal example. 

### Reproduction steps
1. Load [bluebox.zip](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12549450/bluebox.zip) test page
2. Press any button multiple times

### Expected behaviour
Image is not flashing. There is no new network request visible in devtools in network tab.

### Actual behavior
Image flashes. There's new network request visible in devtools in network tab.

### Notes
* It doesn't reproduce when I remove loading="lazy" from img tag, or when I disable lazy loading feature (hardcoding [this](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.38/Source/WebCore/dom/Document.cpp#L9243) function to always return false)
* it works correctly on google chrome and wpe-2.22 (because it doesn't have lazy loading feature)
* it doesn't work correctly on epiphany 44.6

Behavior on Blue TV application on wpe 2.38:
https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/93707234/b0f4e5f0-ee23-4cf6-bf5f-683552db3eae

Behaviour on Blue TV application on wpe 2.38 with lazy loading disabled:
https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/93707234/b80e9f1e-ff25-4366-b135-6896d9182ec3

Minimal testcase attached to the ticket on wpe 2.38:
https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/93707234/0e153d76-60cc-4839-8d0a-64f93daf3894

**Comment by pgorszkowski-igalia** [comment]
@jakub-gocol-red  can you check does fix from https://github.com/WebKit/WebKit/pull/18271 solve this problem?

**Comment by jakub-gocol-red** [comment]
yes, it solves this issue

**Comment by pgorszkowski-igalia** [comment]
The fix from upstream is backported to 2.38 and 2.42:
https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1209
https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/1210

@jakub-gocol-red: I close this issue.
