### ISSUE TITLE
[WPE-2.38] Regression in playing MSE streams with playbin3

### ISSUE THREAD

**Issue by marcin-mielczarczyk-red** [Metrological/WebKitForWayland#1171]
After recent merge of the latest "wpe-2.38" branch, MSE playback stopped working.
It turned out that the culprit is the following commit (removed Westeros autoplug hack):
https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/0035d13e0c9136ac14d8bd779c75f3d3efede365

When I reverted the commit, playbin3 properly plays MSE streams.
Gstreamer MR was not yet merged, so in my opinion we should still use the hack:
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/4391

A lot of vendors are still using older gstreamer versions and even when solution will be delivered to gstreamer upstream, this hack will be needed for some platforms.
Maybe option to enable/disable this hack should be introduced?

Platform: Broadcom
Gstreamer version: 1.18
Logs: 
[autoplug_problem.zip](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/12580900/autoplug_problem.zip)

**Comment by modeveci** [comment]
@marcin-mielczarczyk-red, can you use these patches on gstreamer 1.18.
https://github.com/WebPlatformForEmbedded/buildroot/commit/8ea57bbabe7cf149d317fc5a59da820a34ce001b
Regards,
Ozgur

**Comment by marcin-mielczarczyk-red** [comment]
@modeveci sure, I'll try them.
Thank you.

**Comment by marcin-mielczarczyk-red** [comment]
atches for gstreamer 1.18 sent by @modeveci  solved autoplug issue and MSE streams are working fine without Westeros autoplug hack.
I'm closing the ticket.
Thank you for support.
