### ISSUE TITLE
Best way to utilize VA-API

### ISSUE THREAD

**Issue by septatrix** [Metrological/WebKitForWayland#1217]
Starting with WPE WebKit 2.36.3 the legacy GStreamer VAAPI decoding plugins are disabled by default. For our use-case we sadly cannot forego hardware decoding. I know that `WEBKIT_GST_ENABLE_LEGACY_VAAPI=1` can be used to suppress this behaviour. Were the problems with the VAAPI plugins mostly visual or were there also commonly memory leaks, crashes etc? The former would be acceptable for us to be able to utilize hardware decoding.

Also thanks to the comment in the code I found out about the new VA decoders like `vah264dec`. Currently they are not automatically used by gstreamer unless one overrides the rank manually. Has WPE already tested compatibility with those? Or does it use high-level gst APIs such that those decoders should simply work?

Any advice or general information about the state of this would be appreciated.

**Comment by philn** [comment]
Yes, the new `va` decoders are tested in WPE. Their rank was bumped in GStreamer main, scheduled to ship 1.24. BTW This issue tracker is for downstream deployments of WPE. For upstream questions and bug reports, please refer to https://bugs.webkit.org
