### ISSUE TITLE
RPI3 Mouse/Touch Input Support

### ISSUE THREAD

**Issue by sommerma874** [Metrological/WebKitForWayland#1237]
I'm building WPE Platform for an RPI3 and the build works as expected. 

I would need Mouse/Touch input support for WebKitBrowser. Currently i'm finding no option how i can enable a basically mouse Input working with raspberrypi3_wpe_defconfig. 

I already tried setting Touch and Cursor to true in /etc/WPEFramework/plugins/WebKitBrowser.json. I can see the cursor in WebKitBrowser, but when moving Mouse nothing happens in webkitbrowser. 

Is there something missing in Build config for basic Mouse support? 

For advanced use-cases i want to use an HDMI Touchscreen with an USB Cable for touch input. The touchscreen works in Raspian without any problems. Are there some tips, what i can try get this working with BR and RPI3? 

Thanks in advance for your help!

BR Markus

**Comment by modeveci** [comment]
This is not about wpewebkit support, you can check related buildroot repo/s. Closing the issue
