### ISSUE TITLE
[wpe-2.22] DRM Widevine license renewal fails

### ISSUE THREAD

**Issue by laurence-ejraee** [Metrological/WebKitForWayland#1256]
On wpe-2.22 branch (tried with latest commit) it seems widevine renewal doesnt work whereas in wpe-2.28 it is working.
I used Axinom to create a very simple Widevine renewal and tested with Bitmovin, but when a new license is requested: I see the request made, license response received, but the DrmLicenseAdded event never fires (I suspect from WebKit side) and the player gives error "Key not available":

_[Debug] drm license request base64: – "CAES/wwKrgwIARL/CQq/AggCEhDmhRykwmjVTMfTCNajdCfVGIj55asGIo4CMIIBCgKCAQEAlx00lGR96OI3qD0eyEzD+5/cpvF1IbFah0sW8v8Zy/TgUqYXuYt3z6/4CAZARyy2Xu3O…" (bitmovinplayer.js, line 11)_

_[Debug] drm license response base64: – "CAIS3AIKOgogMzhGRjc5QkQ4RkE4NEYzMzA1MDAwMDAwMDAwMDAwMDASCJZ/rceOEQlfIAEoADgAQABIr/rlqwYSHAgBEAEYASAAKAAw3wE4PEIASKMBUApYAXAAeAAaZhIQqoICQNRh…" (bitmovinplayer.js, line 11)_

_[Log] DrmLicenseAdded ===  – {type: "drmlicenseadded", timestamp: 1702460721626, license: {id: "1", keyIds: ["_

**(First request works)** 

_[Debug] drm license request base64: – "CAESVBJCGkAKOgogMzhGRjc5QkQ4RkE4NEYzMzA1MDAwMDAwMDAwMDAwMDASCJZ/rceOEQlfIAEoADgAQABIr/rlqwYQBBgEGAIgtfrlqwYwFTiayuPeBRogoxC85+6qCH8dhy/he5AO…" (bitmovinplayer.js, line 11)_

_[Debug] drm license response base64: – "CAISbgo6CiAzOEZGNzlCRDhGQTg0RjMzMDUwMDAwMDAwMDAwMDAwMBIIln+tx44RCV8gASgBOABAAEiv+uWrBhISCAEYATDvATg8QgBIswFQClgBGhYgA0ISChBrY3RsAAAA71vY5RoA…" (bitmovinplayer.js, line 11)_

**(Second request/license renewal added event missing)** 

_[Error] PlayerError(1204/SOURCE_STREAM_TYPE_NOT_SUPPORTED) The video element has thrown a media error. – {code: 4, mediaError: "MEDIA_ERR_SRC_NOT_SUPPORTED", message: "Key not available"}_

----

I realise this is an outdated version of wpewebkit so working on a fix for this is not really desired, but what would be useful to know is: **is this a known issue with wpe-2.22 that widevine license renewal doesn't work**, or is this issue only being seen by myself?
If widevine license renewal is actually working on wpe-2.22, if possible please share a demo with me to investigate.

Any insight here is appreciated,
Thanks.

**Comment by calvaris** [comment]
I don't know if we'll be able to work on this, but if I could I would do only if you can provide a use case in the shape of a simple HTML file.

**Comment by calvaris** [comment]
I got notice that we are not supporting 2.22 anymore. Should there be any urgency, please handle it through RDK and we can revisit this. Thanks!
