### ISSUE TITLE
WPE 2.38 - WPE WebKit for Mir Kiosk: Kiosk Segmentation fault on showing a HTML File Input dialog

### ISSUE THREAD

**Issue by ZmRZjFuDsDiR4qi5801F** [Metrological/WebKitForWayland#1282]
Hello, we're testing the "WPE WebKit for Mir Kiosk" snap and encountered an issue on clicking on a web site having a button which shows a file input dialog. This seems to be not supported by the used WPEWebKit browser running in Kiosk mode. Is there any option to prevent the browser from crashing? We would expect all IO  dialogs to be not shown, because of security reasons.
What is the default behavior of file input & file save dialogs here?

.../bin/launch-wpe: line 102: 109978 Segmentation fault      "$SNAP"/usr/bin/cog "${cog_params[@]}" "$url"

This is the JavaScript code trying to show the input element:

 executeUploadLicenseFile(): void {
     const e = document.getElementById('idFileInput');
     const event = new MouseEvent('click', { bubbles: false });
     e.dispatchEvent(event);
  }

**Comment by philn** [comment]
Are you sure you're using this downstream WPE fork? The upstream is hosted at wpewebkit.org (releases) and github.com/webkit/webkit (repo).

**Comment by ZmRZjFuDsDiR4qi5801F** [comment]
I think you're right.  Because I can't report any new issues to WebKit directly. So please could you tell me, how to report this and which related component could be responsible for: webkit, cog or libwpe? This would be very helpful. Thank you in advance.

**Comment by philn** [comment]
cog doesn't support file input popups, as explained in https://github.com/Igalia/cog/issues/578
