### ISSUE TITLE
WPE 2.38 - WPE WebKit for Mir Kiosk:  WARNING: trying to load platform resource 'textAreaResizeCorner'

### ISSUE THREAD

**Issue by ZmRZjFuDsDiR4qi5801F** [Metrological/WebKitForWayland#1283]
Hello, we're testing the "WPE WebKit for Mir Kiosk" snap and encountered an issue on showing some HTML containing a 'textAreaResizeCorner' element. The element appears, but it is read-only. Also a warning is shown in the logs:

WARNING: trying to load platform resource 'textAreaResizeCorner'

Is there some resource missing or is there any WPE Option to enable it?

**Comment by philn** [comment]
Are you sure you're using this downstream WPE fork? The upstream is hosted at wpewebkit.org (releases) and github.com/webkit/webkit (repo).

**Comment by ZmRZjFuDsDiR4qi5801F** [comment]
I think you're right.  Because I can't report any new issues to WebKit directly. So please could you tell me, how to report this and which related component could be responsible for: webkit, cog or libwpe? This would be very helpful. Thank you in advance.

**Comment by philn** [comment]
bugs.webkit.org WPEWebKit component
