### ISSUE TITLE
Build fails (cmake error) for platforms that do not provide gstreamer-gl libraries

### ISSUE THREAD

**Issue by robvogelaar** [Metrological/WebKitForWayland#13]
In Source/cmake/FindGStreamer.cmake there is a find_library(${_component_prefix}_LIBRARIES. If a platform does not provide gstreamer-gl libraries then GSTREAMER_GL_LIBRARIES will be set to GSTREAMER_GL_LIBRARIES-NOTFOUND and then in Source/WebCore/PlatformWPE.cmake the list(APPEND WebCore_LIBRARIES will append GSTREAMER_GL_LIBRARIES-NOTFOUND to the list of WebCore libraries, and this will not be found and there will be a cmake error.

**Comment by robvogelaar** [comment]
Also,

*Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:65:42: fatal error: gst/gl/egl/gsteglimagememory.h: No such file or directory*

**Comment by robvogelaar** [comment]
There are gst-gl references in MediaPlayerPrivateGStreamerBase.cpp and VideoSinkGStreamer.cpp. Minimally commenting these such that a ENABLE_VIDEO=ON, DENABLE_MEDIA_SOURCE=ON build can complete, in anticipation of USE_HOLE_PUNCH_GSTREAMER.

**Comment by philn** [comment]
you shouldn't use the webkit video sink if you enable hole punch

**Comment by robvogelaar** [comment]
How do I configure for that?

**Comment by philn** [comment]
ifdef it and change the ::createVideoSink() method to create whatever sink you need for hole punch

**Comment by robvogelaar** [comment]
Fixed!
