### ISSUE TITLE
[wpe-2.38.5][wpe-webkit-mir-kiosk]

### ISSUE THREAD

**Issue by tbanetwork** [Metrological/WebKitForWayland#1322]
Hi all!

I use ubuntu frame with wpe (through wpe-webkit-mir-kiosk) for … a kiosk :wink:

Unfortunately, in our Kiosk there are some Buttons where you need to confirm the action by “holding” the button for a couple of seconds.

E.g. you need to confirm that you want to shutdown the kiosk by holding “Hold to shutdown” for a certain time. On top of the dialog there is a progress bar (see screenshot; blue) and normally after hitting 100% it should shut down the kiosk. For some reason this never happens and the blue progress bar does not move at all.

![c54e60b615204f241080add6bd2f59943fdc0452_2_690x143](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/92360191/df536e25-3722-4776-ad9d-885fab35fd72)
(Screenshot taken remotely via PC, that’s why there is a mouse cursor)

Any Ideas?

Thanks a lot tbanetwork

P.S. Sysinfo:

Hardware: NVIDIA Orin NX (ARM64)
OS: NVIDIA Jetson Linux 35.4.1 (Ubuntu 20.04)

**Comment by philn** [comment]
Is this Cog?
I don't think mir-kiosk uses this WPE fork. Please report this in the Cog repo if you're using Cog.

**Comment by tbanetwork** [comment]
Thanks for the hint @philn. I opened up a issue in the cog repo.
