### ISSUE TITLE
[wpe-2.38] Spurious lines in zoomed content 

### ISSUE THREAD

**Issue by filipe-norte-red** [Metrological/WebKitForWayland#1324]
When applying a zoom factor to a page with images that form a gradient, spurious lines appear that are otherwise not present without the zoom factor. 

**Good case (zoom = 100%):**
![zoom-100percent-no-2-lines](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/89521141/ad0ab330-0410-43ed-a1fd-3df283c2197b)

**Bad case (zoom = 150%):**
![zoom-150percent-2-lines](https://github.com/WebPlatformForEmbedded/WPEWebKit/assets/89521141/1e8dd1e1-4481-4fe3-83d3-6e8f9a6d8070)

This can be reproduced with the attached test page: [test.zip](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/15075138/test.zip)

Steps:
- Load the page. No spurious lines should be observed
- In inspector console, run: document.body.style.zoom = "150%"

This was only tested on 2.38 so far.

Note: The position of the lines depends on the size of the blocks / images used to create the gradient effect. In this particular case there is an overlap between 2 blocks that leads to the existence of the 2 lines. Should the size of the blocks be adjusted the position of the lines would change.
The same test page renders ok on chrome on the pc.

**Comment by filipe-norte-red** [comment]
Hello @magomez 
Was wondering if you had the chance to have an initial look at this issue?
Thanks

**Comment by magomez** [comment]
@filipe-norte-red yes, I started to look into it. I know it happens because the divs in the example overlap a bit, and the lines are shown exactly at the border of the overlapping area. I discarded it's a composition issue. My bet is that there's a rounding problem somewhere when applying to zoom to the divs size, but I'm still looking into it.

**Comment by magomez** [comment]
@filipe-norte-red I've just pushed 7d2a4ff147c6862f1cb19d5860f5a1e9a87c8152 to the wpe-2.38 branch. That fixes the problem for me. Could you please verify that it works for you as well and close this? Thanks!

**Comment by filipe-norte-red** [comment]
@magomez , many thanks for the fix! I confirm it fixes the issue!
