### ISSUE TITLE
Backporting IndexDB apis to 2.38

### ISSUE THREAD

**Issue by modeveci** [Metrological/WebKitForWayland#1341]
We are going to use IndexDB settings for the first time and from 2.42 on it has been changed to:

"origin-storage-ratio"
"total-storage-ratio"

Could you please backport these changes to 2.38? Then we will be aligned with the coming versions.

**Comment by magomez** [comment]
@modeveci , origin-storage-ratio and total-storage-ratio are supposed to replace the methods to set the quotas that are used on 2.38. They are not meant to be used together with the old methods of 2.38.
There's even the possibility that, even if those properties are available on 2.42, they won't be used until way later, like 2.50, which is when it's planned to switch to the new API.

Also, origin-storage-ratio and total-storage-ratio handle all the local storage, not only IndexedDB. 

I strongly recommend to use the 2.38 way to do this on this version. We will tell you when it's the best moment to switch to the new method.

**Comment by modeveci** [comment]
Synched
