### ISSUE TITLE
100% cpu usage for simple transform animation

### ISSUE THREAD

**Issue by septatrix** [Metrological/WebKitForWayland#1348]
The page https://display.soundtrackyourbrand.com/ results in full load on the CPU. Blink and Gecko do not suffer from this problem. We currently have this page in an iframe in a kiosk solution and it makes the whole browser sluggish.

We tested this on the most recent Cog and Epiphany releases.

**Comment by philn** [comment]
Can you report this to https://bugs.webkit.org please?

This bug tracker is for a downstream fork of WPE. If the issue happens with Epiphany it's an upstream WebKit bug.

**Comment by septatrix** [comment]
Reported upstream as https://bugs.webkit.org/show_bug.cgi?id=276580
