### ISSUE TITLE
GstWebRTCICE was not declared in scope

### ISSUE THREAD

**Issue by ayu7377** [Metrological/WebKitForWayland#1353]
Hi, I'm first time building for  the WPE port, and all the dependencies (GStreamer) are installed, but still I'm getting GstWebRTCICE was not declared in scope in `GStreamerMediaEndpoint.cpp` file. Is there anything additional installation or any steps can I check?
While updating webkitwpe-libs, I got the message, `
Info: org.freedesktop.Platform.GL.default is end-of-life, with reason: org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Nothing to do.
SDK version: 254364.2@bst-21-08
`, can this be an issue?

**Comment by philn** [comment]
Are you using the upstream port (hosted on GH webkit/webkit) or this downstream version?
