### ISSUE TITLE
Hero images/Big Images are not rendered properly, and navigation is too smooth/fast when hold the navigation keys.

### ISSUE THREAD

**Issue by suresh-khurdiya-infosys** [Metrological/WebKitForWayland#1393]
Note:
1.This issue is observed in WPE 2.38 only and not in WPE 2.22.

App:  Fishing TV

2. Replication steps:
1.Launch Fishing TV app and sign in to app.
2.Perform left to right navigation and vice versa by holding the navigation keys in hero carousel (big images available carousel in Home page).
3.Perform top to bottom/left to right navigation by holding the navigation keys and vice versa in the app.
4.Observe the behavior.

Actual results:
Hero images are not rendered properly, and navigation is too smooth/fast when hold the navigation keys.

Expected results:
Images should render properly, and during fast navigation focus should be moving in each carousel.

attaching a video for a reference.

https://github.com/user-attachments/assets/4b499a21-33db-4560-b926-d5fc8d3a1341

**Comment by pgorszkowski-igalia** [comment]
@suresh-khurdiya-infosys : can you provide a link to Fishing TV app ?

**Comment by suresh-khurdiya-infosys** [comment]
> @suresh-khurdiya-infosys : can you provide a link to Fishing TV app ?

https://widgets.metrological.com/lightning/liberty/2e3c4fc22f0d35e3eb7fdb47eb7d4658#app:com.EOS.app.FishingTV

**Comment by pgorszkowski-igalia** [comment]
I cannot signin to TV app. I created an account on fishingtv.com, I am able to login there on my PC, but after entering the code on PC nothing changes on device. I use RPi3B+ with wpe 2.38 for that. Do I need to use some specific UA? Can you check that you can signin to TV app with RPi?

**Comment by suresh-khurdiya-infosys** [comment]
I don'thtink so any login is required after entering the code if we select to Home button it will work other wise,
On page if you can see  the preview button then just select the Preview and next screen we can see the thumbnails and content.
Please see below screenshot of those screen.
![Screenshot from 2024-08-29 08-55-33](https://github.com/user-attachments/assets/04a618c2-55fc-46a0-9520-d0d997d55f72)
![Screenshot from 2024-08-29 08-55-18](https://github.com/user-attachments/assets/4d3f18ac-8bbb-4028-9f65-e622b718901b)
![Screenshot from 2024-08-29 08-54-55](https://github.com/user-attachments/assets/4fdb3f17-f7ed-4f76-ba68-a2bbf445ad0b)

On Chrome Browser also, I can see this issue while pressing Right key for big poster navigation.
I did not try on RPI,  I will check it.

**Comment by pgorszkowski-igalia** [comment]
The problem is also observed on FireFox, so maybe it is how the app works in case of long press of navigation keys.

**Comment by pgorszkowski-igalia** [comment]
Can you provide recording how it works on your box and WPE 2.22?

**Comment by suresh-khurdiya-infosys** [comment]
Video on RPI is attached and same behavior can be see on WPE 2.22.
On RPI also, first time we can see an issue but after that no issue(May be caching something which is not happening with WPE 2.38.

**Comment by suresh-khurdiya-infosys** [comment]
-Chrome and other browser issue is there.
- RPI: Only first time navigation after that no issue.
- With WPE 2.22 on our Devices, Only first time navigation after that no issue.
- With WPE 2.38 on our devices, Every time we can see an issue.

**Comment by pgorszkowski-igalia** [comment]
@suresh-khurdiya-infosys : can you provide me the logs from your device in problematic case with WEBKIT_DEBUG=Editing?

**Comment by suresh-khurdiya-infosys** [comment]
Please check whether this logs are useful or not.

**Comment by pgorszkowski-igalia** [comment]
@suresh-khurdiya-infosys : can you do the same with your box with WPE 2.22? thanks

**Comment by suresh-khurdiya-infosys** [comment]
Video on WPE 2.22

https://github.com/user-attachments/assets/8cff7b92-3bfd-49ec-b80e-0dcaa185d0af

**Comment by suresh-khurdiya-infosys** [comment]
BTW, which logs are useful for this issue?

**Comment by pgorszkowski-igalia** [comment]
I am investigating how many and how often keyEvents are generated when the button/key is pressed and not released: "keyIdentifier|WebAppKeyHandler -> KeyPress"

**Comment by pgorszkowski-igalia** [comment]
BTW.: with WPE 2.38 on RPi 3B+ I don't see the problem, I mean it behaves in the same way as on WPE 2.22

Do you know what is the key repeat rate on your box with wpe 2.22 and wpe 2.38? I suspect that in case wpe 2.22 is higher then in case of wpe 2.38 that is why you observe the problem on wpe 2.38

It can be also "fixed" on desktop (FF, chrome, Epiphany/WebKitGTK/WPEWebKit) by increase the key repeat rate.
In case of Ubuntu(23.10) with wayland you can check the key repeat rate:
`gsettings get org.gnome.desktop.peripherals.keyboard repeat-interval` (in my case default value was 30ms), if I change that to 100ms the behaviour on that FishingTV app was the same as in case wpe 2.22.
`gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 100`

Remember that it is a global setting for GDK so other apps also will be affected by that - so do this only for testing.

Conclusion: if you have the same key-repeating rate on 2.22 and 2.38 you should have the same behaviour

**Comment by pgorszkowski-igalia** [comment]
@suresh-khurdiya-infosys : did you find the key repeat rate? Does it solve the problem?

**Comment by suresh-khurdiya-infosys** [comment]
Yes, actually I found some extra patch is applied on WPE 2.22 for rate point of view and so I have done the similar rate change for WPE 2.38 and issue is fixed. Actually I was waiting for internal review to complete before reply here(that's why did not replied).
Just now review is done. We are good to go with that rate change in wpe-backend-rdk side.
So, we can close this ticket for a now.
