### ISSUE TITLE
Thread leak during clean up

### ISSUE THREAD

**Issue by aazamansari** [Metrological/WebKitForWayland#165]
We have browser working as service in our system. We are using westeros backend.
We create WKContext, WKView runtime as request to load page comes.
Once request is done we delete the WKContext and WKView and release the resources.

What we observe is that there is thread leak happening for "ReceiveQueue" threads.
These ReceiveQueue threads are created by IPC::Connection through WorkQueue.

Source/WebKit2/Platform/IPC/Connection.cpp
When releasing the resources, the 2 ReceiveQueue threads are going in deadlock state.

WorkQueue destructor ~WorkQueue() is getting called in the same thread.
It is calling WorkQueue::platformInvalidate() which calls wait as below.
m_terminateRunLoopCondition.wait(m_terminateRunLoopConditionMutex);

This condition is notified by the same thread and hence the thread goes in deadlock state.

Below link provides the backtrace of the stack that we see for the deadlocked threads.
Out of these top 6 threads have leaked.
https://gist.github.com/aazamansari/40494a4036aeebfacd0c25a106b22229

Below is an example code of how we load the page and then cleanup the resources.
https://gist.github.com/aazamansari/f64b3d8db8f89c51097c83899961a36b

**Comment by vivekarumugam** [comment]
@zdobersek, Can we pull this change made on https://bugs.webkit.org/show_bug.cgi?id=166645 to our master?

**Comment by zdobersek** [comment]
Done:
- on master https://github.com/Metrological/WebKitForWayland/commit/9d4d2cde69ae2f328b1ba15aba8775520cf6f70d
- on wpe-staging https://github.com/Metrological/WebKitForWayland/commit/e05d42e8536499fc7060c3b8c21b57a0ec4edee5
