### ISSUE TITLE
smashcat canvas test doesn't work on PI2 (Yocto image)

### ISSUE THREAD

**Issue by emutavchi** [Metrological/WebKitForWayland#168]
We see a black screen after starting WPELauncher:

    export XDG_RUNTIME_DIR=/tmp
    export WAYLAND_DISPLAY=main0

    westeros --renderer libwesteros_render_dispmanx.so.0.0.0 --framerate 60 --display ${WAYLAND_DISPLAY} --enableCursor &

    WPELauncher http://www.smashcat.org/av/canvas_test/

Instructions on how to build image: https://github.com/Comcast/rdk-on-raspberrypi

P.S.:
Expected to see about 20-22 FPS reported by smashcat test. Bigger numbers would indicate another ISSUE with rendering!!!

**Comment by emutavchi** [comment]
Quick update:

 - this test works on buildroot image, which uses WPE from Sep 22 (622e996fc528212bd0453a076571261d28328d34)
 - in Yocto we use recent master (01489c1792f7bcc2802ad72da8b5cf44c49cde8e, Dec 1) - test doesn't work
 - WPE from sep 22 also works in Yocto, FPS is ~30-31

**Comment by zdobersek** [comment]
This works on RPi with WPE after the latest merge, along with the equally recent buildroot-wpe:
https://github.com/Metrological/WebKitForWayland/commit/d0064885d020e0e74398206e552235b214d7210c

The bcm-rpi backend was used, meaning the issue is either in the Yocto build configuration or Westeros.

**Comment by emutavchi** [comment]
Hi Žan, how may FPS it shows for you on recent buildroot-wpe?

**Comment by zdobersek** [comment]
FWIW, bcm-rpi was giving me ~66FPS reported by the test, and ~55FPS reported by dispmanx.

With Westeros, it's giving me ~56FPS reported by the test, but I don't have any FPS count report from Westeros.

**Comment by karora123** [comment]
Hi, seems like "http://www.smashcat.org/av/canvas_test/" is not available (404 not found)
Is there any other link/utility to calculate FPS for WPELauncher?

**Comment by wouterlucas** [comment]
You can use any animation, WebGL, CSS3 or Canvas. E.g. http://helloracer.com/webgl/ will render the WebGL F1 race car instead. I don't know what happened to smash cat, if someone has the sources we should put it back online somewhere.

**Comment by karora123** [comment]
Hi Wouter, how r u buddy !! well, thanks for quick update !! I been through this link on Chrome & IE, found slight difference while rendering animation. But i could not see FPS marking anywhere on the screen for bench mark. Is the animation working fine is significant to desired FPS ?

**Comment by wouterlucas** [comment]
Doing well thanks! How about you?
Oh right yeah that one does not have a on screen FPS counter, you can only see it in e.g. as explained here https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/412 with the SHOW_FPS export.

If its purely canvas and a on screen FPS counter you may want to look at http://themaninblue.com/experiment/AnimationBenchmark/canvas/

Other things you can try are:
CSS3:
http://webkit.org/blog-files/3d-transforms/poster-circle.html
http://www.webkit.org/blog-files/3d-transforms/morphing-cubes.html
https://webkit.org/blog-files/leaves/

Canvas:
http://ie.microsoft.com/testdrive/performance/fishietank/

WebGL:
http://oos.moxiecode.com/js_webgl/particles_morph/
http://helloracer.com/webgl/
http://alteredqualia.com/three/examples/webgl_pasta.html
http://helloracer.com/racer-s/


And there probably others out there that I dont know off :)

**Comment by karora123** [comment]
Hi, 

Using link below, I could see only around 10 FPS on RPI. using option below to launch WPE Browser.
export XDG_RUNTIME_DIR=/run/user/0/
export WAYLAND_DISPLAY=WPE
/usr/bin/westeros --renderer /usr/lib/libwesteros_render_dispmanx.so.0 --enableCursor --framerate 60 --display WPE &

WPELauncher https://testdrive-archive.azurewebsites.net/performance/fishietank/
Observed 10 FPS for above link.
Any idea or option I forget to enable?

**Comment by wouterlucas** [comment]
Yeah fishie tank is pretty heavy, 10-15 FPS on an RPI2 is about right.
