### ISSUE TITLE
How to make PLAY multimedia key to work on the remote (XKB)

### ISSUE THREAD

**Issue by vertexodessa** [Metrological/WebKitForWayland#184]
windows_key_code_for_key_event has no way to return VK_PLAY which is required for Youtube to react on the PLAY button
https://github.com/Metrological/WebKitForWayland/blame/master/Source/ThirdParty/WPE-platform/src/input/XKB/input-libxkbcommon.cpp#L618

VK_HAVI_PLAY is not working with Youtube
Please provide a key binding to return VK_PLAY
Preferrably XKB_KEY_3270_Play and XKB_KEY_XF86AudioPlay should be converted to VK_PLAY Windows binding.
Thank you

**Comment by blino** [comment]
Right, YouTube would not work with the current key mapping, I have only actually tried the PlayPause key in my tests.

VK_PLAY (0xFA = 250) would work for YouTube, see code below, we can map this value for XKB_KEY_XF86AudioPlay.

Though, changing the previous value could break applications relying on either HAVi / DASE / OCAP / CE-HTML / HbbTV. Not sure if somebody would have a use for this, YouTube is without a double a stronger use-case anyway.

See https://www.youtube.com/s/tv/html5/fdf8825b/app-prod.js (can be pretty-printed in Web Inspector for a formatted version):
    d.r6 = function(a) {
        switch (a.keyCode) {
        case 40:
            this.Pd(this.g, !1, !1, "arrow_down");
            L(a);
            break;
        case 13:
            this.Pd(this.g, !1, !0, "enter");
            L(a);
            break;
        case 75:
        case 250:
        case 179:
        case 32:
            this.Pd(this.g, !1, !1, "play_pause");
            break;
        case 27:
        case 8:
            this.Pd(void 0, !1, !1, "escape")
        }
    }

**Comment by vertexodessa** [comment]
hi Olivier, thank you for the fast response; so you think it should be fine to change XKB_KEY_XF86AudioPlay binding to VK_PLAY from VK_HAVI_PLAY? That would solve the issue for us. I can create a pull request if you confirm.

**Comment by blino** [comment]
Yes, I think we can do this change.
And also remove the VK_HAVI_PLAY define from TvKeyboardCodes.h

**Comment by vertexodessa** [comment]
please review https://github.com/Metrological/WebKitForWayland/pull/187

**Comment by wouterlucas** [comment]
Closing as #187 is merged into master.

**Comment by karora123** [comment]
One small question in same context...why the XKB Key names having 'audio' only instead A/V both. Just like XKB_KEY_XF86AudioForward, XKB_KEY_XF86AudioRecord, XKB_KEY_XF86AudioPlay etc. Even impact observed for both A/V. The name should guide for either both A/V or none as its a bit confusing.
