### ISSUE TITLE
Playready failed in decryption with error in MSE state transition and mapping buffer

### ISSUE THREAD

**Issue by tigereyenj** [Metrological/WebKitForWayland#200]
Just did a testing with  rdk-webrtc-dec12 with PR content. There are decryption errors with invalid MSE state transition and mapping buffer.

Logs with GStreamer information attached. 
[pacexg1v3_wpe_dec_playready_004.log.zip](https://github.com/Metrological/WebKitForWayland/files/742329/pacexg1v3_wpe_dec_playready_004.log.zip)

**Comment by goruklu** [comment]
this seems to be caused by the gst_allocator_fast_malloc_mem_share() function using READ_ONLY flag. WebKitPlayReadyDecryptorGstreamer does in-place transform  when decrypting a buffer so the we need READ&WRITE buffers.

**Comment by zdobersek** [comment]
OK. We'll revert away from using gst_allocator_fast_malloc since it's a minefield. We should still be using FastMalloc for various memory allocations we do in WebKit that are then wrapped into GstBuffers (like the MSE buffers).

**Comment by goruklu** [comment]
@zdobersek you can try this page  http://52.8.38.95/bitdash-demo/playready.html for Playready DASH content playback. For us, WebKitPlayreadyDecryptorGstreamer was failing in this line:

[https://github.com/Metrological/WebKitForWayland/blob/rdk-webrtc-dec12/Source/WebCore/platform/graphics/gstreamer/WebKitPlayReadyDecryptorGStreamer.cpp#L146](url)

`bufferMapped = gst_buffer_map(buffer, &map, static_cast<GstMapFlags>(GST_MAP_READWRITE));
    if (!bufferMapped) {
        gst_buffer_unmap(ivBuffer, &ivMap);
        GST_ERROR_OBJECT(self, "Failed to map buffer");
        return false;
    }`


removing the GST_MINI_OBJECT_FLAG_LOCK_READONLY flag in the following line fixed the issue for us but we are not sure whether that will have any unforeseen side effects:
[https://github.com/Metrological/WebKitForWayland/blob/rdk-webrtc-dec12/Source/WebCore/platform/graphics/gstreamer/GstAllocatorFastMalloc.cpp#L114](url)
`gst_memory_init(GST_MEMORY_CAST(sharedMem),
        static_cast<GstMemoryFlags>(GST_MINI_OBJECT_FLAGS(parent) | GST_MINI_OBJECT_FLAG_LOCK_READONLY),
        mem->base.allocator, parent, mem->base.maxsize, mem->base.align,
        mem->base.offset + offset, size);`

**Comment by zdobersek** [comment]
Removed GstAllocatorFastMalloc in https://github.com/Metrological/WebKitForWayland/commit/f9d534516afa4a82fd69ce4e408bbae81e196565.
