### ISSUE TITLE
.mp3 files not loading or playing

### ISSUE THREAD

**Issue by foleman** [Metrological/WebKitForWayland#227]
I found that .mp3 files do not load metadata, nor the audio file itself when using wpe. I tried from the own filesystem in a server and from different html5 pages(w3school) and it won't load. It renders a player but it remains loading(I tried 1 hour) and if you hit play it won't play the track. In the inspector I'm not getting any error neither. And how could I get .wav codecs?
I'm using rpi2.

**Comment by srinivas-kakarla** [comment]
It seems your Gstreamer is missing a plug-in. Most probably id3demux. Please enable Gstreamer logs on RPi and provide the output.

**Comment by foleman** [comment]
Yes, you were right. I didn't have id3mux enabled in buildroot config! 
Here is the output:

```
# gst-launch-1.0 playbin uri=file:///root/web2py/applications/audi/static/USB/Va
to_Gonzalez__Mucky/UnknownAlbum/Vato_Gonzalez__Mucky_-_Violet_Nights.mp3
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Missing element: ID3 tag demuxer
WARNING: from element /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: No decoder available for type 'application/x-id3'.
Additional debug info:
gsturidecodebin.c(938): unknown_type_cb (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0
ERROR: from element /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: Your GStreamer installation is missing a plug-in.
Additional debug info:
gsturidecodebin.c(1005): no_more_pads_full (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0:
no suitable plugins found:
gstdecodebin2.c(4592): gst_decode_bin_expose (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0:
no suitable plugins found:
Missing decoder: ID3 tag (application/x-id3)

ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
```
The only thing is I select id3demux in the nconfig and re-compile, but it won't load into te rootfs.tar! Do I need to add other package(s)? Or maybe must I make a full re-compile from scratch?
By the way I'm using buildroot-wpe.

**Comment by ghost** [comment]
Hi srinivas ,
can you please let me know how to enable text/html decoder 
Below is the error i am getting 

root@raspberrypi-rdk-mc:~# gst-launch-1.0 playbin uri=http://35.198.234.156:9003/vr/
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Missing element: text/html decoder
WARNING: from element /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: No decoder available for type 'text/html'.
Additional debug info:
../../../gst-plugins-base-1.10.4/gst/playback/gsturidecodebin.c(938): unknown_type_cb (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0
ERROR: from element /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0: Your GStreamer installation is missing a plug-in.
Additional debug info:
../../../gst-plugins-base-1.10.4/gst/playback/gsturidecodebin.c(1005): no_more_pads_full (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0:
no suitable plugins found:
../../../gst-plugins-base-1.10.4/gst/playback/gstdecodebin2.c(4592): gst_decode_bin_expose (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0:
no suitable plugins found:
Missing decoder: text/html (text/html)

ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...
