### ISSUE TITLE
buildroot: rpi-firmware.mk, unclear device selection in S30mountroot

### ISSUE THREAD

**Issue by hlev** [Metrological/WebKitForWayland#556]
I was building an image from a recent `WebPlatformForEmbedded/buildroot:master` and were wondering about a change in `rpi-firmware.mk` that results in a wrong init script.

Checking for the `ifeq ($(BR2_PACKAGE_HOST_LINUX_HEADERS_CUSTOM_4_9),y)` will return false if there is a custom toolchain, and will put a wrong `S30mountroot` init script in the build for an RPI3.

It's clear that the fist condition should evaluate `BR2_TOOLCHAIN_EXTERNAL_HEADERS_4_9`  as well, or even `BR2_TOOLCHAIN_HEADERS_AT_LEAST="4.9"` to yield correct result. It's an easy fix.

However, I don't know which RPI device enumerates the SD card at `/dev/mmcblk1` and would like to understand why these conditions were introduced, how the seemingly unrelated value of kernel version comes into play here? Could someone explain what the intention behind this change was, please? Thanks.

```
ifeq ($(BR2_TARGET_ROOTFS_CPIO),y)
ifeq ($(BR2_PACKAGE_HOST_LINUX_HEADERS_CUSTOM_4_9),y)
define RPI_FIRMWARE_MOUNT_ROOT
        mkdir -p $(TARGET_DIR)/root
        grep -q '^/dev/mmcblk0p2' $(TARGET_DIR)/etc/fstab || \
                echo -e '/dev/mmcblk0p2 /root ext4 defaults 0 0' >> $(TARGET_DIR)/etc/fstab
        $(INSTALL) -m 0755 -D package/rpi-firmware/S30mountroot-0 \
                $(TARGET_DIR)/etc/init.d/S30mountroot
endef
else
define RPI_FIRMWARE_MOUNT_ROOT
        mkdir -p $(TARGET_DIR)/root
        grep -q '^/dev/mmcblk1p2' $(TARGET_DIR)/etc/fstab || \
                echo -e '/dev/mmcblk1p2 /root ext4 defaults 0 0' >> $(TARGET_DIR)/etc/fstab
        $(INSTALL) -m 0755 -D package/rpi-firmware/S30mountroot-1 \
                $(TARGET_DIR)/etc/init.d/S30mountroot
endef
endif
endif

```

**Comment by albertd** [comment]
From 4.9 kernel the block devices have been moved, so that's why we have to types of mount scripts. Fix has been applied so external toolchains will also work, thanks for reporting the issue.
