### ISSUE TITLE
make buildroot-milestone_rc1.8.tar for raspberry pi 3 fail ?

### ISSUE THREAD

**Issue by tfa2012** [Metrological/WebKitForWayland#558]
I start compiling WPE days ago, I'm very intrested in this project, that's so cool to run html5 app on a embeded device while using browser as its UI.
Here is my enviroment:
raspberry3b+, Ubuntu 16.06 LTS(run in VMPlayer)
I downloaded Milestone Release Candidate 1.8.tar.gz and uncompressed it to my working folder, and then compile(cp a new rpi3 wpe_defconfig for feature modify):
```
$cp configs/raspberry3_wpe_defconfig configs/raspberry3_tfwpe_defconfig
$make raspberry3_tfwpe_defconfig
$make
```
Waiting a very long time for downloading and compiling, unfortunely, it failed!! 
1. Was I chosed right source tar ball(Milestone Release Candidate 1.8.tar.gz at https://github.com/WebPlatformForEmbedded/buildroot/archive/milestone_rc1.8.tar.gz)?
2. Why it didn't work?

Can you help me? Thanks a lot!

============
here is log:

> [3620/4514] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/mse/MediaSourceClientGStreamerMSE.cpp.o
> [3621/4514] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/mse/MediaSourceGStreamer.cpp.o
> [3622/4514] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp.o
> FAILED: Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp.o 
> /home/merlin/project/tfwpe-br-mlst-rc1d8/output/host/usr/bin/arm-buildroot-linux-gnueabihf-g++  --sysroot=/home/merlin/project/tfwpe-br-mlst-rc1d8/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot  -DBUILDING_WITH_CMAKE=1 -DBUILDING_WPE__=1 -DBUILDING_WebCore -DDATA_DIR=\"share\" -DGETTEXT_PACKAGE=\"WPE\" -DHAVE_CONFIG_H=1 -DMETROLOGICAL=1 -DSTATICALLY_LINKED_WITH_PAL=1 -DUSER_AGENT_MAJOR_VERSION=\"601\" -DUSER_AGENT_MINOR_VERSION=\"1\" -isystem /home/merlin/project/tfwpe-br-mlst-rc1d8/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/libxml2 -isystem /home/merlin/project/tfwpe-br-mlst-rc1d8/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/gstreamer-1.0 -isystem /home/merlin/project/tfwpe-br-mlst-rc1d8/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/glib-2.0 -isystem /home/merlin/project/tfwpe-br-mlst-rc1d8/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/glib-2.0/include -isystem /home/merlin/project/tfwpe-br-mlst-rc1d8/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/gstreamer-1.0/include -I. -I../Source/WebCore -I../Source/WebCore/Modules/airplay -I../Source/WebCore/Modules/beacon -I../Source/WebCore/Modules/applepay -I../Source/WebCore/Modules/cache -I../Source/WebCore/Modules/credentials -I../Source/WebCore/Modules/debughelper -I../Source/WebCore/Modules/encryptedmedia -I../Source/WebCore/Modules/encryptedmedia/legacy -I../Source/WebCore/Modules/entriesapi -I../Source/WebCore/Modules/fetch -I../Source/WebCore/Modules/geolocation -I../Source/WebCore/Modules/indexeddb -I../Source/WebCore/Modules/indexeddb/client -I../Source/WebCore/Modules/indexeddb/server -I../Source/WebCore/Modules/indexeddb/shared -I../Source/WebCore/Modules/mediacontrols -I../Source/WebCore/Modules/mediasession -I../Source/WebCore/Modules/mediasource -I../Source/WebCore/Modules/mediastream -I../Source/WebCore/Modules/navigatorcontentutils -I../Source/WebCore/Modules/notifications -I../Source/WebCore/Modules/paymentrequest -I../Source/WebCore/Modules/plugins -I../Source/WebCore/Modules/quota -I../Source/WebCore/Modules/speech -I../Source/WebCore/Modules/streams -I../Source/WebCore/Modules/webaudio -I../Source/WebCore/Modules/webdatabase -I../Source/WebCore/Modules/webdriver -I../Source/WebCore/Modules/websockets -I../Source/WebCore/Modules/webvr -I../Source/WebCore/accessibility -I../Source/WebCore/animation -I../Source/WebCore/bindings -I../Source/WebCore/bindings/js -I../Source/WebCore/bridge -I../Source/WebCore/bridge/c -I../Source/WebCore/bridge/jsc -I../Source/WebCore/contentextensions -I../Source/WebCore/crypto -I../Source/WebCore/crypto/algorithms -I../Source/WebCore/crypto/keys -I../Source/WebCore/crypto/parameters -I../Source/WebCore/css -I../Source/WebCore/css/parser -I../Source/WebCore/cssjit -I../Source/WebCore/dom -I../Source/WebCore/dom/default -I../Source/WebCore/domjit -I../Source/WebCore/editing -I../Source/WebCore/fileapi -I../Source/WebCore/history -I../Source/WebCore/html -I../Source/WebCore/html/canvas -I../Source/WebCore/html/forms -I../Source/WebCore/html/parser -I../Source/WebCore/html/shadow -I../Source/WebCore/html/track -I../Source/WebCore/inspector -I../Source/WebCore/loader -I../Source/WebCore/loader/appcache -I../Source/WebCore/loader/archive -I../Source/WebCore/loader/archive/mhtml -I../Source/WebCore/loader/cache -I../Source/WebCore/loader/icon -I../Source/WebCore/mathml -I../Source/WebCore/page -I../Source/WebCore/page/animation -I../Source/WebCore/page/csp -I../Source/WebCore/page/scrolling -I../Source/WebCore/platform -I../Source/WebCore/platform/animation -I../Source/WebCore/platform/audio -I../Source/WebCore/platform/crypto -I../Source/WebCore/platform/encryptedmedia -I../Source/WebCore/platform/gamepad -I../Source/WebCore/platform/graphics -I../Source/WebCore/platform/graphics/cpu/arm -I../Source/WebCore/platform/graphics/cpu/arm/filters -I../Source/WebCore/platform/graphics/displaylists -I../Source/WebCore/platform/graphics/filters -I../Source/WebCore/platform/graphics/harfbuzz -I../Source/WebCore/platform/graphics/harfbuzz/ng -I../Source/WebCore/platform/graphics/opentype -I../Source/WebCore/platform/graphics/transforms -I../Source/WebCore/platform/mediastream -I../Source/WebCore/platform/mediastream/libwebrtc -I../Source/WebCore/platform/mock -I../Source/WebCore/platform/mock/mediasource -I../Source/WebCore/platform/network -I../Source/WebCore/platform/sql -I../Source/WebCore/platform/text -I../Source/WebCore/platform/text/icu -I../Source/WebCore/plugins -I../Source/WebCore/rendering -I../Source/WebCore/rendering/line -I../Source/WebCore/rendering/mathml -I../Source/WebCore/rendering/shapes -I../Source/WebCore/rendering/style -I../Source/WebCore/rendering/svg -I../Source/WebCore/replay -I../Source/WebCore/storage -I../Source/WebCore/style -I../Source/WebCore/svg -I../Source/WebCore/svg/animation -I../Source/WebCore/svg/graphics -I../Source/WebCore/svg/graphics/filters -I../Source/WebCore/svg/properties -I../Source/WebCore/websockets -I../Source/WebCore/workers -I../Source/WebCore/workers/service -I../Source/WebCore/workers/service/server -I../Source/WebCore/xml -I../Source/WebCore/xml/parser -IDerivedSources/WebCore -I../Source/WebCore/PAL -I../Source -I../Source/WebCore/Modules/gamepad -IDerivedSources/ForwardingHeaders/ANGLE -I../Source/WebCore/platform/graphics/gpu -I../Source/ThirdParty/xdgmime/src -I/home/merlin/project/tfwpe-br-mlst-rc1d8/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/cairo -I../Source/WebCore/platform/graphics/cairo -I/home/merlin/project/tfwpe-br-mlst-rc1d8/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/freetype2/freetype -I/home/merlin/project/tfwpe-br-mlst-rc1d8/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/freetype2 -I/home/merlin/project/tfwpe-br-mlst-rc1d8/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/harfbuzz -I../Source/WebCore/platform/graphics/freetype -I../Source/WebCore/platform/mediastream/openwebrtc -I../Source/WebCore/platform/graphics/gstreamer -I../Source/WebCore/platform/graphics/gstreamer/mse -I../Source/WebCore/platform/graphics/gstreamer/eme -I../Source/WebCore/platform/audio/gstreamer -I../Source/WebCore/platform/encryptedmedia/clearkey -I../Source/WebCore/platform/image-decoders -I../Source/WebCore/platform/image-decoders/bmp -I../Source/WebCore/platform/image-decoders/gif -I../Source/WebCore/platform/image-decoders/ico -I../Source/WebCore/platform/image-decoders/jpeg -I../Source/WebCore/platform/image-decoders/png -I../Source/WebCore/platform/image-decoders/webp -I../Source/WebCore/platform/graphics/texmap -I../Source/WebCore/page/scrolling/coordinatedgraphics -I../Source/WebCore/platform/graphics/texmap/coordinated -IDerivedSources/JavaScriptCore -IDerivedSources/JavaScriptCore/inspector -I../Source/JavaScriptCore -I../Source/JavaScriptCore/ForwardingHeaders -I../Source/JavaScriptCore/API -I../Source/JavaScriptCore/assembler -I../Source/JavaScriptCore/bytecode -I../Source/JavaScriptCore/bytecompiler -I../Source/JavaScriptCore/dfg -I../Source/JavaScriptCore/disassembler -I../Source/JavaScriptCore/domjit -I../Source/JavaScriptCore/heap -I../Source/JavaScriptCore/debugger -I../Source/JavaScriptCore/interpreter -I../Source/JavaScriptCore/jit -I../Source/JavaScriptCore/llint -I../Source/JavaScriptCore/parser -I../Source/JavaScriptCore/profiler -I../Source/JavaScriptCore/runtime -I../Source/JavaScriptCore/yarr -I../Source/ThirdParty/ANGLE -I../Source/ThirdParty/ANGLE/include/KHR -I../Source/WebCore/platform/graphics/egl -I../Source/WebCore/platform/graphics/epoxy -I../Source/WebCore/platform/graphics/glx -I../Source/WebCore/platform/graphics/opengl -I../Source/WebCore/platform/graphics/wpe -I../Source/WebCore/platform/graphics/wayland -I../Source/WebCore/platform/network/soup -I../Source/WTF -I/home/merlin/project/tfwpe-br-mlst-rc1d8/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/gio-unix-2.0 -I/home/merlin/project/tfwpe-br-mlst-rc1d8/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/libsoup-2.4 -I../Source/JavaScriptCore/.. -I../Source/JavaScriptCore/b3 -I../Source/JavaScriptCore/b3/air -I../Source/JavaScriptCore/bindings -I../Source/JavaScriptCore/builtins -I../Source/JavaScriptCore/disassembler/udis86 -I../Source/JavaScriptCore/disassembler/ARM64 -I../Source/JavaScriptCore/ftl -I../Source/JavaScriptCore/inspector -I../Source/JavaScriptCore/inspector/agents -I../Source/JavaScriptCore/inspector/augmentable -I../Source/JavaScriptCore/inspector/remote -I../Source/JavaScriptCore/tools -I../Source/JavaScriptCore/wasm -I../Source/JavaScriptCore/wasm/js -IDerivedSources/ForwardingHeaders -I../Source/bmalloc -IDerivedSources -I../Source/ThirdParty -fdiagnostics-color=always -Wno-maybe-uninitialized -Wwrite-strings -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wextra -Wall -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -fno-strict-aliasing -fno-exceptions -std=c++14 -fno-rtti  -O2 -DNDEBUG -Wno-cast-align -fvisibility=hidden -fvisibility-inlines-hidden -finline-limit=90 -fsection-anchors -ffunction-sections -fdata-sections -fno-rtti -fPIC -MD -MT Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp.o -MF Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp.o.d -o Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp.o -c /home/merlin/project/tfwpe-br-mlst-rc1d8/output/build/wpewebkit-28a74d98c18cce2062939c9fc8f5b61bc9f2b486/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp
> In file included from ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:136:0:
> ../../../host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/cairo/cairo-gl.h:65:5: warning: "CAIRO_HAS_GL_SURFACE" is not defined [-Wundef]
>  #if CAIRO_HAS_GL_SURFACE || CAIRO_HAS_GLESV2_SURFACE
>      ^
> ../../../host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/cairo/cairo-gl.h:95:5: warning: "CAIRO_HAS_GLX_FUNCTIONS" is not defined [-Wundef]
>  #if CAIRO_HAS_GLX_FUNCTIONS
>      ^
> ../../../host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/cairo/cairo-gl.h:113:5: warning: "CAIRO_HAS_WGL_FUNCTIONS" is not defined [-Wundef]
>  #if CAIRO_HAS_WGL_FUNCTIONS
>      ^
> ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:1334:80: error: ‘InitData’ has not been declared
>  void MediaPlayerPrivateGStreamerBase::handleInitData(unsigned int gstEventSeq, InitData& concatenatedInitDataChunks)
>                                                                                 ^
> ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:1334:116: error: no ‘void WebCore::MediaPlayerPrivateGStreamerBase::handleInitData(unsigned int, int&)’ member function declared in class ‘WebCore::MediaPlayerPrivateGStreamerBase’
>  void MediaPlayerPrivateGStreamerBase::handleInitData(unsigned int gstEventSeq, InitData& concatenatedInitDataChunks)
>                                                                                                                     ^
> ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp: In member function ‘void WebCore::MediaPlayerPrivateGStreamerBase::handleProtectionEvent(GstEvent*)’:
> ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:1370:5: error: ‘InitData’ was not declared in this scope
>      InitData concatenatedInitDataChunks;
>      ^
> ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:1382:5: error: ‘concatenatedInitDataChunks’ was not declared in this scope
>      concatenatedInitDataChunks.append(mapInfo.data, mapInfo.size);
>      ^
> ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:1385:24: error: ‘m_initSessionCache’ was not declared in this scope
>      auto sessionPair = m_initSessionCache.find(concatenatedInitDataChunks);
>                         ^
> ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:1391:82: error: ‘dispatchDecryptionSession’ was not declared in this scope
>              dispatchDecryptionSession(sessionPair.get()->value.second,gstEventSeq);
>                                                                                   ^
> ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:1395:49: error: ‘CDMInstanceOpenCDM’ was not declared in this scope
>              auto& cdmInstanceOpenCDM = downcast<CDMInstanceOpenCDM>(*this->m_cdmInstance);
>                                                  ^
> ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:1395:89: error: no matching function for call to ‘downcast(const WebCore::CDMInstance&)’
>              auto& cdmInstanceOpenCDM = downcast<CDMInstanceOpenCDM>(*this->m_cdmInstance);
>                                                                                          ^
> In file included from ../Source/WTF/wtf/Ref.h:32:0,
>                  from ../Source/WTF/wtf/RefPtr.h:29,
>                  from ../Source/WTF/wtf/HashFunctions.h:26,
>                  from ../Source/WTF/wtf/HashTraits.h:26,
>                  from ../Source/WTF/wtf/glib/GRefPtr.h:28,
>                  from ../Source/WebCore/platform/graphics/gstreamer/GRefPtrGStreamer.h:24,
>                  from ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.h:28,
>                  from ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:26:
> ../Source/WTF/wtf/TypeCasts.h:85:56: note: candidate: template<class Target, class Source> typename WTF::match_constness<Source, Target>::type* WTF::downcast(Source*)
>  inline typename match_constness<Source, Target>::type* downcast(Source* source)
>                                                         ^
> ../Source/WTF/wtf/TypeCasts.h:85:56: note:   template argument deduction/substitution failed:
> ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:1395:89: error: template argument 1 is invalid
>              auto& cdmInstanceOpenCDM = downcast<CDMInstanceOpenCDM>(*this->m_cdmInstance);
>                                                                                          ^
> In file included from ../Source/WTF/wtf/Ref.h:32:0,
>                  from ../Source/WTF/wtf/RefPtr.h:29,
>                  from ../Source/WTF/wtf/HashFunctions.h:26,
>                  from ../Source/WTF/wtf/HashTraits.h:26,
>                  from ../Source/WTF/wtf/glib/GRefPtr.h:28,
>                  from ../Source/WebCore/platform/graphics/gstreamer/GRefPtrGStreamer.h:24,
>                  from ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.h:28,
>                  from ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:26:
> ../Source/WTF/wtf/TypeCasts.h:77:56: note: candidate: template<class Target, class Source> typename WTF::match_constness<Source, Target>::type& WTF::downcast(Source&)
>  inline typename match_constness<Source, Target>::type& downcast(Source& source)
>                                                         ^
> ../Source/WTF/wtf/TypeCasts.h:77:56: note:   template argument deduction/substitution failed:
> ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:1395:89: error: template argument 1 is invalid
>              auto& cdmInstanceOpenCDM = downcast<CDMInstanceOpenCDM>(*this->m_cdmInstance);
>                                                                                          ^
> ../Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamerBase.cpp:1408:59: error: ‘handleInitData’ was not declared in this scope
>      handleInitData(gstEventSeq, concatenatedInitDataChunks);
>                                                            ^
> [3623/4514] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/mse/PlaybackPipeline.cpp.o
> [3624/4514] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/platform/graphics/gstreamer/mse/SourceBufferPrivateGStreamer.cpp.o
> ninja: build stopped: subcommand failed.
> package/pkg-generic.mk:216: recipe for target '/home/merlin/project/tfwpe-br-mlst-rc1d8/output/build/wpewebkit-28a74d98c18cce2062939c9fc8f5b61bc9f2b486/.stamp_built' failed
> Makefile:79: recipe for target '_all' failed

**Comment by albertd** [comment]
@tfa2012 just do a git clone and instead of downloading the milestone.

**Comment by tfa2012** [comment]
@albertd thank you very much.
I will try it tonight.

**Comment by albertd** [comment]
You're welcome, please reopen if you still have issues
