### ISSUE TITLE
MemoryPressureHandler not reacting in some scenarios

### ISSUE THREAD

**Issue by lazarkovacevic7** [Metrological/WebKitForWayland#560]
Hi, We are using memory pressure handler with intention to limit memory WPE is using on our embedded platform (broadcom 7252). 

Following environment variables are exported when configuring it:
WPE_RAM_SIZE = "331m",
WPE_POLL_MAX_MEMORY = "WPEWebProcess:270m,WPENetworkProcess:40m"

We have a key called EPG which is supposed to open an EPG page. Repeated pressing on this key switches between EPG and starting page. The problem happens when we start pressing EPG button repeatedly, at a certain pace, when near critical memory limit. Then we get into situation to constantly increase memory consumption without memory pressure handler being able to activate, so eventually OOM happens. While switching back and forth pages are still rendering but UI is unresponsive because key events seems to be queued.
Our analysis has shown that memory polling occurs normally but responding to memory pressure doesn't, because response is done on main thread which appears to be over scheduled with other functions.
https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-20170728/Source/WTF/wtf/linux/MemoryPressureHandlerLinux.cpp#L325

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
