### ISSUE TITLE
WebProcessPool destructor causes a failed assertion

### ISSUE THREAD

**Issue by Teider** [Metrological/WebKitForWayland#564]
During the exit of our application, the following occurs after the end or our main function:

```
ASSERTION FAILED: RunLoop::isMain()
<path to wpe>/Source/WebKit/UIProcess/GenericCallback.h(212) : void WebKit::CallbackMap::invalidate(WebKit::CallbackBase::Error)
```

This call to invalidate originates from the WebProcessPool destructor.

Comparing with a reference implementation: https://github.com/Igalia/cog, the following log from WTF::RefCountedLeakCounter appears on application exit:

```
LEAK: 1 WebProcessPool
LEAK: 1 WebPageProxy
```

On this reference implementation, the WebProcessPool destructor is never called.

This issue ocurred on wpe-2.22.3, running on a Raspberry Pi 3 Model B.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
