### ISSUE TITLE
Disable Automatic Inference Engine

### ISSUE THREAD

**Issue by Lokomojo** [Metrological/WebKitForWayland#572]
WebKit's Automatic Inference Engine prevents audio and video from playing if the page has not been interacted with.

This causes significant issues for those using WPE in "kiosk mode" which doesn't accept user interaction.

Consider an option to disable this?

**Comment by Lokomojo** [comment]
In Settings.yaml:

`videoPlaybackRequiresUserGesture:
  initial: defaultVideoPlaybackRequiresUserGesture
audioPlaybackRequiresUserGesture:
  initial: defaultAudioPlaybackRequiresUserGesture`

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
