### ISSUE TITLE
Div background images are corrupted

### ISSUE THREAD

**Issue by igor-borovkov** [Metrological/WebKitForWayland#574]
_Question: is it easy to identify a backportable change for this issue?_

Reproducible in 
"revision date: Jun 4, 2018"
SRCREV = "c699f32f92e227955b252528ed8ececa6118793e"
BASE_URI ?= "git://github.com/WebPlatformForEmbedded/WPEWebKit.git;protocol=http;branch=wpe-20170728"
but **not on the latest revision from wpe-20170728**

very simple repro page:
http://test.borovkov.com/amazon/amazon3.html

rendering result:
https://photos.app.goo.gl/A6rGEukhGtHHJurk7

**UPDATE:**
artifacts might be hard to see on the "rendering result" photo

here is the photo from an original bug report 
https://jira-ext.amazondcl.com/secure/attachment/33189/Radio_buttons.jpg

here is the original image that is shown with artifacts:
https://pv.media-amazon.com/images/G/01/blast/images/template/radio/radio-focused-signed-unselected._CB_.png   

depending on a "background-size" value (width) artifact(s) move around the image (see "rendering result" photo - multiple divs with different background-size values for width)

**Comment by magomez** [comment]
Please cherry-pick 3bc0da687bae3a756bcacac6493315ba3e700794, that should fix the issue.

**Comment by woutermeek** [comment]
@igor-borovkov does @magomez his recommendation solve you issue?

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
