### ISSUE TITLE
[RP3+] Not smooth navigation on youtube/tv

### ISSUE THREAD

**Issue by jacek-skiba-red** [Metrological/WebKitForWayland#580]
Hello,

We observed that on RP3+ horizontal/vertical navigation on youtube/tv is not smooth. When we move from tile to tile we see only 3 frames during the transition: https://drive.google.com/file/d/1ZiQ8fqMzf5jtgdaSschqft9VzmrnLTBg/view

Youtube certification (starting from 2017) requires 12 fps during vertical/horizontal navigation. Please check for comparison youtube/tv on x86 chrome.

Low fps numer during transition it's a bug related to Raspberry Pi platform backend or wpewebkit? Or maybe it's a issue related to platform performance?

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
