### ISSUE TITLE
Google’s Material Icon Font won’t render

### ISSUE THREAD

**Issue by drewcovi** [Metrological/WebKitForWayland#582]
I’ve verified the fonts rendering on various platforms and WebKit browsers but it seems the material icon font won’t load. Are there any known issues with woff fonts?

**Comment by woutermeek** [comment]
@drewcovi could you copy/paste a small test html example?

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
