### ISSUE TITLE
Package 'virtualkeyboard', required by 'world', not found

### ISSUE THREAD

**Issue by ashwinrayaprolu** [Metrological/WebKitForWayland#584]
For config configs/raspberrypi3_wpe_defconfig

--   Package virtualkeyboard was not found in the pkg-config search path.
Perhaps you should add the directory containing `virtualkeyboard.pc'
to the PKG_CONFIG_PATH environment variable
Package 'virtualkeyboard', required by 'world', not found
CMake Error at /home/vagrant/wpe-buildroot/output/host/usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /home/vagrant/wpe-buildroot/output/host/usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  cmake/FindLibVirtualKeyboard.cmake:10 (pkg_check_modules)
  CMakeLists.txt:32 (find_package)

I get above issue. Any one have clue on how to fix this?

**Comment by bramoosterhuis** [comment]
hey @ashwinrayaprolu1984,

This is a cmake or configuration issue. virtualkeyboard is part of the WPEFramework package. Which package is needing it, I guess it's not WPEWebKit? Can you maybe share the configure command (make V=1 <package>-reconfigure) of that package? I think we need to fix the cmake.

**Comment by ashwinrayaprolu** [comment]
I used 
make raspberrypi3_wpe_defconfig

I disable in .config file and it worked for me.
BR2_PACKAGE_WPEFRAMEWORK_VIRTUALINPUT

But i'm not able to get touch working. I'm not sure if this has anything to do with touch.
Still investigating

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
