### ISSUE TITLE
Wifi config isn't persistent

### ISSUE THREAD

**Issue by sleek-geek** [Metrological/WebKitForWayland#586]
Hello,
When trying to save WIFI ssid config, it's connecting and saved, but on reboot they are completely gone. and I have to renter them again.Is it a build related issue ?! I don't see config files anywhere in the root filesystem.I am using the buildroot repository to generate the img for a RPI3.

**Comment by sleek-geek** [comment]
in fact all settings are not persistent for some reason.

**Comment by Minasodrom** [comment]
Got the same issue building with buildroot for raspberrypi3. Is there an other way to hardcode wifi settings during build?

edit: this propably belongs in wpe framework

**Comment by woutermeek** [comment]
@samy-mohsen Could you describe a bit more on what you are trying to achieve?
It does not sound like a WPEWebKit issue, but more like a configuration issue of the RPI build.

**Comment by sleek-geek** [comment]
@woutermeek 

> Could you describe a bit more on what you are trying to achieve?

We are trying to build the wpe image using buildroot method, but so far no config persists at all.

> It does not sound like a WPEWebKit issue, but more like a configuration issue of the RPI build.

Do you need the build config file ?! Can you point out which configs might cause this issue ?

**Comment by sleek-geek** [comment]
@woutermeek
Also wanted to point out that all filesystems are writable when I checked.

**Comment by ghost** [comment]
i can solve your issues, however not from your fixed-price posting.... hourly...

**Comment by pwielders** [comment]
@Minasodrom you are right. This is functionality that belongs to the Wifi plugin in the WPEFramework. This  is not part of the WebKit. The WPEFramework is a framework to start/host the webkit browser and all kind of other pieces of functionality that do not belong in a browser. 
The plugins, running in the WPEframework, of wich the WiFiPlugin is one, translate lowlevel functionality into RESTFull API's which can be used in the browser. The RESTFull API will have a counter part in the very near future (coming few weeks) based on JSONRPC.
This plugin (found here: https://github.com/WebPlatformForEmbedded/WPEFrameworkPlugins/tree/master/WifiControl) is actually a simple gateway to wpa_supplicant. It is known that the save function is not properly working. a Jira ticket is created and will be adressed in the next few weeks. As it is open source, you are offcourse welcome to fix it as well ;-)
The code to save the config is here:
https://github.com/WebPlatformForEmbedded/WPEFrameworkPlugins/blob/master/WifiControl/WifiControl.cpp#L289-L304

**Comment by pwielders** [comment]
@samy-mohsen the persist location on the rapsberrypi image is /root, here it mounts the second partition of the SD card and it mounts it RW. The path is configured in the /etc/WPEFramework/config.json, field persistentpath. You could change it to any other location but the buildroot image should be oke. 
There is definitly some stuff stored there but I already got some reports that the WiFi configuration is not stored correctly, see aslo my remark above. 
You could potentially try to generate a config in /root/WifiControl/wpa_supplicant.conf (see https://github.com/WebPlatformForEmbedded/WPEFrameworkPlugins/blob/master/WifiControl/WifiControl.cpp#L99) as this is where the plugin will start reading for its configuration.

**Comment by pwielders** [comment]
I think this issue needs to be moved to: https://github.com/WebPlatformForEmbedded/WPEFrameworkPlugins
