### ISSUE TITLE
Rendering 3d video

### ISSUE THREAD

**Issue by ghost** [Metrological/WebKitForWayland#603]
Hi ,
I am trying to render 3d video on RPI3 , I have taken the latest build and master branch of wpe-webkit , well when I look into the stable branch 3D video rendered properly but on latest build only black screen is coming and when i run 2 to three times a still image came .
please help me on this .

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
