### ISSUE TITLE
X11 backend for WPE

### ISSUE THREAD

**Issue by peoro** [Metrological/WebKitForWayland#611]
I'd like to try and write an X11 backend for WPE WebKit. Both to familiarize with WPE and to have it running on my system.  
Two days ago I posted [this issue](https://github.com/WebPlatformForEmbedded/meta-wpe/issues/315) on the meta-wpe repository, and was told to ask here.

Since then I've started to experiment. My understanding grew a bit, but I still have some doubts.

I've learned a few things:

- It's necessary to have a backend in its own shared object, external to the launcher. [Libwpe](https://github.com/WebPlatformForEmbedded/libwpe) in fact loads a dynamic library and wraps the backend functions for WebKit to use.

- The launchers use a backend's own API directly, besides libwpe's. Most launchers (dyz, QtViewBackend etc) exclusively support [WPEBackend-fdo](https://github.com/Igalia/WPEBackend-fdo). Cog can supports multiple backends through a plugin system (`libcogplatform-*.so`) - although currently only a plugin for fdo is implemented; if no plugin is found, cog falls back on starting webkit without creating a surface.

- [WPEBackend-mesa](https://github.com/WebPlatformForEmbedded/WPEBackend-mesa) seems to hint about a possible X11 support.
  Unfortunately that backend seems outdated: it needs to be patched just to build it, and I couldn't get it to run properly.

Now I'm wondering:

1. I suspect that the reason why launchers need to use a backend's API directly is because it's the launcher responsibility to create a window/surface for the backend to draw on, but there's no generic way in libwpe to pass a platform-dependent surface to the backend.  
This might be unnecessary for backends that draw directly on the framebuffer thorugh DRM (e.g. [WPEBackend-rdk](https://github.com/WebPlatformForEmbedded/WPEBackend-rdk)), but it's necessary for Wayland or X11.

   Is this correct?

2. For my goal of showing WPE in an X11 window I need to write an X11 backend that exposes EGL to libwpe, and a launcher (or maybe a platform plugin for cog) that creates an X11 window, instantiates WebKit and handles input.

   Am I on the right track?  
I'm open to suggestions!

**Comment by ankitsingh1508** [comment]
Hi @peoro ,
Did you any solution for cog over X11 ?

**Comment by peoro** [comment]
No, didn't find any solution and given the lack of support I stopped looking.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
