### ISSUE TITLE
LighteningDemoApp in Webkit Browser Not displaying Fading and Background picture in RPI Platform

### ISSUE THREAD

**Issue by pavannandyala** [Metrological/WebKitForWayland#613]
when we try to load https://github.com/WebPlatformForEmbedded/Lightning-Demo-App in webkit browser it not displaying background picture and fading effect, 
not observed  which observed with chrome browser
Expected image
![expected](https://user-images.githubusercontent.com/22341841/61458877-29e50780-a989-11e9-96c0-b303783165cb.png)
Observed picture in TV
![observed](https://user-images.githubusercontent.com/22341841/61458880-2d788e80-a989-11e9-80ba-906db55efb9e.jpg)

**Comment by woutermeek** [comment]
@pavannandyala which version of WPEWebKit are you using?

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
