### ISSUE TITLE
WPE WebKit MiniBrowser cant't open new windows,can't jump  to a new page.

### ISSUE THREAD

**Issue by Hoy-June** [Metrological/WebKitForWayland#614]
hello,
When I open a webpage with MiniBrowser, the webpage works fine, but I can't jump from that webpage to a new page.

In first terminal I executed:weston --socket=wpe. Weston Window shown.
In second terminal: WAYLAND_DISPLAY=wpe MiniBrowser --automation http://www.taobao.com. The page loads successfully on Weston Window，But when I click on the options in the page, the Weston window does not change,it didn't create a new window.

Please for support.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
