### ISSUE TITLE
How do I select a backend during build?

### ISSUE THREAD

**Issue by kytart** [Metrological/WebKitForWayland#626]
I built WPE Webkit 2.25.1 and tried to run it in cog but it ends with error
```
wpe: could not load the impl library. Is there any backend installed?: Error loading shared library libWPEBackend-default.so: No such file or directory
Aborted
```

From there I realized I gotta somehow pick a backend during build. I want to use wpebackend-fdo, but I don't know how to pick it during build. It's not obvious from the cmake files and it's not documented anywhere.

Can somebody please help me? Thank you!

**Comment by aperezdc** [comment]
@kytart In which environment are you running Cog? If you are on Wayland, you can use `cog --platform=fdo …` and the [FDO backend](https://github.com/Igalia/WPEBackend-fdo) will be configured.

Alternatively, you can provide a `libWPEBackend-default.so` symlink to the actual backend you want to use. For example, this is known to work with the [RDK backend](https://github.com/WebPlatformForEmbedded/WPEBackend-rdk), assuming your installation is in `/usr/local` (change the path accordingly):

```sh
cd /usr/local/lib
ln -snf libWPEBackend-rdk.so libWPEBackend-default.so
```

After that you should be able to start `cog` and the error should be gone. Note that you only need to use the `--platform=fdo` command line option if you are using the FDO backend.

**Comment by kytart** [comment]
Thanks, that works!
