### ISSUE TITLE
Is it possible to exclude fdo completely from build?

### ISSUE THREAD

**Issue by kytart** [Metrological/WebKitForWayland#630]
I wanna run wpe webkit with wpebackend-rdk but it seams that compilation requires wpebackend-fdo anyway. I would like to completely exclude it if possible, because it adds a bunch of dependencies that bloat the system even when I don't use fdo at all. Is it possible?

**Comment by aperezdc** [comment]
The WPE WebKit build only needs WPEBackend-fdo in the following cases:

- The Qt API is enabled (`-DENABLE_WPE_QT_API=ON`).
- The MiniBrowser is being build (`-DENABLE_MINIBROWSER=ON`).
- Developer mode is enabled (`-DDEVELOPER_MODE=ON`).

If you do not need any of these options, you can disable them and you will not need WPEBackend-fdo for building WPE WebKit—you *still* need libwpe, of course.

**Comment by kytart** [comment]
I need the minibrowser. Why is fdo needed for it if you have a choice to
use a different backend?

**Comment by kytart** [comment]
Also, maybe I'm not entirely sure what's minibrowser. If I want to run wpe webkit with cog and wpewebkit-rdk in fullscreen, do I need the minibrowser for that? I assume the minibrowser means "the standalone browser" or something like that.

**Comment by aperezdc** [comment]
@kytart If you intend to use Cog, then you do *not* need the MiniBrowser.

(The MiniBrowser is a very bare-bones browser which is included with the WebKit sources and is used for testing things, usually only developers want to build it—it has even less features than Cog.)

**Comment by kytart** [comment]
I'm closing this. This answer pretty much summarizes it. Thank you @aperezdc!

> The WPE WebKit build only needs WPEBackend-fdo in the following cases:
> 
>     * The Qt API is enabled (`-DENABLE_WPE_QT_API=ON`).
> 
>     * The MiniBrowser is being build (`-DENABLE_MINIBROWSER=ON`).
> 
>     * Developer mode is enabled (`-DDEVELOPER_MODE=ON`).
> 
> 
> If you do not need any of these options, you can disable them and you will not need WPEBackend-fdo for building WPE WebKit—you _still_ need libwpe, of course.
