### ISSUE TITLE
[IntersectionObserver] IntersectionObserver Implementation

### ISSUE THREAD

**Issue by skumarbdc11** [Metrological/WebKitForWayland#636]
I am currently using wpe-2.22 branch for a BRCM STB, The IntersectionObserver callback is called only during the object creation and no more afterwards even after the object comes in viewport.

Does this feature completely integrated here? Any quick guideline on adding this full fledged implementation in this branch?

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
