### ISSUE TITLE
Choppy animation of video positioning/scaling

### ISSUE THREAD

**Issue by emutavchi** [Metrological/WebKitForWayland#638]
Probably specific to a configuration that uses video hole punching. It looks like the positioning/resizing of the actual video is delayed/throttled.

Reproducible on https://5zsmx.csb.app/, https://qual-e.appspot.com/scaling.html

branch=wpe-20170728, src rev = "bc64bbadf261ab2e618c19653befb264fa757e23"

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
