### ISSUE TITLE
No punch hole created on loading any youtube video URL on WPE Webkit 2.22

### ISSUE THREAD

**Issue by moorthy-bs** [Metrological/WebKitForWayland#640]
There is an issue that punch hole not created while loading youtube video url on wpewebkit 2.22 where video rectangle is showing whitescreen (no video displayed, may be playing behind) whereas when any video loads through 'autoload' is displaying on the rectangle (hole punch created). The issue is when loading the URL
Environment details:
Platform: RPI3 32 bit (vc4 graphics)
distro: yoe distro (yocto build)
meta-wpe: master branch
westeros: westeros-sink is used (v4l2 decoder + kms)
wpewebkit: 2.22 (westeros-sink is enabled with hole punch)

**Comment by moorthy-bs** [comment]
Follow the below procedure to build WPE westeros image on YOE distro to reproduce this issue

1) git clone --recurse-submodules -j8 -b master git://github.com/YoeDistro/yoe-distro.git YOE
2) cd YOE/sources
3) git clone  https://github.com/WebPlatformForEmbedded/meta-wpe
4) Add `DOCKER_REPO=none` in raspberrypi3-envsetup.sh
5) source ./raspberrypi3-envsetup.sh
6) yoe_setup
7) bitbake-layers add-layer <path for sources dir>/meta-wpe
8) bitbake wpe-westeros-image
9) yoe_install_image /dev/sdX wpe-westeros-image

Note: /usr/lib/libwesteros_gl.so.0 to be preloaded

**Comment by moorthy-bs** [comment]
When youtube video url loaded, setSize() is called around 3 times with different values, 1446x813, 0x0 and 1280x720 respectively. before this call, texturemapper layer buffer got destroy and newly created whereas in working scenario (auto loaded video) only one time setSize() is called only once with value 1280x720.
So, a workaround is made by calling pushNextHolePunchBuffer() in setSize() forcefully is creating a punch hole on this scenario.

**Comment by magomez** [comment]
I've just pushed dbaec6ed91c6e27e7f152ea04c0e6d3d9e79542f to the wpe-2.22 branch, that should fix the issue.
@moorthy-bs could you test and confirm, please?

**Comment by moorthy-bs** [comment]
Thanks @magomez It's working!

**Comment by magomez** [comment]
Let's close this then :)
