### ISSUE TITLE
setting max fps

### ISSUE THREAD

**Issue by Minasodrom** [Metrological/WebKitForWayland#642]
hi, i am building for the rpi3 on the buildroot milestone rc2.3.
i am setting the environment variable WEBKIT_MAXIMUM_FPS (as per https://github.com/WebPlatformForEmbedded/ThunderNanoServices/commit/2499aa15f44d0dac1e13eb50a0bacc95ac8bb283)
is this not supposed to work?
The lcd panel we are using does not allow for 30hz and our animations run with about 50 fps so i would like to limit the framerate to 30.
Thank you.

**Comment by woutermeek** [comment]
@Minasodrom yes that is supposed to work. Nowadays the repository has moved, but the setting is still the same.
https://github.com/rdkcentral/ThunderNanoServices/blob/f2790ff0ac89c6244bb061961c7042d8652816e5/WebKitBrowser/WebKitImplementation.cpp#L1303
