### ISSUE TITLE
Webprocess-JSC crash with signature "prepareForExecution<JSC::FunctionExecutable>"

### ISSUE THREAD

**Issue by varumugam123** [Metrological/WebKitForWayland#645]
Hi, we are observing crashes with the above mentioned signature during video playback. The exact scenario to reproduce this is still not clear to us. 

We are using wpe-20170728 branch and crash was observed with below versions "bc64bbadf261ab2e618c19653befb264fa757e23", "c0bb44a4053c261212b865e74b553816d88a9d37".

I have attached few stack traces here for your reference.
[crash_3.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/4122859/crash_3.txt)
[crash_1.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/4122860/crash_1.txt)
[crash_2.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/4122861/crash_2.txt)

Could you check this?

**Comment by woutermeek** [comment]
@varumugam123 I think we need a little more information on the crash, is it possible to provide a url or html with which we can reproduce it?

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
