### ISSUE TITLE
WPEWebProcess getting crashed with the signature "setupVarargsFrame" when playing Video from Hulu and other HTML apps

### ISSUE THREAD

**Issue by Ameerrafiq** [Metrological/WebKitForWayland#646]
The crash has been identified in the boxes like AxG1V3 during playback of video in html apps. Exact steps to reproduce is not available as they are occurring random and intermittently. The branch being used is wpe-20170728. 

Stack traces has been added for further analysis

[mini_dump_2.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/4180651/mini_dump_2.txt)
[mini_dump_3.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/4180652/mini_dump_3.txt)
[mini_dump_1.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/4180653/mini_dump_1.txt)

**Comment by eocanha** [comment]
I thought this was a multimedia related bug, but after seeing the stacktraces it looks like a JavaScriptCore bug. Somebody else with JSC experience should have a look at it.

**Comment by woutermeek** [comment]
@guijemont could you please have a look at this?

**Comment by woutermeek** [comment]
@Ameerrafiq is this crash the same as #645 ?

**Comment by Ameerrafiq** [comment]
No, they are different issue

**Comment by woutermeek** [comment]
@Ameerrafiq can you share an html page with the video which has the problem? (you can mail it to me in private)

**Comment by Ameerrafiq** [comment]
@woutermeek , i have shared the url with you in mail with the subject of mail as "WPEWebProcess crashes with signature "setupVarargsFrame" when playing hulu video". The thread has been updated again. Thanks

**Comment by guijemont** [comment]
As I can see them, I can't deduce much from the attached stack trace, though I'm not familiar with this mini dump format. Is there some tool to "decode" it? Mostly, I'm interested to know if the argument values are saved in some way that I don't get (though it doesn't look like it), and if not, are you able to provide a trace with argument values?

**Comment by Ameerrafiq** [comment]
At this point, we are unable to provide you trace with argument values as it is not available. As far as we know, it is getting crashed when jsCast, but arguments to cast is not available.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
