### ISSUE TITLE
[WPE Browser][WPE Performance Test][Bench Mark test]Regex-dna.js(inside bomb.js) sub-test is crashed while running on WPE browser.

### ISSUE THREAD

**Issue by SureshKhurdiya** [Metrological/WebKitForWayland#647]
We are running WPE browser on our PLATFORM.  Our platform is based on Broadcom SOC(7439) and as a pre-requisite for running this JestStream2 cases, we always set the WPE_RAM_SIZE as higher value (600MB) than the usual.  While running Regex-dna testcase which is part of JetStream2 we are seeing browser crash.  We did not notice any runtime exception in the logs.
  
The JetStream2 benchmark test case is working in other browser like chrome, safari etc.
 
Original link to trigger the JetStream2 performance test:
https://browserbench.org
 
WPE version:2.22
 
Investigation:
As per java scripts code of Regex-dna.js, there is a big string manipulation happening with regular expression and couple of logic related to string replacement and JsonStringify function.
 
 
Temporary changes:
If We add console.log in Regex-dna.js file anywhere, then this crash is not observed. We are not sure how it is resolving the issue.
 
Another observation is, when we build the WPE without -NDEBUG option (basically DEBUG build) then this specific test case is passed without any modification.
 
Our platform has previous version of WPE (Snapshot: 9bdb033861b105b08dc9839d1458513155bcedab, branch: wpe-20170728) and this test case is passed in that version.
 
Any Idea or suggestion will help us fix this issue.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
