### ISSUE TITLE
STM backend porting to new WPE-platform infra

### ISSUE THREAD

**Issue by blino** [Metrological/WebKitForWayland#65]
The STM backend is not yet ported to the new WPE-platform infra, and still lives disabled in WPE-old.

I am using this backend on Broadcom STB boards.
I can help to port the backend to the new infra, if this is not work in progress already.

By the way, this should probably be renamed, since this is really just a generic wayland-egl backend so far.

**Comment by albertd** [comment]
@blino yes thats fine, just do a pull request when done, so we can review for you.
