### ISSUE TITLE
How to remote debug from OSX?

### ISSUE THREAD

**Issue by kvasdopil** [Metrological/WebKitForWayland#663]
Hi there.
I'm using WPEWebkit + cog on ubuntu, with developer extensions enabled and WEBKIT_INSPECTOR_SERVER env var set up properly. I am able to connect from other machine running Epiphany browser on Linux using `inspector://<my-machine-ip>:<port>` URI scheme. 
Now I'm trying to figure how do I connect to remote inspector server from my dev computer which is running OSX:
- Safari (an obvious candidate) does not seem to have a way to enter ip address and port of external device to debug.
- Chrome does not seem to support debugging protocol used by WPEWebkit since adding device:port on 'chrome://inspect/#devices' page does nothing.
- Firefox does not seem to support it as well, adding device:port on `about:debugging` shows timeout error.

Is there any way to make this work?

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
