### ISSUE TITLE
RaspberryPI Zero Compiling Error

### ISSUE THREAD

**Issue by suniltop** [Metrological/WebKitForWayland#669]
Hi all,

I have a issue different issue. Anyone knows how to solve ?
I have use Rev: e044951cb6a9bf2f6f1c20ec4a6630d05c40a3d6 but i tested already latest rev but no luck.
In addition same error occurs both buildroot and yocto.

Error:

[1221/2724] Generating ../../DerivedSources/JavaScriptCore/LLIntAssembly.h
FAILED: DerivedSources/JavaScriptCore/LLIntAssembly.h 
cd /home/username/buildroot/output/build/wpewebkit-e044951cb6a9bf2f6f1c20ec4a6630d05c40a3d6/build-Release/DerivedSources/JavaScriptCore && /home/username/buildroot/output/host/usr/bin/ruby /home/username/buildroot/output/build/wpewebkit-e044951cb6a9bf2f6f1c20ec4a6630d05c40a3d6/Source/JavaScriptCore/offlineasm/asm.rb -I/home/username/buildroot/output/build/wpewebkit-e044951cb6a9bf2f6f1c20ec4a6630d05c40a3d6/build-Release/DerivedSources/JavaScriptCore/ /home/username/buildroot/output/build/wpewebkit-e044951cb6a9bf2f6f1c20ec4a6630d05c40a3d6/Source/JavaScriptCore/llint/LowLevelInterpreter.asm /home/username/buildroot/output/build/wpewebkit-e044951cb6a9bf2f6f1c20ec4a6630d05c40a3d6/build-Release/bin/LLIntOffsetsExtractor /home/username/buildroot/output/build/wpewebkit-e044951cb6a9bf2f6f1c20ec4a6630d05c40a3d6/build-Release/DerivedSources/JavaScriptCore/LLIntAssembly.h && /home/username/buildroot/output/host/usr/bin/cmake -E touch_nocreate /home/username/buildroot/output/build/wpewebkit-e044951cb6a9bf2f6f1c20ec4a6630d05c40a3d6/build-Release/**DerivedSources/JavaScriptCore/LLIntAssembly.h
offlineasm: No magic values found. Skipping assembly file generation.**

**Comment by guijemont** [comment]
Hi @suniltop. We don't support the JIT tiers and offlineassembly for armv6 processors (which includes the Pi Zero). You need to disable this, I think that passing `-DENABLE_JIT=OFF` to cmake should do the trick.

**Comment by suniltop** [comment]
Thank you, @guijemont I have compiled succesfully.
But i wonder that what i have lost specification at wpewebkit.
I searched on the net about what is JIT means, it is only explain as Just In Time debug.
