### ISSUE TITLE
Failed to build WPE port dependencies with jhbuild

### ISSUE THREAD

**Issue by zizijun** [Metrological/WebKitForWayland#672]
The error happens when  patch applying
This is the log:

 gst-plugins-good-0003-qtdemux-Clarify-field-name-about-stream-encryption-s.patch *** [17/34]
patch -p1 < "/home/WPE/WPEWebKit/Tools/gstreamer/patches/gst-plugins-good-0003-qtdemux-Clarify-field-name-about-stream-encryption-s.patch"
patching file gst/isomp4/qtdemux.c
Hunk #1 succeeded at 7857 (offset -239 lines).
Hunk #2 succeeded at 7888 (offset -239 lines).
Hunk #3 succeeded at 7913 (offset -239 lines).
Failed to build WPE port dependencies with jhbuild
Died at Tools/Scripts/update-webkitwpe-libs line 25.

I would appreciate any help

**Comment by philn** [comment]
Did you really clone this fork or are you trying to build the upstream repo from webkit.org ?

**Comment by zizijun** [comment]
I continue to update webkitwpe libs by commenting code in `Tools/gstreamer/jhbuild.modules`
````
<!-- <patch file="gst-plugins-good-0007-matroskademux-Allow-Matroska-headers-to-be-read-more.patch" strip="1" /> --> <!-- Merged as 9dc7859184d4b7ad1dd7e2b54704e994dbace329 (to be shipped in 1.14.4) -->
 <!-- <patch file="gst-plugins-good-0008-matroskademux-Refactor-track-parsing-out-from-adding.patch" strip="1" />--> <!-- Merged as f279bc5336dda19741a5996a108da42dd3201366 (to be shipped in 1.14.4) -->
 <!-- <patch file="gst-plugins-good-0009-matroskademux-Parse-successive-Tracks-elements.patch" strip="1" />--> <!-- Merged as 0e60076a390fd3ef53d350940b2c695ff7bbe008 (to be shipped in 1.14.4) -->
<!-- <patch file="gst-plugins-good-0010-matroskademux-Emit-no-more-pads-after-parsing-Tracks.patch" strip="1" />--> <!-- Merged as 7ceefec7141069b4adf4451a874766f8760c66d6 (to be shipped in 1.14.4) -->
````
And then I' m receiving the following error message:
````
make[4]: “/home/WPE/WPEWebKit/WebKitBuild/DependenciesWPE/Build/gst-plugins-bad-1.14.1/ext/wayland”
  CC       libgstwaylandsink_la-gstwaylandsink.lo
  CXX      libgstopenh264_la-gstopenh264enc.lo
  CC       libgstbz2_la-gstbz2dec.lo
In file included from /usr/include/c++/7/cstdint:35:0,
                 from /usr/include/OpenEXR/ImfFrameBuffer.h:55,
                 from /usr/include/OpenEXR/ImfRgbaFile.h:51,
                 from /home//android/WPE/WPEWebKit/WebKitBuild/DependenciesWPE/Source/gst-plugins-bad-1.14.1/ext/openexr/gstopenexrdec.cpp:30:
/usr/include/c++/7/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^~~~~
  CC       libgstcurl_la-gstcurlbasesink.lo
  CC       libgstopenglmixers_la-gstglbasemixer.lo
Makefile:914: recipe for target 'libgstopenexr_la-gstopenexrdec.lo' failed
make[3]: *** [libgstopenexr_la-gstopenexrdec.lo] Error 1
````
My gcc version is  7.5.0, i want to know which version of gcc should I use to build wpe, or I can fix it by adding  options, like `-std=c++0x `or `-std=gnu++0x`, as accepted in [https://github.com/openalpr/openalpr/issues/528](url)

**Comment by calvaris** [comment]
JHBuild is not used in the embedded so for that you would need to check buildroot or yocto. For upstream, please use the upstream bugzilla or correct project.

Closing this now.

**Comment by zizijun** [comment]
您好，您的邮件已收到，我会尽快回复你的邮件上海交通大学金初阳
