### ISSUE TITLE
 buildroot build fails for rpi4 32-bit after post-image.sh saying error about config

### ISSUE THREAD

**Issue by NirajTummala** [Metrological/WebKitForWayland#676]
ln -sf rootfs.ext2 /home/nirajtummala/buildroot/output/images/rootfs.ext4
>>> Executing post-image script board/raspberrypi4/post-image.sh
board/raspberrypi4/genimage-raspberrypi4.cfg:30: no sub-section title/index for 'config'
INFO: cmd: "mkdir -p "/home/nirajtummala/buildroot/output/build/genimage.tmp"" (stderr):
INFO: cmd: "rm -rf "/home/nirajtummala/buildroot/output/build/genimage.tmp"/*" (stderr):
INFO: cmd: "mkdir -p "/home/nirajtummala/buildroot/output/build/genimage.tmp"" (stderr):
INFO: cmd: "cp -a "/tmp/tmp.3rJcfQQAN8" "/home/nirajtummala/buildroot/output/build/genimage.tmp/root"" (stderr):
INFO: cmd: "find '/home/nirajtummala/buildroot/output/build/genimage.tmp/root' -depth -type d -printf '%P\0' | xargs -0 -I {} touch -r '/tmp/tmp.3rJcfQQAN8/{}' '/home/nirajtummala/buildroot/output/build/genimage.tmp/root/{}'" (stderr):
INFO: cmd: "mkdir -p "/home/nirajtummala/buildroot/output/images"" (stderr):
INFO: vfat(boot.vfat): cmd: "dd if=/dev/zero of="/home/nirajtummala/buildroot/output/images/boot.vfat" seek=67108864 count=0 bs=1 2>/dev/null" (stderr):
INFO: vfat(boot.vfat): cmd: "mkdosfs '/home/nirajtummala/buildroot/output/images/boot.vfat'" (stderr):
INFO: vfat(boot.vfat): adding file 'zImage' as 'zImage' ...
INFO: vfat(boot.vfat): cmd: "MTOOLS_SKIP_CHECK=1 mcopy -bsp -i '/home/nirajtummala/buildroot/output/images/boot.vfat' '/home/nirajtummala/buildroot/output/images/zImage' '::'" (stderr):
INFO: vfat(boot.vfat): adding file 'bcm2711-rpi-4-b.dtb' as 'bcm2711-rpi-4-b.dtb' ...
INFO: vfat(boot.vfat): cmd: "MTOOLS_SKIP_CHECK=1 mcopy -bsp -i '/home/nirajtummala/buildroot/output/images/boot.vfat' '/home/nirajtummala/buildroot/output/images/bcm2711-rpi-4-b.dtb' '::'" (stderr):
INFO: vfat(boot.vfat): adding file 'rpi-firmware/cmdline.txt' as 'rpi-firmware/cmdline.txt' ...
INFO: vfat(boot.vfat): cmd: "MTOOLS_SKIP_CHECK=1 mcopy -bsp -i '/home/nirajtummala/buildroot/output/images/boot.vfat' '/home/nirajtummala/buildroot/output/images/rpi-firmware/cmdline.txt' '::'" (stderr):
INFO: vfat(boot.vfat): adding file 'rpi-firmware/config.txt' as 'rpi-firmware/config.txt' ...
INFO: vfat(boot.vfat): cmd: "MTOOLS_SKIP_CHECK=1 mcopy -bsp -i '/home/nirajtummala/buildroot/output/images/boot.vfat' '/home/nirajtummala/buildroot/output/images/rpi-firmware/config.txt' '::'" (stderr):
INFO: vfat(boot.vfat): adding file 'rpi-firmware/fixup.dat' as 'rpi-firmware/fixup.dat' ...
INFO: vfat(boot.vfat): cmd: "MTOOLS_SKIP_CHECK=1 mcopy -bsp -i '/home/nirajtummala/buildroot/output/images/boot.vfat' '/home/nirajtummala/buildroot/output/images/rpi-firmware/fixup.dat' '::'" (stderr):
INFO: vfat(boot.vfat): adding file 'rpi-firmware/start.elf' as 'rpi-firmware/start.elf' ...
INFO: vfat(boot.vfat): cmd: "MTOOLS_SKIP_CHECK=1 mcopy -bsp -i '/home/nirajtummala/buildroot/output/images/boot.vfat' '/home/nirajtummala/buildroot/output/images/rpi-firmware/start.elf' '::'" (stderr):
INFO: vfat(boot.vfat): adding file 'rpi-firmware/overlays' as 'rpi-firmware/overlays' ...
INFO: vfat(boot.vfat): cmd: "MTOOLS_SKIP_CHECK=1 mcopy -bsp -i '/home/nirajtummala/buildroot/output/images/boot.vfat' '/home/nirajtummala/buildroot/output/images/rpi-firmware/overlays' '::'" (stderr):
INFO: hdimage(sdcard.img): adding partition 'boot' (in MBR) from 'boot.vfat' ...
ERROR: hdimage(sdcard.img): fiemap /home/nirajtummala/buildroot/output/images/boot.vfat: 25 Inappropriate ioctl for device
ERROR: hdimage(sdcard.img): failed to write image partition 'boot'
INFO: hdimage(sdcard.img): cmd: "rm -f "/home/nirajtummala/buildroot/output/images/sdcard.img"" (stderr):
ERROR: hdimage(sdcard.img): failed to generate sdcard.img
make: *** [Makefile:835: target-post-image] Error 1
root@NirajTummala:/home/nirajtummala/buildroot#

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
