### ISSUE TITLE
WPEWebprocess hang crash on lightning app

### ISSUE THREAD

**Issue by Balajims88** [Metrological/WebKitForWayland#678]
Hi @woutermeek ,

we are facing hang and crash on the following lightning app with wpe-2.22 commit id 686cd2f7df.
http://lsaauto02.ccp.xcal.tv/assets/ads/rdkv/lightning_scripts_20_5_20/lightning.html?render=rectstress
please find the BT below and help me to resolve the issue.

` Crash Thread #0
Frame	Thread	Module	Source

#0	appendChildWithoutPreInsertionValidityCheck	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WebCore/dom/ContainerNode.cpp:334 (0x0)
#1	insertBefore	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WebCore/dom/ContainerNode.cpp:367 (0x9)
#2	insertBefore	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WebCore/dom/Node.cpp:415 (0x3)
#3	jsNodePrototypeFunctionInsertBefore	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/build/DerivedSources/WebCore/JSNode.cpp:832 (0xf)
#4	@0xb1aff127		
Crash Thread #1
Frame	Thread	Module	Source

#0	libpthread-2.24.so@0xe0d4	libpthread-2.24.so	
#1	__pthread_cond_timedwait	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/futex-internal.h:205 (0x15)
#2	__pthread_cond_timedwait	libc-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/forward.c:162 (0xf)
#3	threadRunLoop	libWPEWebKit-0.1.so.2.2.1	/usr/include/c++/6.4.0/arm-rdk-linux-gnueabi/bits/gthr-default.h:871 (0x3)
#4	threadEntryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/bmalloc/bmalloc/Scavenger.cpp:359 (0x3)
#5	std::execute_native_thread_routine	libstdc++.so.6.0.22	/usr/src/debug/gcc-runtime/6.4.0-r0/gcc-6.4.0/build.arm-rdk-linux-gnueabi.arm-rdk-linux-gnueabi/arm-rdk-linux-gnueabi/libstdc++-v3/src/c++11/../../../../../../../../../../work-shared/gcc-6.4.0-r0/gcc-6.4.0/libstdc++-v3/src/c++11/thread.cc:83 (0x3)
#6	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#7	clone	libc-2.24.so	
`

**Comment by woutermeek** [comment]
@Balajims88 the test page does not load for me, could you please supply us a test page which causes the crash?

**Comment by Balajims88** [comment]
@woutermeek  Please find lightning test page in my attachment and run the "Stress-Test" at bottom to reproduce the issue.
[lightning.zip](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/5290710/lightning.zip)

**Comment by magomez** [comment]
@Balajims88, I've been trying to reproduce this crash with the rpi3 but I haven't been able to so far. The test completes for me and the browser doesn't crash (tried several times).
What I have noticed is that the memory usage is quite high during the test (I see it peak at ~460MB). Could it be the case that the browser is running of out of memory? Do you have that amount of memory available on your device?

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
