### ISSUE TITLE
WPEWebProcess (JavaScriptCore) SIGSEGV crash in put() called from operationPutByValCellStrict()

### ISSUE THREAD

**Issue by Gavriliuk** [Metrological/WebKitForWayland#682]
Hi @woutermeek,

We're observing SIGSEGV crashes with the signature [put] and different backtraces
where the function put() is being called from the function operationPutByValCellStrict()

### Example 1:
Id | # | module | function | source | line | addr
-- | - | - | - | - | - | -
0|0|libWPEWebKit-0.1.so.2.2.1|put|wpe-webkit/git/Source/JavaScriptCore/runtime/JSObjectInlines.h|70|0xc
0|1|libWPEWebKit-0.1.so.2.2.1|operationPutByValCellStrict|wpe-webkit/git/Source/JavaScriptCore/runtime/JSCJSValueInlines.h|939|0x18
0|2|||||0x6f527478
0|3|libWPEWebKit-0.1.so.2.2.1|operationPutByValCellStrict|wpe-webkit/git/Source/JavaScriptCore/runtime/JSCJSValueInlines.h|939|0x18
0|4|||||0xfffffff3
0|5|libWPEWebKit-0.1.so.2.2.1|getOwnPropertySlotByIndex|wpe-webkit/build/DerivedSources/WebCore/JSNodeList.cpp|174|0x0

### Example 2:
Id | # | module | function | source | line | addr
-- | - | - | - | - | - | -
0|0|libWPEWebKit-0.1.so.2.2.1|put|wpe-webkit/git/Source/JavaScriptCore/runtime/JSObjectInlines.h|70|0xc
0|1|libWPEWebKit-0.1.so.2.2.1|operationPutByValCellStrict|wpe-webkit/git/Source/JavaScriptCore/runtime/JSCJSValueInlines.h|939|0x18
0|2|||||0x6fd109b8
0|3|libWPEWebKit-0.1.so.2.2.1|operationGetByValGeneric|wpe-webkit/git/Source/JavaScriptCore/jit/JITOperations.cpp|1991|0x28
0|4|||||0xfffffff4
0|5|libWPEWebKit-0.1.so.2.2.1|profiledCall|wpe-webkit/git/Source/JavaScriptCore/runtime/CallData.cpp|69|0x10

### Example 3:
Id | # | module | function | source | line | addr
-- | - | - | - | - | - | -
0|0|libWPEWebKit-0.1.so.2.2.1|put|git/Source/JavaScriptCore/runtime/JSObjectInlines.h|70|0xc
0|1|libWPEWebKit-0.1.so.2.2.1|operationPutByValCellStrict|git/Source/JavaScriptCore/runtime/JSCJSValueInlines.h|939|0x18
0|2|||||0x6f693ad8
0|3|libWPEWebKit-0.1.so.2.2.1|_fini|||0x36332c
0|4|libWPEWebKit-0.1.so.2.2.1|operationGetByValGeneric|git/Source/JavaScriptCore/jit/JITOperations.cpp|1991|0x28

Please help us to resolve this issue

Thanks

**Comment by woutermeek** [comment]
@Gavriliuk could you share how you reproduce this crash? (eg. an example html page)

**Comment by Gavriliuk** [comment]
@woutermeek, these BTs were gotten from automatic crashreports
We receive millions of crashreports per month
The crash I've mentioned above was reported 5 times per 30 days
I have no steps to reproduce the issue

But we have some logs from those crashreports
I can attach some suspicious logging from related crashreports

**Comment by Gavriliuk** [comment]
@woutermeek, could you please take a look on a few examples: [DELIA-45668-070.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/5460104/DELIA-45668-070.txt)

Thanks

**Comment by Gavriliuk** [comment]
Hi @woutermeek,

did you have a chance to take a look on the issue?

It seems we have a deal with a memory corruption
The crash in "put()" is only an indicator but not a reason
To find the root cause we have to know which piece of code corrupts the memory

Thanks

**Comment by woutermeek** [comment]
@Gavriliuk do you have a way of reproducing the issue either on the platform or the RPI?

**Comment by Gavriliuk** [comment]
Unfortunately not

The issue is intermittent and is being observed rarely during mass testing

**Comment by guijemont** [comment]
> It seems we have a deal with a memory corruption
> The crash in "put()" is only an indicator but not a reason
> To find the root cause we have to know which piece of code corrupts the memory

I agree with your analysis @Gavriliuk .
A core file (and associated binaries with debug symbols and source code) could help in figuring this out, or alternatively a backtrace that gives more information on memory (such as with `bt full` in gdb).
Looking at the log+backtrace samples you sent, I can see a few common points between the crashes:
 - the top 2-3 frames of the stack, as you noted. The line in put() where we segfault is:
 ```
       if (obj->structure(vm)->hasReadOnlyOrGetterSetterPropertiesExcludingProto() || obj->methodTable(vm)->getPrototype != defaultGetPrototype)                                                                                           
 ```
 Which is at least 4 pointer dereferences (the 4 `->`), plus likely additional ones in inlined calls, but it looks like we're in the land of js objects heap.
 - the bottom of the frame is always `sharedTimerFiredInternal()`, meaning we're always executing a timer callback. Maybe that could help you investigate what's happening in the js code, which could help you to get to a test case that reproduces the issue (that would be *very* useful to understand what's happening within jsc)
 - we always have some errors from the AAMP-PLAYER in the log, in all but the first one that includes `[AAMP-PLAYER]PrivateStreamAbstractionMPD::FetchFragment:1357 failed.`, though maybe in the first one it was there but before the cutoff? Also, if that error is *very* frequent in your logs outside of this crash, that could be pure coincidence, but if not, that's also somewhere to look at (could code around there do something that invalidates a js object memory? I don't think I have access to that code, so I cannot check), and possibly a hint on crafting a reproduction scenario and/or test.

@Gavriliuk with these last two elements, do you think you could try to craft a way of reproducing the issue? Failing that, is there a way to have a backtrace with more memory info or a core file + binary + debug symbols + source ? With the information I have so far, I don't think I can get much further in the investigation.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
