### ISSUE TITLE
WPEWebProcess crash (JavaScriptCore) due to SIGFPE

### ISSUE THREAD

**Issue by kkanag314** [Metrological/WebKitForWayland#686]
WPEWEbProcess is crashing randomly while launching the peacock application.
The crash is observed in field frequently.

Stack Trace:

Crash thread #0 
Frame	Signature	Module	Source
#0	deallocateLarge	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/bmalloc/bmalloc/Map.h:100 (0x0)
#1	deallocateSlowCase	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/bmalloc/bmalloc/Deallocator.cpp:86 (0xd)
#2	free	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/bmalloc/bmalloc/Deallocator.h:80 (0x3)
#3	sweepLargeAllocations	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/JavaScriptCore/heap/MarkedSpace.cpp:250 (0x3)
#4	sweepInFinalize	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/JavaScriptCore/heap/Heap.cpp:2046 (0x3)
#5	finalize	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1993 (0x3)
#6	handleNeedFinalize	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1914 (0x3)
#7	handleNeedFinalize	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1930 (0x3)
#8	finishChangingPhase	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1506 (0x3)
#9	runEndPhase	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1482 (0x3)
#10	runCurrentPhase	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1136 (0x7)
#11	implFunction	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1740 (0xb)
#12	callWithCurrentThreadState	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/WTF/wtf/ScopedLambda.h:56 (0x1)
#13	collectInMutatorThread	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1752 (0x3)
#14	stopIfNecessarySlow	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1721 (0x5)
#15	stopIfNecessarySlow	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1695 (0x3)
#16	collectIfNecessaryOrDefer	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/JavaScriptCore/heap/HeapInlines.h:269 (0x5)
#17	llint_slow_path_put_by_id	libWPEWebKit.so.0.0.20170728	/usr/src/debug/wpe-webkit/0.4.4+gitAUTOINC+5f899bc2e0-r0/git/Source/JavaScriptCore/heap/HeapInlines.h:198 (0x5)
#18	libWPEWebKit.so.0.0.20170728@0xc28391	libWPEWebKit.so.0.0.20170728	

imagename:AX061AEI_4.4p9s1_PROD_sdy

Crashed URL : https://tv.clients.peacocktv.com/?lmt=0&us_privacy=1-N-

Commit Details : "5f899bc2e0e3736908d46ddf473dc4fe5c7f5c95"

[receiver.log](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/5566311/receiver.log)

**Comment by kkanag314** [comment]
The crash is not 100% reproducible.
The crash is observed randomly while launching the peacock application.

crashed url: https://tv.clients.peacocktv.com/?lmt=0&us_privacy=1-N-

**Comment by woutermeek** [comment]
@kkanag314 I get access denied when I go to the url. Is there a way to open it so we can access it?

**Comment by kkanag314** [comment]
The crash is not observed in field.So,We are closing this ticket.
