### ISSUE TITLE
WebRTC on buildroot/Raspberry PI

### ISSUE THREAD

**Issue by SamDecrock** [Metrological/WebKitForWayland#691]
Hi,

Can someone help me enable WebRTC when building with buildroot for Raspberry Pi? I saw a pull request from 2019, but I'm not sure if it ever got merged.

I tried enabling all WebRTC related packages on buildroot, but that didn't help...

Thanks!
Sam

**Comment by SamDecrock** [comment]
I tried building it with WebRTC enabled using the following 2 forks from @thiblahute:

- https://github.com/thiblahute/buildroot/tree/wpe-2.22%2Bwebrtc
- https://github.com/thiblahute/webkit/tree/wpe-2.22+webrtc

But I couldn't get a simple online WebRTC demo to work 😢

**Comment by calvaris** [comment]
You would need to ensure WebRTC is enabled when WebKit is built. Anyway, at the moment, libwebrtc is the current implementation that would work but a new one based on GstWebRTC is being developed for newer GStreamer and WebKit version that will work better with hardware enabled enconding and decoding.

If you need more help, please let us know. I'l closing this for now.
