### ISSUE TITLE
WPE Webkit not building.

### ISSUE THREAD

**Issue by sahil-siwatch** [Metrological/WebKitForWayland#693]
Hello all. I want to use webkit on my rpi3b+ to display a webpage when the pi boots. I tried building using this tutorial on medium - https://samdecrock.medium.com/building-web-applications-for-wpe-webkit-using-node-js-3347146013f3 but it doesn't work. I could not even build the image. It stops at a place where it can't get access to github page - access denied. sources.buildroot.net. 
Can anyone tell me much simpler way to build image. Less complicated with minimal functionalities to begin with?
Thanks and regards.

![image](https://user-images.githubusercontent.com/53403558/106730998-ff26d680-6634-11eb-9b68-d487a355c622.png)
 this is the error i get

**Comment by woutermeek** [comment]
Could you try to use our meta-wpe layer, that one is up to date:
https://github.com/WebPlatformForEmbedded/meta-wpe
