### ISSUE TITLE
WPEWebProcess crashes on every alternate launch of lightening App

### ISSUE THREAD

**Issue by ManjariMallikarjun** [Metrological/WebKitForWayland#695]
Hi,

WPEWebProcess  is crashing on every alternate running lightening app,
WPE source used from branch wpe-20170728 and commit id is c699f32f92e227955b252528ed8ececa6118793e

Please find the BT below and help me to resolve the issue

Frame	Signature	Module	Source
#0	transformedVisibleRect	libWPEWebKit.so.0.0.20170728	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedGraphicsLayer.cpp:926 (0xd)
#1	updateContentBuffers	libWPEWebKit.so.0.0.20170728	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedGraphicsLayer.cpp:1016 (0x7)
#2	updateContentBuffersIncludingSubLayers	libWPEWebKit.so.0.0.20170728	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedGraphicsLayer.cpp:976 (0x9)
#3	updateContentBuffersIncludingSubLayers	libWPEWebKit.so.0.0.20170728	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedGraphicsLayer.cpp:979 (0xe)
#4	updateContentBuffersIncludingSubLayers	libWPEWebKit.so.0.0.20170728	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedGraphicsLayer.cpp:979 (0xe)
#5	updateContentBuffersIncludingSubLayers	libWPEWebKit.so.0.0.20170728	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedGraphicsLayer.cpp:979 (0xe)
#6	updateContentBuffersIncludingSubLayers	libWPEWebKit.so.0.0.20170728	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedGraphicsLayer.cpp:979 (0xe)
#7	updateContentBuffersIncludingSubLayers	libWPEWebKit.so.0.0.20170728	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedGraphicsLayer.cpp:979 (0xe)
#8	flushPendingLayerChanges	libWPEWebKit.so.0.0.20170728	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebKit/WebProcess/WebPage/CoordinatedGraphics/CompositingCoordinator.cpp:124 (0x8)
#9	layerFlushTimerFired	libWPEWebKit.so.0.0.20170728	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebKit/WebProcess/WebPage/CoordinatedGraphics/CoordinatedLayerTreeHost.cpp:205 (0x9)
#10	_FUN	libWPEWebKit.so.0.0.20170728	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:166 (0x6)
#11	g_main_context_dispatch	libglib-2.0.so.0.4800.1	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gmain.c:3154 (0x3)
#12	g_main_context_iterate	libglib-2.0.so.0.4800.1	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gmain.c:3844 (0x9)
#13	g_main_loop_run	libglib-2.0.so.0.4800.1	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gmain.c:4038 (0x11)
#14	run	libWPEWebKit.so.0.0.20170728	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:96 (0x8)
#15	ChildProcessMain<WebKit::WebProcess, WebKit::WebProcessMain>	libWPEWebKit.so.0.0.20170728	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebKit/Shared/unix/ChildProcessMain.h:61 (0x5)
#16	main	WPEWebProcess	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebKit/WebProcess/EntryPoint/unix/WebProcessMain.cpp:60 (0xd)
#17	__libc_start_main	libc-2.19.so	/usr/src/debug/eglibc/2.19-r0/eglibc-2.19/libc/csu/libc-start.c:285 (0x15)
#18	_start	WPEWebProcess	
#19	WPEWebProcess@0x4da0	WPEWebProcess	
#20	ConvertUTF8toUTF32	WPEWebProcess	/mnt/jenkins/workspace/PACEXG1V1-Yocto-Release/build-pacexg1v1/tmp/work/core2-32-rdk-linux/breakpad/svn-r0/trunk/src/common/convert_UTF.c:535 (0xa)
#21	@0xbfa4a1e0		
#22	@0x6e69622f

**Comment by woutermeek** [comment]
@ManjariMallikarjun could you share the URLs of the lightning apps you use so we can reproduce it on our side? Also could you let us know how it happens? eg. the browser is restarted each app launch, or you switch the URL to launch the new app?

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
