### ISSUE TITLE
Blank page with remote inspector

### ISSUE THREAD

**Issue by madanagopalt** [Metrological/WebKitForWayland#7]
Hi,

I am trying wpe wayland and opened remote inspector, only by the below command:

export WEBKIT_INSPECTOR_SERVER=ipaddress:port

I opened http://ipaddress:port in firefox. It is showing the opened URL in inspectable views. When i click that link, JS Pages are downloaded but showing empty page. Please suggest a way to debug this.

Regards,
Madan

**Comment by philn** [comment]
Duplicate of https://github.com/Metrological/buildroot/issues/107
