### ISSUE TITLE
[wpe-2.22] "playing" event is missing on seek

### ISSUE THREAD

**Issue by varumugam123** [Metrological/WebKitForWayland#700]
Hi,

In wpe-2.22 it looks like the "playing" event is not sent on seeking. 

In wpe-20170728 branch ("5f899bc2e0e3736908d46ddf473dc4fe5c7f5c95") which we were using earlier, sends this event. This change in the event affects the behavior of an app we host.

When I checked the history I came to know that the code related to sending "playing" event were removed as part of https://bugs.webkit.org/show_bug.cgi?id=183383. So it looks like this change is causing the regression.

The missing event can be checked with this simple html 
[seeking.html.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/6070937/seeking.html.txt)

**Comment by varumugam123** [comment]
I tried this patch [restore-scheduling-playing-event.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/6082889/restore-scheduling-playing-event.txt) with that the I observe the event.

@woutermeek @eocanha do you think this will cause any other regressions?

**Comment by eocanha** [comment]
I think the change is fine and won't cause regressions.

The "playing" event was scattered before https://bugs.webkit.org/show_bug.cgi?id=183383, following the conditions mandated by [the old spec](https://www.w3.org/TR/html52/semantics-embedded-content.html#the-video-element) (search for "fire a simple event named playing") or [the new spec](https://html.spec.whatwg.org/#the-video-element) (search for "notify about playing for the element"). It was centralized in setPlaying() after 183383, but that method had a condition to avoid being re-run again if the state was already playing.

As the "waiting" event is still scattered and was never centralized, I don't think there's any issue about returning "playing" to the way it was before.

I'll merge the commit you attached in the wpe-2.22 branch.

**Comment by eocanha** [comment]
Merged in https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/87cbd6cb994c02ba37427c21fa095af7e5ac229d
