### ISSUE TITLE
WebInspector Blank debug window

### ISSUE THREAD

**Issue by AndrisBB** [Metrological/WebKitForWayland#701]
I am trying to connect to the remote device using web-inspector, but as a result I can only see blank web-inspector window.

I am using webkit 2.24.2 or 2.24.3 (from Igalia meta-browser) and Cog 0.3.
If I start Cog with:

```
export WEBKIT_INSPECTOR_SERVER=0.0.0.0:9222
cog 0.0.0.0 --enable-write-console-messages-to-stdout=true --enable-developer-extras=true
```

I can see that page is running in the Epiphany Browser, but if I select inspect only thing I see is blank page. A few years ago I somehow got it working, but I do not remember what have I done. I think I had to use Ubuntu 18 with Epuphany-Browser version 3.28.5, but now I cannot reproduce it anymore.

![Screenshot from 2021-03-08 13-18-16](https://user-images.githubusercontent.com/4208535/110326835-192b4e80-8011-11eb-8e53-5ede14f2271d.png)
![Screenshot from 2021-03-08 13-17-53](https://user-images.githubusercontent.com/4208535/110326840-19c3e500-8011-11eb-8167-72e22faf1e87.png)
![Screenshot from 2021-03-08 13-17-40](https://user-images.githubusercontent.com/4208535/110326841-19c3e500-8011-11eb-9f39-1759e260208a.png)

What I am missing here?

Thanks,

**Comment by AndrisBB** [comment]
If I open another Epiphany and try to debug Web Inspector window, then I can see that it complains that about not existing function on the InspectorBackend object.

// Audit.
**InspectorBackend.registerVersion("Audit", 3);**  // <---- Complaining about this
InspectorBackend.registerCommand("Audit.setup", [{
    "name": "contextId",
    "type": "number",
    "optional": true
}], []);
InspectorBackend.registerCommand("Audit.run", [{
    "name": "test",
    "type": "string",
    "optional": false
}, {
    "name": "contextId",
    "type": "number",
    "optional": true
}], ["result", "wasThrown"]);
InspectorBackend.registerCommand("Audit.teardown", [], []);
InspectorBackend.activateDomain("Audit");

**Comment by AndrisBB** [comment]
Problem solved. Have not realised that I need exactly the same version of the Epiphany/Webikt on PC to connect web-inspector to the remote WPE instance on the device.
Hope this helps someone else.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
