### ISSUE TITLE
WPENetworkProcess causes 100% CPU load

### ISSUE THREAD

**Issue by DerArtem** [Metrological/WebKitForWayland#702]
Hello,

I am using wpewebkit with cog to display an web-based interface on an embedded device.
The web-interface is made with VUE and connects via websocket to localhost to receive the data which it beeing displayed.

When the websocket-backend is running on the system and I start cog the WPENetworkProcess takes 100% CPU and the page loads forever. Sometimes it also loads correctly.

When the websocket-backend is not running the web-application is started correctly (with no data available). And later starting the websocket-backend then brings the correct data.

How can I troubleshoot the WPENetworkProcess to see what causes the problem?

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
