### ISSUE TITLE
WPEWebProcess crash with signature resolveRopeSlowCase8 due to SIGSEGV

### ISSUE THREAD

**Issue by pkumbh631** [Metrological/WebKitForWayland#705]
Hi,

WPEWebProcess crashed with signature resolveRopeSlowCase8 due to SIGSEGV
Please find the BT below and help me to resolve the issue

Crash Thread #0
Frame	Thread	Module	Source

#0	resolveRopeSlowCase8	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/build/DerivedSources/ForwardingHeaders/wtf/RefPtr.h:82 (0x0)
#1	resolveRope	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/JavaScriptCore/runtime/JSString.cpp:273 (0x7)
#2	toWTFString	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/build/DerivedSources/ForwardingHeaders/JavaScriptCore/JSString.h:545 (0x7)
#3	setJSElementInnerHTML	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WebCore/bindings/js/JSDOMConvertStrings.h:56 (0x9)
#4	callCustomSetter	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/JavaScriptCore/runtime/CustomGetterSetter.cpp:41 (0x5)
#5	putInlineSlow	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/JavaScriptCore/runtime/JSObject.cpp:793 (0x1f)
#6	llint_slow_path_put_by_id	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/JavaScriptCore/runtime/JSObjectInlines.h:245 (0xd)
#7	libWPEWebKit-0.1.so.2.2.1@0x144ac43	libWPEWebKit-0.1.so.2.2.1	
#8	consoleLogWithLevel	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/JavaScriptCore/runtime/ConsoleObject.cpp:121 (0x15)
#9	@0xb14ff127		
Crash Thread #1
Frame	Thread	Module	Source

#0	libpthread-2.24.so@0xe0d4	libpthread-2.24.so	
#1	__pthread_cond_timedwait	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/futex-internal.h:205 (0x15)
#2	__pthread_cond_timedwait	libc-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/forward.c:162 (0xf)
#3	threadRunLoop	libWPEWebKit-0.1.so.2.2.1	/usr/include/c++/6.4.0/arm-rdk-linux-gnueabi/bits/gthr-default.h:871 (0x3)
#4	threadEntryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/bmalloc/bmalloc/Scavenger.cpp:359 (0x3)
#5	std::execute_native_thread_routine	libstdc++.so.6.0.22	/usr/src/debug/gcc-runtime/6.4.0-r0/gcc-6.4.0/build.arm-rdk-linux-gnueabi.arm-rdk-linux-gnueabi/arm-rdk-linux-gnueabi/libstdc++-v3/src/c++11/../../../../../../../../../../work-shared/gcc-6.4.0-r0/gcc-6.4.0/libstdc++-v3/src/c++11/thread.cc:83 (0x3)
#6	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#7	clone	libc-2.24.so	
Crash Thread #2
Frame	Thread	Module	Source

#0	__poll	libc-2.24.so	
#1	g_poll	libglib-2.0.so.0.4800.2	/usr/include/bits/poll2.h:46 (0x3)
#2	g_main_context_iterate	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4139 (0x7)
#3	g_main_loop_run	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4038 (0x9)
#4	run	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:96 (0x5)
#5	entryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/Function.h:56 (0x7)
#6	wtfThreadEntryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/ThreadingPthreads.cpp:215 (0x3)
#7	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#8	clone	libc-2.24.so	
Crash Thread #3
Frame	Thread	Module	Source

#0	__poll	libc-2.24.so	
#1	g_poll	libglib-2.0.so.0.4800.2	/usr/include/bits/poll2.h:46 (0x3)
#2	g_main_context_iterate	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4139 (0x7)
#3	g_main_loop_run	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4038 (0x9)
#4	run	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:96 (0x5)
#5	entryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/Function.h:56 (0x7)
#6	wtfThreadEntryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/ThreadingPthreads.cpp:215 (0x3)
#7	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#8	clone	libc-2.24.so	
Crash Thread #4
Frame	Thread	Module	Source

#0	__poll	libc-2.24.so	
#1	g_poll	libglib-2.0.so.0.4800.2	/usr/include/bits/poll2.h:46 (0x3)
#2	g_main_context_iterate	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4139 (0x7)
#3	g_main_loop_run	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4038 (0x9)
#4	run	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:96 (0x5)
#5	entryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/Function.h:56 (0x7)
#6	wtfThreadEntryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/ThreadingPthreads.cpp:215 (0x3)
#7	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#8	clone	libc-2.24.so	
Crash Thread #5
Frame	Thread	Module	Source

#0	ioctl	libc-2.24.so	
#1	NEXUS_Platform_P_UnmapMemory	libnexus.so	
#2	_fini	libnexus.so	
#3	_fini	libnexus.so	
#4	NEXUS_Platform_P_UnmapMemory	libnexus.so	
#5	NEXUS_P_Base_Statistics_StackAggregate_Update	libnexus.so	
#6	@0xfffe		
#7	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
Crash Thread #6
Frame	Thread	Module	Source

#0	libpthread-2.24.so@0xe0d4	libpthread-2.24.so	
#1	__pthread_cond_timedwait	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/futex-internal.h:142 (0x11)
#2	__pthread_cond_timedwait	libc-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/forward.c:162 (0xf)
#3	BKNI_WaitForGroup	libnexus.so	
#4	_fini	libnexus.so	
#5	_fini	libnexus.so	
#6	_fini	libnexus.so	
#7	_fini	libnexus.so	
#8	_fini	libnexus.so	
#9	_fini	libnexus.so	
#10	_fini	libnexus.so	
#11	NEXUS_P_MapInit	libnexus.so	
#12	_dl_lookup_symbol_x	ld-2.24.so	/usr/src/debug/glibc/2.24-r0/git/elf/dl-lookup.c:833 (0x2d)
#13	_fini	libnexus.so	
#14	_fini	libnexus.so	
#15	_fini	libnexus.so	
#16	_fini	libnexus.so	
#17	_fini	libnexus.so	
#18	_dl_fixup	ld-2.24.so	/usr/src/debug/glibc/2.24-r0/git/elf/dl-runtime.c:111 (0x23)
#19	@0xb2f182ee		
#20	NEXUS_P_Base_ExternalScheduler_Step	libnexus.so	
#21	NEXUS_Platform_P_UnmapMemory	libnexus.so	
#22	NEXUS_P_Base_Statistics_StackAggregate_Update	libnexus.so	
#23	@0xfffe		
#24	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
Crash Thread #7
Frame	Thread	Module	Source

#0	libpthread-2.24.so@0xe0d4	libpthread-2.24.so	
#1	__pthread_cond_timedwait	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/futex-internal.h:205 (0x15)
#2	__pthread_cond_timedwait	libc-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/forward.c:162 (0xf)
#3	timedWait	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/ThreadingPthreads.cpp:556 (0x3)
#4	parkConditionallyImpl	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/ParkingLot.cpp:597 (0x7)
#5	sleep	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/ParkingLot.h:85 (0x3)
#6	call	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/linux/MemoryPressureHandlerLinux.cpp:182 (0x7)
#7	entryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/Function.h:56 (0x7)
#8	wtfThreadEntryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/ThreadingPthreads.cpp:215 (0x3)
#9	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#10	clone	libc-2.24.so	
Crash Thread #8
Frame	Thread	Module	Source

#0	__poll	libc-2.24.so	
#1	_dbus_poll	libdbus-1.so.3.14.7	/usr/include/bits/poll2.h:46 (0x3)
#2	socket_do_iteration	libdbus-1.so.3.14.7	/usr/src/debug/dbus/1.10.10-r0/dbus-1.10.10/dbus/dbus-transport-socket.c:1167 (0xd)
#3	_dbus_transport_do_iteration	libdbus-1.so.3.14.7	/usr/src/debug/dbus/1.10.10-r0/dbus-1.10.10/dbus/dbus-transport.c:1001 (0x5)
#4	_dbus_connection_do_iteration_unlocked	libdbus-1.so.3.14.7	/usr/src/debug/dbus/1.10.10-r0/dbus-1.10.10/dbus/dbus-connection.c:1227 (0x9)
#5	_dbus_connection_read_write_dispatch	libdbus-1.so.3.14.7	/usr/src/debug/dbus/1.10.10-r0/dbus-1.10.10/dbus/dbus-connection.c:3706 (0xb)
#6	dbus_connection_read_write_dispatch	libdbus-1.so.3.14.7	/usr/src/debug/dbus/1.10.10-r0/dbus-1.10.10/dbus/dbus-connection.c:3774 (0x5)
#7	dispatchThread	libIARMBus.so.0.0.0	/usr/src/debug/iarmbus/1.99+git2e47924142-r0/git/core/libIARM-dbus.c:982 (0xb)
#8	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#9	clone	libc-2.24.so	
Crash Thread #9
Frame	Thread	Module	Source

#0	__poll	libc-2.24.so	
#1	g_poll	libglib-2.0.so.0.4800.2	/usr/include/bits/poll2.h:46 (0x3)
#2	g_main_context_iterate	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4139 (0x7)
#3	g_main_loop_run	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4038 (0x9)
#4	run	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:96 (0x5)
#5	entryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/Function.h:56 (0x7)
#6	wtfThreadEntryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/ThreadingPthreads.cpp:215 (0x3)
#7	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#8	clone	libc-2.24.so	
Crash Thread #10
Frame	Thread	Module	Source

#0	__poll	libc-2.24.so	
#1	g_poll	libglib-2.0.so.0.4800.2	/usr/include/bits/poll2.h:46 (0x3)
#2	g_main_context_iterate	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4139 (0x7)
#3	g_main_context_iteration	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:3905 (0xd)
#4	glib_worker_main	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:5676 (0x9)
#5	g_thread_proxy	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gthread.c:780 (0x5)
#6	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#7	clone	libc-2.24.so	
Crash Thread #11
Frame	Thread	Module	Source

#0	__poll	libc-2.24.so	
#1	g_poll	libglib-2.0.so.0.4800.2	/usr/include/bits/poll2.h:46 (0x3)
#2	g_main_context_iterate	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4139 (0x7)
#3	g_main_loop_run	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4038 (0x9)
#4	run	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:96 (0x5)
#5	entryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/Function.h:56 (0x7)
#6	wtfThreadEntryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/ThreadingPthreads.cpp:215 (0x3)
#7	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#8	clone	libc-2.24.so	
Crash Thread #12
Frame	Thread	Module	Source

#0	libpthread-2.24.so@0xe0d4	libpthread-2.24.so	
#1	do_futex_wait	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/futex-internal.h:205 (0x17)
#2	__new_sem_wait_slow	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/sem_waitcommon.c:282 (0x7)
#3	sem_timedwait	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/sem_timedwait.c:36 (0x3)
#4	display_thread_func	libv3ddriver.so	/mnt/jenkins/workspace/CXD01ANI-Yocto-Build/build-ciscoxid/tmp/work/ciscoxid-rdk-linux-gnueabi/broadcom-refsw/unified-17.3-r4.2/BSEAV/lib/gpu/v3d/driver/./interface/vcos/pthreads/vcos_platform.h:229 (0x7)
#5	vcos_thread_entry	libv3ddriver.so	/mnt/jenkins/workspace/CXD01ANI-Yocto-Build/build-ciscoxid/tmp/work/ciscoxid-rdk-linux-gnueabi/broadcom-refsw/unified-17.3-r4.2/BSEAV/lib/gpu/v3d/driver/interface/vcos/pthreads/vcos_pthreads.c:69 (0x3)
#6	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#7	clone	libc-2.24.so	
Crash Thread #13
Frame	Thread	Module	Source

#0	__poll	libc-2.24.so	
#1	g_poll	libglib-2.0.so.0.4800.2	/usr/include/bits/poll2.h:46 (0x3)
#2	g_main_context_iterate	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4139 (0x7)
#3	g_main_loop_run	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4038 (0x9)
#4	gdbus_shared_thread_func	libgio-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/gio/gdbusprivate.c:246 (0x3)
#5	g_thread_proxy	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gthread.c:780 (0x5)
#6	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#7	clone	libc-2.24.so	
Crash Thread #14
Frame	Thread	Module	Source

#0	libpthread-2.24.so@0xe0d4	libpthread-2.24.so	
#1	__pthread_cond_wait	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/futex-internal.h:88 (0x11)
#2	__pthread_cond_wait	libc-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/forward.c:149 (0xf)
#3	AampCacheHandler::AsyncCacheCleanUpTask	libaamp.so	/usr/src/debug/aamp/1.99+gitAUTOINC+95e68d3a71-r0/git/AampCacheHandler.cpp:311 (0x7)
#4	AampCacheHandler::AampCacheThreadFunction	libaamp.so	/usr/src/debug/aamp/1.99+gitAUTOINC+95e68d3a71-r0/git/AampCacheHandler.h:89 (0x3)
#5	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#6	clone	libc-2.24.so	
Crash Thread #15
Frame	Thread	Module	Source

#0	__poll	libc-2.24.so	
#1	g_poll	libglib-2.0.so.0.4800.2	/usr/include/bits/poll2.h:46 (0x3)
#2	g_main_context_iterate	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4139 (0x7)
#3	g_main_loop_run	libglib-2.0.so.0.4800.2	/usr/src/debug/glib-2.0/1_2.48.2-r0/glib-2.48.2/glib/gmain.c:4038 (0x9)
#4	run	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:96 (0x5)
#5	entryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/Function.h:56 (0x7)
#6	wtfThreadEntryPoint	libWPEWebKit-0.1.so.2.2.1	/usr/src/debug/wpe-webkit/2.22+gitAUTOINC+686cd2f7df-r0/git/Source/WTF/wtf/ThreadingPthreads.cpp:215 (0x3)
#7	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#8	clone	libc-2.24.so	
Crash Thread #16
Frame	Thread	Module	Source

#0	libpthread-2.24.so@0xe0d4	libpthread-2.24.so	
#1	__pthread_cond_wait	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/sysdeps/unix/sysv/linux/futex-internal.h:88 (0x11)
#2	__pthread_cond_wait	libc-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/forward.c:149 (0xf)
#3	WPEFramework::Core::Event::Lock	libWPEFrameworkCore.so.1.0.0	/usr/src/debug/wpeframework/1.99+gitAUTOINC+0105e8f8ed-r1/git/Source/core/Sync.cpp:841 (0xb)
#4	WPEFramework::Core::Event::Lock	libWPEFrameworkCore.so.1.0.0	/usr/src/debug/wpeframework/1.99+gitAUTOINC+0105e8f8ed-r1/git/Source/core/Sync.cpp:882 (0x3)
#5	WPEFramework::Core::StateTrigger<WPEFramework::Core::QueueType<WPEFramework::Core::ProxyType<WPEFramework::Core::IDispatchType<void> > >::enumQueueState>::WaitState	libocdm.so.1.0.0	/usr/src/debug/wpeframework/1.99+gitAUTOINC+0105e8f8ed-r1/git/Source/core/StateTrigger.h:118 (0x7)
#6	WPEFramework::Core::ThreadPool::Minion::Process	libocdm.so.1.0.0	/usr/src/debug/wpeframework/1.99+gitAUTOINC+0105e8f8ed-r1/git/Source/core/Queue.h:213 (0xb)
#7	WPEFramework::Core::ThreadPool::Executor::Worker	libocdm.so.1.0.0	/usr/src/debug/wpeframework/1.99+gitAUTOINC+0105e8f8ed-r1/git/Source/core/Thread.h:459 (0x5)
#8	WPEFramework::Core::Thread::StartThread	libWPEFrameworkCore.so.1.0.0	/usr/src/debug/wpeframework/1.99+gitAUTOINC+0105e8f8ed-r1/git/Source/core/Thread.cpp:170 (0x7)
#9	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#10	clone	libc-2.24.so	
Crash Thread #17
Frame	Thread	Module	Source

#0	__poll	libc-2.24.so	
#1	WPEFramework::Core::ResourceMonitorType<WPEFramework::Core::IResource, WPEFramework::Core::Void>::Worker	libWPEFrameworkCore.so.1.0.0	/usr/include/bits/poll2.h:46 (0xb)
#2	WPEFramework::Core::ResourceMonitorType<WPEFramework::Core::IResource, WPEFramework::Core::Void>::MonitorWorker::Worker	libWPEFrameworkCore.so.1.0.0	/usr/src/debug/wpeframework/1.99+gitAUTOINC+0105e8f8ed-r1/git/Source/core/ResourceMonitor.h:81 (0x7)
#3	WPEFramework::Core::Thread::StartThread	libWPEFrameworkCore.so.1.0.0	/usr/src/debug/wpeframework/1.99+gitAUTOINC+0105e8f8ed-r1/git/Source/core/Thread.cpp:170 (0x7)
#4	start_thread	libpthread-2.24.so	/usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458 (0xd)
#5	clone	libc-2.24.so

**Comment by guijemont** [comment]
There's a lot of inlined code behind the 2nd line of the backtrace (JSString.cpp:273), assuming I'm looking at the right revision. It's hard to diagnose anything from the stack trace alone, unfortunately, and I would need to be able to reproduce the crash to investigate it further.
Also, seeing the name of your source directory, it looks like you are using revision 686cd2f7df. This is an old revision of [wpe 2.22](https://github.com/WebPlatformForEmbedded/WPEWebKit/tree/wpe-2.22/), and we have included many fixes in this branch since then. Can you update to the latest version and see if the issue still reproduces?

If it does still reproduce, I will need more information so that I can attempt to reproduce it locally to investigate it:
 - Am I correct to assume this is happening on Arm 32-bits?
 - How much RAM is available for WPE?
 - How can I reproduce? What website or webapp does it trigger on? Can I have access to it?
 - How often does the crash happen?
 - What exact revision of WPE are you able to reproduce this on?

Thank you.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
