### ISSUE TITLE
WPEWebProcess (JavaScriptCore) crashes with SIGSEGV

### ISSUE THREAD

**Issue by simi-mathew** [Metrological/WebKitForWayland#714]
Webprocess crashes during hbomax playback with signature 'updateProfile'

Crash details
fingerprint: 06774f3d53fced52eb5e76f7d9b1a51b18344eeb0713f34b14cac96bf3224238
Appname: WPEWebProcess
Application: WPEWebProcess
crashed url: https://comcast.play.hbomax.com/?launchpoint=&query=&assetId=&assetType=&entityId=&sectionName=&contentUrl=&lmt=0&us_privacy=1-N- 

CallStack:
1 updateProfile ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/runtime/JSCellInlines.h:110
2 updateAllArrayPredictions ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/bytecode/CodeBlock.cpp:2619
3 finalizeUnconditionally ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/bytecode/CodeBlock.cpp:1410
4 forEachMarkedCell<JSC::Heap::finalizeMarkedUnconditionalFinalizers(CellSet&) [with CellType = JSC::CodeBlock; CellSet = JSC::IsoCellSet]::<lambda(JSC::HeapCell*, JSC::HeapCell::Kind)> > ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/heap/Heap.cpp:582
5 finalizeUnconditionalFinalizers ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/heap/Heap.cpp:580
6 runEndPhase ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1469
7 runCurrentPhase ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1185
8 implFunction ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1789
9 callWithCurrentThreadState ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/build/DerivedSources/ForwardingHeaders/wtf/ScopedLambda.h:59
10 collectInMutatorThread ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1801
11 stopIfNecessarySlow ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1770
12 stopIfNecessarySlow ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/heap/Heap.cpp:1744
13 collectIfNecessaryOrDefer ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/heap/HeapInlines.h:265
14 ~GCSafeConcurrentJSLocker ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/heap/HeapInlines.h:194
15 tryCacheGetByID ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/jit/Repatch.cpp:189
16 repatchGetByID ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/jit/Repatch.cpp:406
17 operationGetByIdOptimize ‎/usr/src/debug/wpe-webkit/2.22.2+gitAUTOINC+22d6522031-r0/git/Source/JavaScriptCore/jit/JITOperations.cpp:323 18 0xb1983cef

WPE Commit : [22d6522](https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/22d6522031250cdeb967101a0fa0cc91f190b84d)

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
