### ISSUE TITLE
Add 'ResizeObserver' support in 2.22

### ISSUE THREAD

**Issue by nrajan002c** [Metrological/WebKitForWayland#717]
Could you please backport 'ResizeObserver' support in 2.22.
We need this support for new apps.

**Comment by magomez** [comment]
I've just pushed 3e284c5675c9de1339d6c08add7a66e2a7e0b052 to the wpe-2.22 branch with the backport of the feature. We've done some testing and things seem to be ok, but please test it on your side as well and tell us if you find some issue.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
