### ISSUE TITLE
MediaElement currentTime property not fully compliant with the specification when readyState == HAVE_NOTHING

### ISSUE THREAD

**Issue by GenericEngineer** [Metrological/WebKitForWayland#722]
Setting the media element currentTime property when its readyState is HAVE_NOTHING, returns early with no action.

According to the specification this should get/set an internal default playback position which should be used when the media is not in a ready state.

From [https://html.spec.whatwg.org/#current-playback-position]

> The currentTime attribute must, on getting, return the media element's default playback start position, unless that is zero, in which case it must return the element's official playback position. The returned value must be expressed in seconds. On setting, if the media element's readyState is HAVE_NOTHING, then it must set the media element's default playback start position to the new value; otherwise, it must set the official playback position to the new value and then seek to the new value. The new value must be interpreted as being in seconds.

**Comment by eocanha** [comment]
It's true, the current WebKit implementation wasn't aware of _default playback start_ and just resorted to regular seeks in those cases. An implementation of the requested behavior has been pushed to [wpe-2.22](https://github.com/WebPlatformForEmbedded/WPEWebKit/commits/wpe-2.22)  as commit [8ccf6b1](https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/8ccf6b10daf158fad11831edcc059232f74a3346).

I've checked that it works properly in initial "changes of currentTime" (readyState=HAVE_NOTHING) in regular and MSE videos.

**Comment by eocanha** [comment]
The patch is also being upstreamed as https://bugs.webkit.org/show_bug.cgi?id=229605
