### ISSUE TITLE
WPEWebProcess Crash(JavaScriptCore) with deref signature due to SIGSEGV

### ISSUE THREAD

**Issue by CM112** [Metrological/WebKitForWayland#735]
Crash Scenario 1:
1)Hulu was in a still state, 
2)After exactly 4 hours app,  App is getting closed without any user interaction
3)WebProcess is crashed with deref signature after that
Crash Scenario 2 :
1)When a user tries to exit the app with the menu button 
2)After exiting the app WebProcess is crashed with deref signature 

WPE commit :
22d6522031250cdeb967101a0fa0cc91f190b84d

Callstack:

- [ [ 00 ] 0x168db550
[ 01 ] deref
[ 02 ] ~CodeBlock
[ 03 ] specializedSweep<true, (JSC::MarkedBlock::Handle::EmptyMode)0u, (JSC::MarkedBlock::Handle::SweepMode)0u, (JSC::MarkedBlock::Handle::SweepDestructionMode)1u, (JSC::MarkedBlock::Handle::ScribbleMode)0u, (JSC::MarkedBlock::Handle::NewlyAllocatedMode)1u, (JSC::MarkedBlock::Handle::MarksMode)0u, JSC::DefaultDestroyFunc>
[ 04 ] finishSweepKnowingHeapCellType<JSC::DefaultDestroyFunc>
[ 05 ] finishSweep
[ 06 ] sweep
[ 07 ] sweep
[ 08 ] sweep
[ 09 ] deleteUnmarkedCompiledCode
[ 10 ] finalize
[ 11 ] handleNeedFinalize
[ 12 ] handleNeedFinalize
[ 13 ] finishChangingPhase
[ 14 ] runEndPhase
[ 15 ] runCurrentPhase
[ 16 ] implFunction
[ 17 ] callWithCurrentThreadState
[ 18 ] collectInMutatorThread
[ 19 ] stopIfNecessarySlow
[ 20 ] waitForCollection
[ 21 ] collectSync
[ 22 ] collectNow
[ 23 ] garbageCollectNow
[ 24 ] releaseMemory
[ 25 ] performWork
[ 26 ] _FUN
[ 27 ] 0xb3f2b189
[ 28 ] 0xb59d9a3f
[ 29 ] derefGPtr<_GClosure>
[ 30 ] run
[ 31 ] ChildProcessMain<WebKit::WebProcess, WebKit::WebProcessMain>
[ 32 ] __libc_start_main
[ 33 ] _start
[ 34 ] __libc_csu_init]

**Comment by CM112** [comment]
Is there any update on this issue?

**Comment by CM112** [comment]
[deref.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/7801920/deref.txt)
attached full stack trace for all threads, @woutermeek  Can you help check this?

**Comment by CM112** [comment]
We don't have an exact scenario  to reproduce this issue, It is mostly happening in arm devices

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
