### ISSUE TITLE
Image not rendered on accelerated 2d canvas under specific conditions

### ISSUE THREAD

**Issue by bboczar** [Metrological/WebKitForWayland#738]
We have encountered some issues with painting on accelerated 2d canvas with cairo. Basically, when display property of the canvas is changed to 'none' and later on to something different, like 'block', canvas itself is visible (it occupy space) but image is no longer rendered on this canvas.

I have prepared example: https://bboczar.github.io/stb/canvas-display-property/index.html

Prerequisites:
- accelerated 2d canvas functionality is enabled

Steps to reproduce:
- draw something on canvas (use 'paint' buttons)
- change display property of the canvas to 'none' (use 'play' button to hide canvas and play video)
- change display property of the canvas to 'block' (use 'stop' button to hide video and show canvas)
- try to paint again

Expected:
- drawing on canvas works OK

Actual
- drawing on canvas have no effect

This issue is not visible when accelerated 2d canvas is disabled
Canvas can be "recovered" by recreating image buffer, for example when size is changed (use 'changeCanvasWidth' buttons)

Also noticed strange behavior, that first draw on canvas makes no effect (almost like drawn content was flushed to invisible buffer), second one makes image to appear - is this expected?

**Comment by magomez** [comment]
I've just pushed d852c5036ef93b9e469203adbdca5eb63bc6a4b8 to the wpe-2.22 branch, that should fix the issue. Please try that it fixes it for your case and close this if everything is working properly.

**Comment by bboczar** [comment]
Looks like issue is fixed, however we will perform some more tests before closing this issue. Thanks!

**Comment by magomez** [comment]
@bboczar is this issue fixed? could we close it?

**Comment by bboczar** [comment]
Sorry, I forgot about this one. Yes, issue could be closed. Thank you for your support!
