### ISSUE TITLE
WPEWebProcess Crash(JavaScriptCore) with clobberize signature due to SIGFPE 

### ISSUE THREAD

**Issue by CM112** [Metrological/WebKitForWayland#747]
Crash Scenario: 
This hang crash happens while launching apps, iheart radio, IPTV, startup screen, ....
It is not specific to any app 

WPE commit :
22d6522031250cdeb967101a0fa0cc91f190b84d

Callstack:
[ 00 ] clobberize<JSC::DFG::AbstractHeapOverlaps, JSC::DFG::AbstractHeapOverlaps, JSC::DFG::NoOpClobberize>
[ 01 ] accessesOverlap
[ 02 ] handleNode
[ 03 ] runAndLog<JSC::DFG::StrengthReductionPhase>
[ 04 ] performStrengthReduction
[ 05 ] compileInThreadImpl
[ 06 ] compileInThread
[ 07 ] compile
[ 08 ] operationOptimize
[ 09 ] 0x6f420d90
[ 10 ] llint_slow_path_call
[ 11 ] 0x76462420
[ 12 ] setEntrypoint
[ 13 ] 0xfffffff3

**Comment by CM112** [comment]
As @woutermeek  suggests , Tried Disabling DFG jit as a workaround, But it affects performance of the device,
@woutermeek  can you help in fix this

**Comment by CM112** [comment]
Also this issue is mostly seen mips platform

**Comment by guijemont** [comment]
> As @woutermeek suggests , Tried Disabling DFG jit as a workaround, But it affects performance of the device, @woutermeek can you help in fix this

Do you mean the issue does reproduce any more with DFG disabled? That's interesting information in itself.

Are you able to provide a more complete backtrace (with source code line numbers) like in #759, or ideally, like I recently asked there (`thread apply all bt full`). Thanks!

**Comment by CM112** [comment]
I am able to reproduce the issue in 1/60 times  but frequent hangs are detected, When I disable DFG jit After a long try, I saw a crash, But I'm not able to resolve the bt(so not sure about the exact issue is reproduced or not), I saw  less frequent hangs detected, Maybe the frequency is reduced by disabling jit
[747.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/7802435/747.txt)

**Comment by CM112** [comment]
hi @guijemont  any updates on this tickets , I can see still the issue is happening in the field

**Comment by guijemont** [comment]
> hi @guijemont any updates on this tickets , I can see still the issue is happening in the field

Unfortunately, I cannot do anything without either a way for me to reproduce the issue, a more complete backtrace (`thread apply all bt full`) and/or a core file and associated build/source.

**Comment by jacek-skiba-red** [comment]
As disabling DFG is causing performance issues (but reduces crash reproduction), maybe try to adjust different parameter related to DFG: `bytecodeRangeToDFGCompile`. Setting environment variable to eg. `JSC_bytecodeRangeToDFGCompile=1:200` will limit bytecode range for DFG compilation. 

That parameter solved one of our issue in my STB project, where we also had JSC crash on some specific platform. 

Using `jitWhitelist / dfgWhitelist` also can help to norrow down issue when JSC backtrace is unreadable.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
