### ISSUE TITLE
BBC ACT testsuite support [question]

### ISSUE THREAD

**Issue by jacek-skiba-red** [Metrological/WebKitForWayland#748]
Is WPE (especially branch WPE2.22) officially supporting BBC ACT testcases (https://certification.bbctvapps.co.uk/act/portal/)? 
If the answer is "Yes", then which version is supported (1.14 / 1.15)?
If the answer is "No", then why ACT testsuite is not added to WPE CI suite?

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
