### ISSUE TITLE
html video element with src="udp://0.0.0.0:5000" never starts playing

### ISSUE THREAD

**Issue by russdill** [Metrological/WebKitForWayland#752]
I'm trying to render a video source that's being supplied via udp in the most direct way possible. The following works:

`gst-launch-1.0 playbin uri=udp://0.0.0.0:5000 video-sink=glimagesink`

But when using src="udp://0.0.0.0:5000" in a video element with cog *almost* works. A UDP port gets opened and bind gets called but the pipeline never moves past the PAUSED state. I've tried with autoplay and with controls and pressing play. I've tested with cog 0.13.1 and wpewebkit 2.35.1.

Is this something that's supposed to work? It would certainly be awesome if it did.

**Comment by woutervanh** [comment]
Hi russdill,
There's something wrong with playing network content
Following patch will fix this behaviour:
```
a/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp b/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
index b6911dff7994..ba5c2412f796 100644
--- a/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
+++ b/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp
@@ -2348,8 +2348,7 @@ void MediaPlayerPrivateGStreamer::updateStates()
         else if (m_currentState == GST_STATE_PLAYING)
             m_isPaused = false;
-        if (!m_isPaused && m_playbackRate)
-            changePipelineState(GST_STATE_PLAYING);
+        changePipelineState(GST_STATE_PLAYING);
         m_networkState = MediaPlayer::NetworkState::Loading;
         break;

```

**Comment by russdill** [comment]
Working great with this patch, thanks so much.

**Comment by Steffen-Rumler** [comment]
This patch looks essential for video streaming.
But it seems the patch was never incorporated to official WPEWebkit releases?

**Comment by philn** [comment]
Right. See https://bugs.webkit.org/show_bug.cgi?id=227904
