### ISSUE TITLE
Use of noncompositedwebgl

### ISSUE THREAD

**Issue by cuttlfish** [Metrological/WebKitForWayland#784]
We are observing that when this flag is set true in RDK environment, general memory bandwidth usage goes way up. The graphics core is 3 times more busy as well when drawing a simple lightning app that is mostly static compare to when this flag is set to false. Simple pages like google.com does not exhibit such behavior. Is this to be expected? What is the purpose of this flag. Thanks

**Comment by jacek-skiba-red** [comment]
Noncomposited mode disables the render loop for the DOM tree and CPU cycles are saved with that. This mode should be enabled only for apps which use only WebGL (eg. [Lightning framework](https://lightningjs.io/docs/#/what-is-lightning/index)) for apps rendering. This mode is not working with HTML5-based apps. 
                                               
Noncomposited mode is one of the features which is only present in WPE. Functionallity due ti it's "embeeded nature" is not ported to Webkit.

@cuttlfish on which hardware platform you see this issue?

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
