### ISSUE TITLE
Webprocess crash with signature "executeCall" after launching paramount plus app

### ISSUE THREAD

**Issue by antishantony** [Metrological/WebKitForWayland#788]
This issue is seen in few device models. 
It is mainly happening during paramount plus app. Issue is seen in hulu and amazon also but very less.

In most of the devices this crash is happening just after launching the app. Issue occurs in wpe-2.22. 
[5fe9dea5.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8088775/5fe9dea5.txt)
[61b78650.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8088784/61b78650.txt)

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
