### ISSUE TITLE
[wpe-2.28]  createImageBitmap doesn't work with accelerated 2d canvas

### ISSUE THREAD

**Issue by emutavchi** [Metrological/WebKitForWayland#793]
We observe that Lightning apps don't look right in wpe-2.28 with accelerated canvas enabled('-DENABLE_ACCELERATED_2D_CANVAS=ON'). can be reproduced with: https://github.com/rdkcentral/Lightning-VOD-example. 

Initial investigation suggests that createImageBitmap doesn't work with accelerated 2d canvas on

**Comment by magomez** [comment]
I've just pushed 6197d5de13b17115ebe3d6d269c6734529c87a7f that should fix this.

@emutavchi , please, could you verify and close this if it's fixed? Thanks

**Comment by emutavchi** [comment]
https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/6197d5de13b17115ebe3d6d269c6734529c87a7f works for us. I'm closing this issue
