### ISSUE TITLE
Unable to call classes in webkit from application

### ISSUE THREAD

**Issue by madanagopalt** [Metrological/WebKitForWayland#8]
Hi,
Is it not possible to create objects for  classes for WebInspector or any class inside WebKit2.This is because, i am seeing the symbols are seen local within objdump of generated libWPE.so file.Do i need to add new C API, inorder for application to speak with webkit?. Please let me know.

Regards,
Madan

**Comment by madanagopalt** [comment]
Or, do we have anyway to export the symbols from .so file to external application, so it can be linked. Thanks.

Regards,
Madan

**Comment by philn** [comment]
why are you trying to do such thing? The WebInspector symbols are meant to remain private.
