### ISSUE TITLE
[wpe-2.28] "playing" event is missing on seek

### ISSUE THREAD

**Issue by varumugam123** [Metrological/WebKitForWayland#816]
Hi @eocanha, in wpe-2.22 branch we identified an issue in the way playing event is sent and fixed by going back the way it was before https://bugs.webkit.org/show_bug.cgi?id=183383. Please refer https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/700

We need the same change cherry-picked here in wpe-2.28 as the same issue occurs here also. Could you please help?

**Comment by eocanha** [comment]
This issue can be closed, since pull request #819 has been merged.
