### ISSUE TITLE
Memory pressure handler not releasing memory

### ISSUE THREAD

**Issue by d21d3q** [Metrological/WebKitForWayland#826]
## the problem

I am using [`meta-webkit` from Igalia](https://github.com/Igalia/meta-webkit) which uses wpe 2.28. 

I am observing memory leak. I tried to limit memory by: 
```
[Service]
Type=simple
Environment=WPE_BCMRPI_TOUCH=1
Environment=WPE_RAM_SIZE=200m
Environment=WEBKIT_DEBUG="MemoryPressure=debug"
Environment=WPE_POLL_MAX_MEMORY="databaseprocess:50m,WPENetworkProcess:100m,WPEWebProcess:100m,rpcprocess:50m"
ExecStart=/usr/bin/cog --enable-page-cache=false --enable-offline-web-application-cache=false http://127.0.0.1:8080
Restart=on-failure
```

I can see in logs that Memory Pressure is firing:
```
Apr 06 20:02:47 touch-app cog[5873]: <http://127.0.0.1:8080/> Loading...
Apr 06 20:02:54 touch-app cog[5873]: <http://127.0.0.1:8080/#/> Loaded successfully.
Apr 07 09:35:21 touch-app WPEWebProcess[5888]: Memory usage policy changed: Unrestricted -> Conservative
Apr 07 09:35:21 touch-app WPEWebProcess[5888]: Memory pressure relief: Total: res = 161665024/160993280/-671744, res+swap = 210382848/209960960/-421888
Apr 07 09:35:51 touch-app WPEWebProcess[5888]: Memory usage policy changed: Conservative -> Unrestricted
Apr 07 10:38:22 touch-app WPEWebProcess[5888]: Memory usage policy changed: Unrestricted -> Conservative
Apr 07 10:38:22 touch-app WPEWebProcess[5888]: Memory pressure relief: Total: res = 161988608/161787904/-200704, res+swap = 210956288/210755584/-200704
Apr 07 10:38:52 touch-app WPEWebProcess[5888]: Memory usage policy changed: Conservative -> Unrestricted
Apr 07 11:05:22 touch-app WPEWebProcess[5888]: Memory usage policy changed: Unrestricted -> Conservative
Apr 07 11:05:22 touch-app WPEWebProcess[5888]: Memory pressure relief: Total: res = 161902592/160370688/-1531904, res+swap = 210874368/209342464/-1531904
Apr 07 11:05:52 touch-app WPEWebProcess[5888]: Memory usage policy changed: Conservative -> Unrestricted
```
but memory usage keeps increasing which leads to system freeze after two days (on rpi). This is last capture of tmux before ssh session died:
<img width="803" alt="wpememory" src="https://user-images.githubusercontent.com/490844/162167643-acf5852d-ee47-4a83-a213-f24fd9c36827.png">

Previously I've been using chromium (on rpi) and it could run forever, also leaving the same website opened on desktop doesn't result in such memory consumption.

App running in browser is SPA, Vue, it receives some data over websocket, and it seems that the more data it receives, the sooner it crashes. (However I am not 100% sure about it, will confirm).

Right after startup memory reported by `systemctl status` is around 45M, 

## questions
* how WPE_POLL_MAX_MEMORY is supposed to work? Is it tied to GC? 
* how would you suggest to debug it? building it with [`remote-inspector`](https://github.com/Igalia/meta-webkit/blob/10c67660e1448eb580bebdab37f2b7849b2ca609/recipes-browser/wpewebkit/wpewebkit.inc#L83=) might be the way to go?

**Comment by magomez** [comment]
I'm afraid you're using the wrong WPE recipe.
The one that you're using (Igalia one) uses a WPE version that doesn't have support for the WPE_RAM_SIZE env var, or to control the MemoryPressureHandler limits through the WPE_POLL_MAX_MEMORY env var. In order to use those features, you should build WPE from the WebPlatformForEmbedded recipe (https://github.com/WebPlatformForEmbedded/meta-wpe).

> how WPE_POLL_MAX_MEMORY is supposed to work? Is it tied to GC?

Yes. MemoryPressureHandler measures every some seconds the amount of memory that's being used by the process. If the memory is close to that limit, the process tries to release memory to stay inside the limit. In order to release memory, some caches are cleaned, some object pools are emptied, and GC can be performed.

**Comment by d21d3q** [comment]
Thanks!

I assumed that both projects use same source, but wrapped differently... 

Do you think that as a workaround (without switching to `meta-wpe`) patching [this place](https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/289f55ffafa03461d568a16bd177022781ce77ed/Source/WTF/wtf/MemoryPressureHandler.cpp#L123=) (which is shared in both repos) 
```
    const size_t baseThresholdForPolicy = std::min(3 * GB, ramSize());
```
to something like
```
    const size_t baseThresholdForPolicy = std::min(3 * GB, ramSize() * 0.5);
```
could trigger cleanup earlier?
