### ISSUE TITLE
feature: Populate MediaDevices with locally configured gstreamer pipelines

### ISSUE THREAD

**Issue by russdill** [Metrological/WebKitForWayland#828]
The gstreamer support in WPEWebKit is a really killer feature, and the playbin interface covers most use cases. However, sometimes a little more fine grain control over pipelines is required, such as when raw video packets are being received via a local network interface, or some other source. Adding the ability for the server to specify a client gstreamer pipeline seems rather nonsensical though and would be a major security issue.

Providing a list of gstreamer pipelines to be used as MediaDevices seems like a good solution to this. The list could include both input and output pipelines and would be ultimately configured by a config file for the browser or passed via command line to the browser before being provided to WPEWebKit. They could then be enumerated with MediaDevices.enumerateDevices().

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
