### ISSUE TITLE
CoordinatedGraphicsScene::assignImageBackingToLayer crash in wpe 2.22

### ISSUE THREAD

**Issue by nrajan002c** [Metrological/WebKitForWayland#830]
When we try to load "https://cd-stage.web.plus.espn.com/espn/comcast/xclass/index.html" with nonCompositedWebGLEnabled option, it is crashing in CoordinatedGraphicsScene.

Stack trace is below,
Thread 21 (crashed)
 0  libWPEWebKit-0.1.so.2.2.4!WebKit::CoordinatedGraphicsScene::assignImageBackingToLayer(WebCore::TextureMapperLayer*, unsigned long long) [CoordinatedGraphicsScene.cpp : 433 + 0x0]
 1  libWPEWebKit-0.1.so.2.2.4!WebKit::CoordinatedGraphicsScene::setLayerState(unsigned int, WebCore::CoordinatedGraphicsLayerState const&, WebKit::CoordinatedGraphicsScene::CommitScope&) [CoordinatedGraphicsScene.cpp : 210 + 0xb]
 2  libWPEWebKit-0.1.so.2.2.4!WebKit::CoordinatedGraphicsScene::applyStateChangesAndNotifyVideoPosition(WTF::Vector<WebCore::CoordinatedGraphicsState, 0u, WTF::CrashOnOverflow, 16u> const&) [CoordinatedGraphicsScene.cpp : 531 + 0x11]
 3  libWPEWebKit-0.1.so.2.2.4!WebKit::ThreadedCompositor::renderNonCompositedWebGL() [ThreadedCompositor.cpp : 242 + 0x7]
 4  libWPEWebKit-0.1.so.2.2.4!WebKit::ThreadedCompositor::renderLayerTree() [ThreadedCompositor.cpp : 250 + 0x3]
 5  libWPEWebKit-0.1.so.2.2.4!WebKit::CompositingRunLoop::updateTimerFired() [Function.h : 56 + 0x5]
 6  libWPEWebKit-0.1.so.2.2.4!_FUN [RunLoopGLib.cpp : 170 + 0x3]
 7  libglib-2.0.so.0.6200.4!g_main_context_dispatch [gmain.c : 3216 + 0x5]
 8  libglib-2.0.so.0.6200.4!g_main_context_iterate [gmain.c : 3958 + 0x3]
 9  libglib-2.0.so.0.6200.4!g_main_loop_run [gmain.c : 4152 + 0x9]
10  libWPEWebKit-0.1.so.2.2.4!WTF::RunLoop::run() [RunLoopGLib.cpp : 96 + 0x5]
11  libWPEWebKit-0.1.so.2.2.4!WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) [Function.h : 56 + 0x7]
12  libWPEWebKit-0.1.so.2.2.4!wtfThreadEntryPoint [ThreadingPthreads.cpp : 215 + 0x3]
13  libpthread-2.31.so!start_thread [pthread_create.c : 477 + 0x1]
14  libc-2.31.so!clone + 0x3a

If I disable the 'nonCompositedWebGL' flag, this crash is not happening.
This issue is 100% reproducible in Arris xi6 and Platco devices.

**Comment by nrajan002c** [comment]
This crash is happened when we enable 'nonCompostedWebGL' flag for non-lightning apps.
Please ignore this issue.

**Comment by nrajan002c** [comment]
Crash shouldn't happen even we load non-lightning apps with 'non-composistedWebGL' flag enabled.

**Comment by magomez** [comment]
I've just pushed 438caeacda1e915777db1df2c136b5f72b7a1603 to the wpe-2.22 branch that should fix this. The crash is gone, despite the page doesn't load anything besides a blank page. Please verify that the fix works for you as well.

**Comment by nrajan002c** [comment]
@magomez I tested the above patch. I am seeing black screen when I launch html app with 'nonCompositedWebGL' flag.
And I am not seeing the crash.
I will close this issue. Thanks.
