### ISSUE TITLE
The playback starts playing by itself after manual pause by user

### ISSUE THREAD

**Issue by przemyslaw-gorszkowski-red** [Metrological/WebKitForWayland#831]
It happens at the beginning of the playback  (type of playback: progressive). Observed on applications like CNN or Euronews. 
1. Start one of the content with progressive type of stream (mp4 file).
2. Just after it starts to play, pause it manually(videoElement.pause() or via video controls)
3. sometimes after a few seconds it starts to play by itself

The problem can be observed in file: 

https://user-images.githubusercontent.com/47318228/163565868-be61fd4b-e5a8-4ffb-b8b6-4c901fcd2fc6.mp4

Logs from the problematic case:
```
 0:00:54.206494532    11    0x276a0 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2075:updateStates: [Buffering] Complete.
 0:00:54.934967716    11    0x276a0 INFO       webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:690:play:<play> Start playback
// manual pause the playback
 0:00:55.566245159    11    0x276a0 INFO       webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:628:changePipelineState:<play> from PLAYING to PAUSED (pending VOID_PENDING)
 0:00:55.598478752    11    0x276a0 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2083:updateStates: [Buffering] Stream still downloading.
 0:00:55.731645788    11    0x276a0 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:1452:handleMessage: Message buffering received from element queue2-0
// receiving the buffer is full from the queue2
 0:00:55.731811418    11    0x276a0 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:1631:processBufferingStats: [Buffering] Buffering: 100%.
 0:00:55.731849825    11    0x276a0 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2041:updateStates: State: PAUSED, pending: VOID_PENDING
 0:00:55.731872936    11    0x276a0 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2075:updateStates: [Buffering] Complete.
// restart the playback automatically
 0:00:55.787017122    11    0x276a0 INFO       webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:690:play:<play> Start playback
 
// manual pause the playback
HTMLMediaElement::pause(0xaddd3800)
 0:00:57.107898600    11    0x276a0 INFO       webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:628:changePipelineState:<play> from PLAYING to PAUSED (pending VOID_PENDING)
 0:00:57.393543414    11    0x276a0 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2083:updateStates: [Buffering] Stream still downloading.
// receiving the buffer is full from the queue2
 0:00:57.448223155    11    0x276a0 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:1631:processBufferingStats: [Buffering] Buffering: 100%.
 0:00:57.448270710    11    0x276a0 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2075:updateStates: [Buffering] Complete.
// restart the playback automatically
 0:00:57.510602821    11    0x276a0 INFO       webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:690:play:<play> Start playback
```

**Comment by przemyslaw-gorszkowski-red** [comment]
After more deeply analysis it seems that the unpausing happens because applications(CNN, Euronews) reacts on "canplay" event, which is generated when WPE receives the GST_MESSAGE_BUFFERING with buffer level equal to 100%(in consequence of changing readyState):

1. Receiving the GST_MESSAGE_BUFFERING: https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp#L1467
2. Calling "updateStates" if the buffering level is 100%: https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp#L1731
3. calling "readyStateChanged" (readyState change to 'HaveEnoughData'): https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/MediaPlayerPrivateGStreamer.cpp#L2358
4. schedule event "canPlay": https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/html/HTMLMediaElement.cpp#L2586

**Comment by eocanha** [comment]
At first, I couldn't reproduce the issue straight away just with user interaction (the video loads too fast here, and even if I restrict the network bandwidth, that's not enough to reproduce). Then I added some code to call HTMLMediaElement::pause() when "[Buffering] Stream still downloading" happens (like a fast user pressing pause at the right time) and could see the auto-continue issue described. I'm now debugging it.

**Comment by eocanha** [comment]
> After more deeply analysis it seems that the unpausing happens because applications(CNN, Euronews) reacts on "canplay" event, which is generated when WPE receives the GST_MESSAGE_BUFFERING with buffer level equal to 100%(in consequence of changing readyState).

But, as I see it, that canplay event is properly generated. It just means that ["there's enough data to start playing (although not during much time)"](https://html.spec.whatwg.org/multipage/media.html#event-media-canplay). It the app "changes mind about wanting to pause" and decides to start playing in those conditions (or even if canplaythrough had been emitted), then it's a problem of the app.

At first, I suspected that there might be some pending code triggering the play() call, but the debugger showed that it's triggered from JavaScript (as you mention, likely by the canplay event handler, but I don't know for sure):

```
b6935811 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) en :?
...
b5f9c1ed WebCore::HTMLMediaElement::play(WebCore::DOMPromiseDeferred<void>&&) en :?
b5a2ec67 WebCore::jsHTMLMediaElementPrototypeFunctionPlay(JSC::ExecState*) en :?
b699c0f1 llint_entry en :?
b69960ad vmEntryToJavaScript en :?
b69358b1 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) en :?
```

At this point I don't think this is an issue with the HTMLMediaElement or the MediaPlayerPrivateGStreamer implementation, but an issue of the JavaScript player. Do you agree? Can this issue be closed?

**Comment by przemyslaw-gorszkowski-red** [comment]
It seems, as you mentioned, that this issue is rather on the app side(JavaScript player) which bases on the "canplay" event - starts the playback. The problem occurs on many applications (CNN, Euronews, Sunset), probably all of them base on the same js engine or something like this. 
Thanks for your investigation.
I close the ticket.
