### ISSUE TITLE
[JSC] Webprocess crash with linkPolymorphicCall signature de to SIGSEGV

### ISSUE THREAD

**Issue by CM112** [Metrological/WebKitForWayland#841]
This issue is mostly happening in MIPS devices around 95.91 % (pace xg2v2, Samsung xg2v2, arris xg1v1 ..)and the most affected app is amazon

Scenario:
While playing assets of amazon

wpe-commit:
22d6522031250cdeb967101a0fa0cc91f190b84d

full Stactrace:
[stacktrace.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8619721/stacktrace.txt)

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
