### ISSUE TITLE
Recording in Timelines tab doesn't work with HTTP WebInspector 

### ISSUE THREAD

**Issue by emutavchi** [Metrological/WebKitForWayland#843]
Steps:

- enable HTTP web inspector by exporting WEBKIT_INSPECTOR_HTTP_SERVER
- connect to RWI, select Timelines tab 
- try to start recording

Observed: nothing is changing, looks like no data is available. Similar works fine with native ('inspector://') inspector server

- http inspector
![Screenshot from 2022-05-04 16-17-00](https://user-images.githubusercontent.com/114908/166818940-ec4bd78a-d4b2-425b-b428-c3a89b203566.png)
- native
![Screenshot from 2022-05-04 16-14-32](https://user-images.githubusercontent.com/114908/166818942-2afaff50-e5a5-4529-a26a-cd07f9e8f221.png)

**Comment by magomez** [comment]
I've pushed 8f379305f7766f9ff7a56c799bf952a5fd5967c5 to the wpe-2.28 branch to fix this. Please verify that's working as expected and close this.

**Comment by emutavchi** [comment]
Works for me with latest 2.28:

![Screenshot from 2022-06-22 17-29-15](https://user-images.githubusercontent.com/114908/175141932-cac6fdd1-cbee-4b7f-b695-68f5f8febdbb.png)
