### ISSUE TITLE
[wpe-2.28] Google DAI & AppleTV+ assets doesn't work

### ISSUE THREAD

**Issue by varumugam123** [Metrological/WebKitForWayland#844]
With wpe-2.28 (f049f40), Google DAI test https://github.com/googleads/googleads-ima-html5-dai/tree/master/hls_js/simple doesn't work. Fails with "ParsingFailed" error.

@emutavchi  pointed that the issue is similar to https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/673. Cherry-picked this https://trac.webkit.org/changeset/266820/webkit change to wpe-2.28 and the Google test works.

However AppleTV+ still fails with "ParsingFailed" error when there is an ad at the start of the asset. On checking it is found that at times when the src_pad corresponding to ad video track is removed from AppendPipeline's qtdemux AppendPipeline doesn't try to connect the other remaining pad to app sink because there are more than one pads present. Please refer the attached log, this log was collected with fix from #673, towards the end 

```
May 04 11:56:45 hisense-a6gp WPEFramework[29540]: VIVEK-DBG [30682,3452]: AppendPipeline::connectDemuxerSrcPadToAppsinkFromStreamingThread (0x974ca4c8), got pad-added callback for srcpad-0x2182950(video_2), numPads-2
May 04 11:56:45 hisense-a6gp WPEFramework[29540]: VIVEK-DBG [30682,3452]: AppendPipeline::connectDemuxerSrcPadToAppsinkFromStreamingThread (0x974ca4c8), Only one stream per SourceBuffer is allowed! Ignoring stream 2 by adding a black hole probe.
May 04 11:56:45 hisense-a6gp WPEFramework[29540]: VIVEK-DBG [30682,3452]: AppendPipeline::connectDemuxerSrcPadToAppsinkFromStreamingThread (0x974ca4c8), got pad-added callback for srcpad-0x2182eb0(subtitle_1), numPads-3
May 04 11:56:45 hisense-a6gp WPEFramework[29540]: VIVEK-DBG [30682,3452]: AppendPipeline::connectDemuxerSrcPadToAppsinkFromStreamingThread (0x974ca4c8), Only one stream per SourceBuffer is allowed! Ignoring stream 3 by adding a black hole probe.
May 04 11:56:45 hisense-a6gp WPEFramework[29540]: VIVEK-DBG [30682,3452]: AppendPipeline::disconnectDemuxerSrcPadFromAppsinkFromAnyThread (0x974ca4c8), received pad-remove callback, disconnecting 0x2182d58(video_1) src-pad from app sink, numSrcPads-2 
```
[appletv-playback-with-ad-issue-log.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8629507/appletv-playback-with-ad-issue-log.txt)

At this point since there are 2 src pads available, the logic doesn't attempt to connect video_2 pad to appsink.

I tried a patch on top of #673, with it the AppleTV+ playback works fine. Please find the patch here 
[patch-for-appletv-playback-with-ad-issue.diff.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8629510/patch-for-appletv-playback-with-ad-issue.diff.txt)

Raising this issue as I saw the implementation in wpe-2.22 (3a5aeccf6a306a2cb8a4cddc6add36a3aa6a1c78) already has #673 and the issue is not observed without any further changes in Appendpipeline. But the wpe-2.22 AppendPipeline has a lot of differences compared to wpe-2.28.

**Comment by varumugam123** [comment]
Looks like gst also has some influence. Below are the combinations & observations
gst-1.10.4 + wpe-2.22 => AppleTV playback works
gst-1.18.5 + wpe-2.22 => No "ParsingFailed" error, but playback got stuck (I believe the pads are not connected properly)
gst-1.18.5 + wpe-2.28 => ParsingFailed error was observed. After adding #673 I observe similar behavior to the above combination

**Comment by eocanha** [comment]
I'm going to look into this.

**Comment by eocanha** [comment]
> I tried a patch on top of #673, with it the AppleTV+ playback works fine. Please find the patch here
> [patch-for-appletv-playback-with-ad-issue.diff.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8629510/patch-for-appletv-playback-with-ad-issue.diff.txt)

Is there any reason why you're not including the lines 830-853 from [the changeset](https://trac.webkit.org/changeset/266820/webkit) in your patch? It looks important to me, because I don't think connecting two pads with different caps (without any kind of renegotiation) can work. Do you know if the new pad (the one from the inserted ads) has different caps than the ones in the old pad?

**Comment by varumugam123** [comment]
Hi @eocanha, I didn't cherry-pick the patch directly, rather brought those portion from wpe-2.22 (https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/wpe-2.22/Source/WebCore/platform/graphics/gstreamer/mse/AppendPipeline.cpp#L1222).

I saw the comment regarding the possibility of caps not available in the removed & remaining pads, but was not sure how else we can identify the pad to be connected. That is one of the reason for creating this ticket.

**Comment by varumugam123** [comment]
>It looks important to me, because I don't think connecting two pads with different caps (without any kind of renegotiation) can work

I agree on the point that instead of checking just the video / audio type, we can compare the caps. 

> Do you know if the new pad (the one from the inserted ads) has different caps than the ones in the old pad?

I haven't seen so far with the assets I tried. But not sure if that would be the case always.

**Comment by eocanha** [comment]
I've split your patch in two, the original upstream patch and the new improvements. I've generalized the pad matching mechanism in the latest patch of branch https://github.com/WebPlatformForEmbedded/WPEWebKit/commits/eocanha/eocanha-debug-117

If this works for your use case, I guess we can merge it into wpe-2.28 trough a pull request to track the issue. Ok?

**Comment by varumugam123** [comment]
Sure @eocanha, Thanks. Let me try those changes and update.

**Comment by varumugam123** [comment]
Hi @eocanha, The commits work fine with slight modification on the second patch. It looks like post advertisement the actual content comes with cap (applications/x-cenc) which is different from the ad's cap (video/x-h265). Below are the changes I made
* Use capsMediaType() which takes care of handling "original-media-type", instead of directly getting the cap's structure name
* Remove remainingPadType which is not used
* Removed finding oldPeerPad again post identifying remainingPad
* Rearranged code a little bit to reuse identification of mediatype from pads

Attaching the patch :
[0001-MSE-GStreamer-Google-Dynamic-Ad-Insertion-DAI-suppor.patch.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8648941/0001-MSE-GStreamer-Google-Dynamic-Ad-Insertion-DAI-suppor.patch.txt)

**Comment by eocanha** [comment]
The proposed patch is fine. I've submitted it as PR https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/847, keeping your authorship.
