### ISSUE TITLE
[WPE-2.28] MSE MediaSourceDurationH264 test fail

### ISSUE THREAD

**Issue by emutavchi** [Metrological/WebKitForWayland#850]
It looks like edit lists still aren't handled correctly in MSE case. I tried with WPE-2.28 and GST 1.18. MediaSourceDurationH264 test is failing because the duration is above expected. here is the test link:

https://ytlr-cert.appspot.com/2021/main.html?&test_type=msecodec-test&tests=71&command=run#1652367110466

The same is failing with Epiphany (WebKitGTK 2.36.0) and GST 1.16 on my Ubuntu machine.

WPE-2.22 passes the test by clipping duration. I think WPE-2.22 behavior is not correct. WPE MSE should be applying edit list present in the content.

**Comment by eocanha** [comment]
I've been working on fixing this issue upstream in https://github.com/WebKit/WebKit/pull/1020, commit https://github.com/WebKit/WebKit/commit/bf69bf7f9edc397b39b76d90a861362b8182088a. I'm now working on porting it downstream.

**Comment by eocanha** [comment]
https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/878 is the port to wpe-2.28 of the patch.

This patch needs https://github.com/WebPlatformForEmbedded/buildroot/commit/2537f19b77757cf4d20e4b430e5099a4bf2d3487 on buildroot. An wpewebkit version dump has been done there.

**Comment by modeveci** [comment]
@eocanha, I have seen some related merges. If it is done, can you close this issue?
