### ISSUE TITLE
[WPE 2.24.3] Local Storage does't work with iframes 

### ISSUE THREAD

**Issue by ghost** [Metrological/WebKitForWayland#869]
Hi Team 
I am looking for a way to share some data among two domains that get opened on the same tab. I have tested this with normal browsers and managed to get it working using iframes and local storage. But that doesn't seem to be working with WPE. Looking for an alternative way to share data among domains from the front end. Any help is much appreciated. 

To test my initial approach, first, do this on a regular browser
Go to [Cross Storage Client ](https://aow.im/localtest/senderApp.html) (either type something on the text box before 4 secs or let it generate a random value)
Then go to [Cross Storage Hub](https://walkeralex.com/localtest/reciverApp.html). You should see that value(Might have to refresh if you had it already opened)

**Comment by jacek-skiba-red** [comment]
Hello @roshanaccedo 

Provided above testcases currently are not working, but I will try to describe general flow.

To share local storage data between iframes on different domains you need to use `postMessage()` method to enable cross-origin communication between iframes:
* use an iframe from your main domain - say `example.com`
* on each child iframe domain (eg. child.example.com), just do a postMessage to your parent iframe
* you need to setup a protocol of how to interpret your postMessage messages to talk to the parent `example.com` iframe

Above functionallity is done eg. by `Cross Domain Local Storage` library: https://github.com/ofirdagan/cross-domain-local-storage
Running it's test page on WPE2.22 (https://rawgit.com/ofirdagan/cross-domain-local-storage/master/app/index.html) works OK:
```
// save cookie
document.getElementById("keyInput").value = "1"
document.getElementById("valueInput").value = "2"
document.getElementsByTagName("button")[0].click()

// get cookie
document.getElementById("getInput").value = "1"
document.getElementsByTagName("button")[1].click()
```

In general, Safari based browsers does not allowed cross-domain cookies in iframe (where other browsers enable it).
@roshanaccedo: you have issue with local storage or with cookies?

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
