### ISSUE TITLE
[wpe-2.28] Image looses quality during scaling transition

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#884]
The **ACT-1279 | css-supports-transition-scale-image** test case from https://certification.bbctvapps.co.uk/act/client/ test suite (animation tests) fails. Interestingly it also fails on modern Safari 15.1 and modern firefox.
Screenshots:
![screen1](https://user-images.githubusercontent.com/1207385/173065363-b45368eb-03d9-465f-973a-ab8f18e538a4.png)
![screen2](https://user-images.githubusercontent.com/1207385/173065385-ea0cadc7-4dae-4504-b417-b686e7c8d176.png)

**Comment by magomez** [comment]
I've just pushed c57bfa7656248b61c5458feb98786b1337f091dc to the wpe-2.28 brach as a fix for this. Please verify and close this if everything is fine.

**Comment by Scony** [comment]
@magomez the https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/c57bfa7656248b61c5458feb98786b1337f091dc fixes the issue, thanks!
