### ISSUE TITLE
[wpe-2.28] No HTTP/2 push support (libsoup3, glib-networking 2.72)

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#888]
Despite having `libsoup3` and `glib-networking 2.72` it looks like WPE WebKit does not support HTTP/2 push i.e. the `ACT-1038 HTTP/2 push support` test case from `Device Tests` section from https://certification.bbctvapps.co.uk/act/client/ test suite is failing.

To run test just open https://certification.bbctvapps.co.uk/act/client on the WPE WebKit browser and pair it with https://certification.bbctvapps.co.uk/act/portal/ opened anywhere. After pairing, select test case and run it.

**Comment by woutermeek** [comment]
@Scony currently it is unclear wether apple will actually ever support this feature. I spoke with @emutavchi could you please check with BBC wether this a real hard requirement or if you could get an exception for it.

**Comment by Scony** [comment]
Sure, I'll check and let you know once I got something.

**Comment by Scony** [comment]
`This is still a MUST requirement in our list` - BBC.

**Comment by woutermeek** [comment]
@Scony I spoke with Anil on the topic, and a waiver will be requested. So we won't be implementing this.

**Comment by Scony** [comment]
@woutermeek the apple allegedly supports this issue now with Safari Version 15.6 (17613.3.9.1.5) - can we reopen this issue?
