### ISSUE TITLE
[wpe-2.28] No HTTP/2 stream prioritization (libsoup3, glib-networking 2.72)

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#889]
Despite having `libsoup3` and `glib-networking 2.72` it looks like WPE WebKit does not support HTTP/2 stream prioritisation i.e. the `ACT-1036 HTTP/2 stream prioritisation` test case from `Device Tests` section from https://certification.bbctvapps.co.uk/act/client/ test suite is failing.

To run test just open https://certification.bbctvapps.co.uk/act/client on the WPE WebKit browser and pair it with https://certification.bbctvapps.co.uk/act/portal/ opened anywhere. After pairing, select test case and run it.

**Comment by woutermeek** [comment]
@Scony this functionality is working upstream. We will backport it to 2.28.

**Comment by carlosgcampos** [comment]
The test doesn't work on main either, so there must be something else. I've tried and we get a socket timeout in libsoup. I've also tried with curl and wget2 and they both fail too, but works with chromium.

**Comment by carlosgcampos** [comment]
Could it be that this test requires push too?

**Comment by Scony** [comment]
@carlosgcampos no idea - I guess we'd need a push implemented to find out.

**Comment by carlosgcampos** [comment]
I've enabled push support in settings (even when it's not implemented) and the test still fails, but at least now it can continue without hanging, so it seems this test requires push support.

**Comment by carlosgcampos** [comment]
I've seen this in the test code: `'Response has been received from HTTP2 endpoint indicating push is not allowed, meaning stream priority support will never work`. So, I think what this is testing is prioritization of push promise frames and push support is required for this test.

**Comment by Scony** [comment]
> I've seen this in the test code: `'Response has been received from HTTP2 endpoint indicating push is not allowed, meaning stream priority support will never work`. So, I think what this is testing is prioritization of push promise frames and push support is required for this test.

yes, the dependency to HTTP/2 push was confirmed, so I think we can close this ticket.
