### ISSUE TITLE
[wpe-2.28] Contents are not rendered / cleared randomly on lightening apps

### ISSUE THREAD

**Issue by varumugam123** [Metrological/WebKitForWayland#892]
Sometimes when AppleTV is launched, the logo is not rendered (but later the actual home page comes up)... This issue was observed with wpe-2.28 (aaad8c5cdb8d2a7261ca53f17e718259deda528b).

Tried a sample which more or less recreates the issue... Try launching the html with noncompositedwebgl enabled. The logo is not rendered always. If the lightening js load is delayed (by replacing `window.onload = initLng;` with `window.onload = () => setTimeout(initLng, 0);` in `app.js` the logo is rendered always... Attaching the sample file here -
[missing_logo.zip](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/8909684/missing_logo.zip)

**Comment by varumugam123** [comment]
Hi @woutermeek may I know if there are any updates on this?

**Comment by magomez** [comment]
I hope I can look into this this week, or next one the later.

**Comment by varumugam123** [comment]
Log from the case where the sample app is not showing anything
```
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GraphicsContextGLOpenGL::GraphicsContextGLOpenGL (0x9f741000), count=1, window-0xae8a7ea0, destination-HostWindow, sharedContex-(nil)
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: NonCompositedGC3DLayer::NonCompositedGC3DLayer (0x9f746d00) - count=1, destination-directToWindow
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GLContextEGL::createContext, window-0xaba05940, display-0xae8da000
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GLContextEGL::createSharingContext, display-0xae8da000
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GLContextEGL::createSurfacelessContext, display-0xae8da000, sharingContext-(nil)
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GLContextEGL::GLContextEGL (0x9f740d60), count=1
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GLContextEGL::createWindowContext, window-0xaba05940, display-0xae8da000, sharingContext-0xa475e8
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GLContextEGL::GLContextEGL (0x9f740d80), count=2
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GLContextEGL::makeContextCurrent (0x9f740d80), prevContext-(nil)((nil))
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: WebGLRenderingContextBase::WebGLRenderingContextBase (0xaaf08700), count=1
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GraphicsContextGLOpenGL::reshape (0x9f741000), w-300, h-150
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GraphicsContextGLOpenGL::reshape (0x9f741000), w-1920, h-150
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GraphicsContextGLOpenGL::reshape (0x9f741000), w-1920, h-1080
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: [LightningApp]:webgl-splash.js:164 VIVEK-DBG: Rendered splash screen from webgl-splash.js
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GraphicsContextGLOpenGL::GraphicsContextGLOpenGL (0x9f731900), count=2, window-0xae8a7ea0, destination-HostWindow, sharedContex-(nil)
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: NonCompositedGC3DLayer::NonCompositedGC3DLayer (0x9f73a790) - count=2, destination-directToWindow
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: WebGLRenderingContextBase::WebGLRenderingContextBase (0xaaf08c40), count=2
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GraphicsContextGLOpenGL::reshape (0x9f731900), w-1920, h-1080
Jun 22 11:14:41 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GLContextEGL::swapBuffers (0x9f740d80)
```
Logo was rendered on the first WebGL context but before it is actually displayed (by doing swapBuffer), the second WebGL context is created by Lightning framework. This clears the previously rendered logo. When the swapBuffer is finally called it doesn't have any graphics data.

Another set of logs which shows that if swapBuffer() is called before the second context is created the logo is seen. 
```
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GraphicsContextGLOpenGL::~GraphicsContextGLOpenGL (0x9f731900), count=1
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: NonCompositedGC3DLayer::~NonCompositedGC3DLayer (0x9f73a790) - count=1
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GraphicsContextGLOpenGL::~GraphicsContextGLOpenGL (0x9f741000), count=0
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: NonCompositedGC3DLayer::~NonCompositedGC3DLayer (0x9f746d00) - count=0
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: WebGLRenderingContextBase::~WebGLRenderingContextBase (0xaaf08c40), count=1
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GraphicsContextGLOpenGL::GraphicsContextGLOpenGL (0x9d2a96c0), count=1, window-0xae8a7ea0, destination-HostWindow, sharedContex-(nil)
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: NonCompositedGC3DLayer::NonCompositedGC3DLayer (0x9d2898b0) - count=1, destination-directToWindow
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: WebGLRenderingContextBase::WebGLRenderingContextBase (0xaaf08c40), count=2
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GraphicsContextGLOpenGL::reshape (0x9d2a96c0), w-300, h-150
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GraphicsContextGLOpenGL::reshape (0x9d2a96c0), w-1920, h-150
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GraphicsContextGLOpenGL::reshape (0x9d2a96c0), w-1920, h-1080
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: [LightningApp]:webgl-splash.js:164 VIVEK-DBG: Rendered splash screen from webgl-splash.js
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: WebGLRenderingContextBase::~WebGLRenderingContextBase (0xaaf08700), count=1
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GLContextEGL::swapBuffers (0x9f740d80)
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GraphicsContextGLOpenGL::GraphicsContextGLOpenGL (0x9f776b40), count=2, window-0xae8a7ea0, destination-HostWindow, sharedContex-(nil)
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: NonCompositedGC3DLayer::NonCompositedGC3DLayer (0x9d252f50) - count=2, destination-directToWindow
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: WebGLRenderingContextBase::WebGLRenderingContextBase (0xaaf08700), count=2
Jun 22 11:16:36 hisense-a6gp WPEFramework[14843]: VIVEK-DBG [18186,18186]: GraphicsContextGLOpenGL::reshape (0x9f776b40), w-1920, h-1080
```
Delaying the second context creation happened randomly in the above case, but we can force it by deferring the lightning.js & app.js in the test app (or initializing lighting on a timer)

**Comment by magomez** [comment]
I haven't had time to look into this yet, but from this last comment I can tell you that having two webgl contents at the same time is not supported when using nonCompositedWebGL. There has to be a single context performing all the operations. In this case, you can't use a webgl context to render the logo and then create a second context for the lightning app. The lightning app is the one that should show the logo.

And why is it not supported? Because when using nonCompositedWebGL the glcontext is rendering directly to the native window, and it has to be the only one doing that. Having several contexts rendering to the same surface has undefined results because it's not meant to happen.

**Comment by magomez** [comment]
Just to be clear here, there's nothing to fix in wpe regarding this. The nonCompositedWebGL mode has this limitation of only allowing a single webgl context existing at every time (cause there can't be 2 contexts rendering to the same window at the same time). The applications need to be modified so the logo is painted by the lightning application, or if they want to use another webgl context to render the logo, they need to ensure that the context used for the logo is destroyed before the lightning one is created. They could create the first context, paint the logo, destroy the context, wait for a couple of seconds so the logo is visible and then create the lightning app and that would work.

But I don't really get why the apps are not already using lightning to paint the logo.

**Comment by magomez** [comment]
Ah, checking the code, I had forgotten that I had to add an extra limitation to nonCompositedWebGL. In some hardware I found that creating several contexts to paint on the same window (one after the other, not at the same time) wouldn't work (the rpi3 and I think there was some other as well). To overcome this I had to use the same glcontext for all of the webgl contexts, so no more contexts needed to be created.
This changes a bit what I explained about the behavior. Having several contexts at the same time is still not allowed, but not because there are several contexts painting to the same window, but because all of the webgl contexts use the same glcontext, so the changes that one webgl context does will affect the rendering of the other webgl context.

**Comment by magomez** [comment]
I've merged https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/894, but I'm not sure whether that's enough to fix this issue. And even if it's enough to fix it, I can't guarantee that there won't be other glitches happening because of the way the logo is being rendered.

**Comment by woutermeek** [comment]
@varumugam123 please see @magomez his comments. Either do not use nonCompositedWebGL or make sure they use Lightning (or at least the same context) to render the logo.
