### ISSUE TITLE
wpe-2.28 - window.close() doesn't work

### ISSUE THREAD

**Issue by emutavchi** [Metrological/WebKitForWayland#897]
it is blocked because app wasn't opened by JS:

```
> window.close()
[Warning] Can't close the window since it was not opened by JavaScript
```

wpe-2.22 has API (WKPreferencesSetAllowScriptsToCloseWindow) that allows configuring browser instances to allow apps to close the window. A similar is needed for wpe-2.28 with GLib APIs

**Comment by magomez** [comment]
@emutavchi , a fix for this was merged in the wpe-2.28 branch, could you verify and close this if everything's ok?
