### ISSUE TITLE
1920x1080 output

### ISSUE THREAD

**Issue by depili** [Metrological/WebKitForWayland#9]
WPE compiled by buildroot rpi2_wpe_minimal_defconfig yesterday (at afd955bf45e123dd459d0889f10712fd1fcc15a7 ) and a raspberry pi 2 running in 1080p resolution (hdm_group=1, hdmi_mode=16) results in a 1280x720 (720p) browser content "window", meaning that the page is displayed only in the top left corner of the screen, rest is black. Tried with our own material and the google front page with same results. A environment compiled on 2nd of September doesn't have this same issue.

**Comment by depili** [comment]
The same problem is still present when compiled with 32a42dc321b0efaab82975cf0ed3ecc662fdd858

**Comment by zdobersek** [comment]
With recent changes and the switch to WPELauncher the support for proper window sizing has been lost. I am working on fixing this today.

If it's convenient for you, you could work around this issue by changing the hard-coded sizes in WPELauncher and WPEView:
https://github.com/Metrological/WebKitForWayland/blob/master/Tools/WPELauncher/main.cpp#L125
https://github.com/Metrological/WebKitForWayland/blob/master/Source/WebKit2/UIProcess/API/wpe/WPEView.cpp#L44

**Comment by zdobersek** [comment]
This has been fixed with the addition of the wpe-launcher package[1] and bumping the wpe version[2].

[1] https://github.com/Metrological/buildroot/commit/7df6e9e4ae140b4b13b1b09ccd293ee800bd7b72
[2] https://github.com/Metrological/buildroot/commit/4794c57df8ead96d912390f9988c28f2156a12d8
