### ISSUE TITLE
[wpe-2.28] huge memory usage spike while compositing

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#904]
hi,

I've found pretty interesting memory usage spike during memory usage analysis in: https://sky.play.works/service/apps/portal/index.html
Here's how it looks like:
![Screenshot from 2022-07-05 10-36-38](https://user-images.githubusercontent.com/1207385/177348332-e1b68c65-72c6-4ce2-8ff7-2563cf306c1b.png)
I've gathered the data on desktop by running `MiniBrowser` under valgrind (massif) with `Malloc=1` env variable set to make `bmalloc` use `malloc()`-based `DebugHeap`. Please note I get the same memory usage spike on the ARM device.

As one can see, when the app loads there is this huge memory usage spike after which the overall memory usage goes back to normal.

The spike comes from:
```
#-----------
snapshot=58
#-----------
time=26809336763
mem_heap_B=181720457
mem_heap_extra_B=5263399
mem_stacks_B=0
heap_tree=peak
n4: 181720457 (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
 n2: 163769195 0x150E5960: bmalloc::DebugHeap::malloc(unsigned long, bmalloc::FailureAction) (DebugHeap.cpp:98)
  n1: 156980070 0x150E3E4F: bmalloc::Cache::tryAllocateSlowCaseNullCache(bmalloc::HeapKind, unsigned long) (Cache.cpp:57)
   n1: 156980070 0x11559B9F: bmalloc::Cache::tryAllocate(bmalloc::HeapKind, unsigned long) (Cache.h:73)
    n2: 156980070 0x11559CFD: bmalloc::api::tryMalloc(unsigned long, bmalloc::HeapKind) (bmalloc.h:43)
     n2: 156884062 0x1502156C: WTF::tryFastMalloc(unsigned long) (FastMalloc.cpp:565)
      n1: 143234464 0x150210DB: WTF::tryFastZeroedMalloc(unsigned long) (FastMalloc.cpp:111)
       n1: 143234464 0x10A22037: WTF::FastMalloc::tryZeroedMalloc(unsigned long) (FastMalloc.h:210)
        n1: 143234464 0x10A2217B: WTF::MallocPtr<unsigned char, WTF::FastMalloc>::tryZeroedMalloc(unsigned long) (MallocPtr.h:126)
         n1: 143234464 0x10A21BD6: Nicosia::Buffer::Buffer(WebCore::IntSize const&, unsigned int) (NicosiaBuffer.cpp:46)
          n2: 143234464 0x10A21AF9: Nicosia::Buffer::create(WebCore::IntSize const&, unsigned int) (NicosiaBuffer.cpp:38)
           n1: 139484704 0x10A116DF: WebCore::CoordinatedGraphicsLayer::flushCompositingStateForThisLayerOnly() (CoordinatedGraphicsLayer.cpp:823)
            n1: 139484704 0x10A1037C: WebCore::CoordinatedGraphicsLayer::flushCompositingState(WebCore::FloatRect const&) (CoordinatedGraphicsLayer.cpp:633)
             n1: 139484704 0x10A103E3: WebCore::CoordinatedGraphicsLayer::flushCompositingState(WebCore::FloatRect const&) (CoordinatedGraphicsLayer.cpp:636)
              n1: 139484704 0x10A103E3: WebCore::CoordinatedGraphicsLayer::flushCompositingState(WebCore::FloatRect const&) (CoordinatedGraphicsLayer.cpp:636)
               n1: 139484704 0x10A103E3: WebCore::CoordinatedGraphicsLayer::flushCompositingState(WebCore::FloatRect const&) (CoordinatedGraphicsLayer.cpp:636)
                n1: 139484704 0x10A103E3: WebCore::CoordinatedGraphicsLayer::flushCompositingState(WebCore::FloatRect const&) (CoordinatedGraphicsLayer.cpp:636)
                 n1: 139484704 0x10A103E3: WebCore::CoordinatedGraphicsLayer::flushCompositingState(WebCore::FloatRect const&) (CoordinatedGraphicsLayer.cpp:636)
                  n1: 139484704 0x12EBD07D: WebCore::RenderLayerCompositor::flushPendingLayerChanges(bool) (RenderLayerCompositor.cpp:542)
                   n1: 139484704 0x1285C025: WebCore::FrameView::flushCompositingStateForThisFrame(WebCore::Frame const&) (FrameView.cpp:979)
                    n1: 139484704 0x1285C922: WebCore::FrameView::flushCompositingStateIncludingSubframes() (FrameView.cpp:1145)
                     n1: 139484704 0x1094B806: WebKit::CompositingCoordinator::flushPendingLayerChanges() (CompositingCoordinator.cpp:131)
                      n2: 139484704 0x1094F8D9: WebKit::LayerTreeHost::layerFlushTimerFired() (LayerTreeHost.cpp:153)
                       n1: 139484704 0x10950806: WebKit::LayerTreeHost::renderNextFrame(bool) (LayerTreeHost.cpp:436)
                        n1: 139484704 0x10950640: WebKit::LayerTreeHost::handleDisplayRefreshMonitorUpdate(bool) (LayerTreeHost.cpp:407)
                         n1: 139484704 0x10954D72: WebKit::LayerTreeHost::CompositorClient::handleDisplayRefreshMonitorUpdate(bool) (LayerTreeHost.h:168)
                          n1: 139484704 0x102EC7FC: WebKit::ThreadedDisplayRefreshMonitor::displayRefreshCallback() (ThreadedDisplayRefreshMonitor.cpp:122)
                           n1: 139484704 0x1030A615: WTF::RunLoop::Timer<WebKit::ThreadedDisplayRefreshMonitor>::fired() (RunLoop.h:168)
                            n1: 139484704 0x150D240A: WTF::RunLoop::TimerBase::TimerBase(WTF::RunLoop&)::{lambda(void*)#1}::operator()(void*) const (RunLoopGLib.cpp:177)
                             n1: 139484704 0x150D2462: WTF::RunLoop::TimerBase::TimerBase(WTF::RunLoop&)::{lambda(void*)#1}::_FUN(void*) (RunLoopGLib.cpp:183)
                              n0: 139484704 0x150D1A89: WTF::{lambda(_GSource*, int (*)(void*), void*)#1}::operator()(_GSource*, int (*)(void*), void*) const (RunLoopGLib.cpp:45)
```

When I've checked (and compared with `2.22`) what are the Nicosia buffers we create:
```
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(256x208)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(256x512)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(256x208)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(256x512)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(256x208)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(256x512)
Buffer::create(1x27)
Buffer::create(1x27)
Buffer::create(1280x720)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(256x208)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(256x512)
Buffer::create(512x38)
Buffer::create(256x38)
Buffer::create(512x38)
Buffer::create(512x29)
Buffer::create(256x29)
Buffer::create(512x29)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(256x208)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(256x512)
Buffer::create(1280x720)
Buffer::create(190x338)
Buffer::create(190x338)
Buffer::create(190x338)
Buffer::create(190x338)
Buffer::create(315x296)
Buffer::create(190x338)
Buffer::create(190x338)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(1409x986)
Buffer::create(190x338)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(278x208)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(278x512)
Buffer::create(60x19)
Buffer::create(190x338)
Buffer::create(337x319)
Buffer::create(337x319)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(278x208)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(278x512)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(278x208)
Buffer::create(512x512)
Buffer::create(512x208)
Buffer::create(278x512)
Buffer::create(1x27)
Buffer::create(60x19)
Buffer::create(337x319)
```
I've discovered that in `2.28` we get calls which we don't in `2.22` i.e. `Buffer::create(1409x986)`. It means that compositing behaves differently for some reason.

Would anyone be able to help me on narrowing down if compositing in that case works fine?

**Comment by Scony** [comment]
Just a note: the sprite used by the portal (https://sky.play.works/service/apps/portal/data/img/textureMap0.png) has the size of exactly `1409x986` but I'm nor sure how its size may impact compositing

**Comment by magomez** [comment]
Arg, I wrote an explanation here about what's happening in this case but I guess I forgot to press the comment button or something because I can't see the comment now :(

Anyway, as you mention @Scony , there's a sprite with all the application covers whose size is 1409x986. That sprite is being set as the background-image of several divs, each one with an offset, in order to paint the application covers. There are also other cases where this is happening as well, as the buffers with size 190x338.

I've checked that indeed the behavior of 2.22 is different than 2.28 when handling this. In 2.22 there's a single buffer that's being shared by all the elements that have the same image-background, so you'll see a single 1409x986 buffer allocation. In 2.28 though, each element that uses the image-background uses its own buffer, and that's why there are all those buffer allocations with the same size (each one belongs to one of the application covers). I understand this change was performed because of thread synchronization issues, but it's indeed increasing the memory used in extreme cases like this where several elements use the same image resource.

So, answering your question, yes, the composition is behaving differently in this case. But it's not an error and it's expected behavior. It's just a different implementation that behaves worse in this scenario, as it doesn't take advantage of several components using the same image as background.

**Comment by Scony** [comment]
@magomez are you able to point which commit(s) changes this?

**Comment by magomez** [comment]
I'm afraid this was not changed by a single commit, but it was a whole reimplementation of the way layers are passed to the compositor stage. We can't just go back to the way things were done in 2.22 without having to revert a lot of changes that affect several classes.

**Comment by Scony** [comment]
@magomez would it be possible to improve that implementation without reverting anything then?

From the memory usage standpoint this is a severe regression... In `2.22` the SYS memory usage peaked at 100MB and GPU memory usage peaked at 26MB while now, in `2.28`, SYS memory peaks at 209MB and GPU memory peaks at 186MB (ofc. high GPU memory usage is the consequence of the changes you described as the buffers are eventually loaded to GPU). Not to mention we're talking about one app only. Technically, other apps which use sprites may have the same issue. In worst case scenario (large sprite, lots of small tiles) we will be constantly OOM.

**Comment by magomez** [comment]
I'll give it a look and see what can be improved.

**Comment by magomez** [comment]
For the record, this is being handled in https://bugs.webkit.org/show_bug.cgi?id=242394

**Comment by Scony** [comment]
Tested backport of the fix (https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/df8e110fba7f876335131fb7905a5f2d3ede6a65) with 2.28 on STB and the results are good enough.

**Comment by Scony** [comment]
To be more precise: `wpe-2.28` with fix behaves much better now, but it looks like it still keeps some extra `Nicosia::Buffer`s in comparison to `wpe-2.22`. In case of play.works portal (https://sky.play.works/service/apps/portal/index.html) the difference is ~20MB.

For closer look, one can analyze the massif (valgrind) output from running play.works portal (https://sky.play.works/service/apps/portal/index.html) on desktop: [massif.zip](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/9358119/massif.zip)

**Comment by magomez** [comment]
I've been giving a look to both Zan's patch and the difference in memory usage that you mention @Scony. With Zan's patch the imageBackings are now shared, which is awesome, and removes the extra 100MB of memory usage in this case. Great. He will soon commit the patch upstream and then I'll backport it 2.28 and this problem will be fixed.

Then, regarding those extra 20MB that you mention, this is a different topic than the original. It seems that in 2.22 we're freeing the Nicosia::Buffers used for tiles faster than we do in 2.28. I'll investigate whether this can be improved as well.

**Comment by magomez** [comment]
I've just pushed e738fffe836aa8c895f368819d7a5ac32ddadfe1 to the wpe-2.28 branch, with the backport of the fix that Zan created for https://bugs.webkit.org/show_bug.cgi?id=242394. This should fix the memory peak by reusing the same buffer for all the ImageBackingStores, and also should reduce those extra 20MB present after the first version of the patch. It may not remove all those extra 20MB because there are some data structures that weren't there on 2.22, but the memory used for buffers, which is the bigger amount, should be freed as long as the buffers are not needed.

@Scony , please, give it a test and close this if the problem is gone. Thanks!

**Comment by Scony** [comment]
Tested on desktop and that 20 extra MBs are gone. I'll close the issue once I confirm the same on the STB. So far it looks good tho.

**Comment by Scony** [comment]
Fixed on STB as well. Thanks!
