### ISSUE TITLE
Webprocess crash with JSValueToStringCopy signature

### ISSUE THREAD

**Issue by ryadav115** [Metrological/WebKitForWayland#908]
The crash is being observed with the signature "JSValueToStringCopy" in mips device: Pxg1v2

Affected Wpe Versions: [2.22.4](https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/ed39c92e596238c3eb434d2388177bc61ca90f38) 

**Frequency**: 0.15% (based on launches => 10 crashes/6351 launches)

**Steps for Reproduction:**
1. Load pace v2 with PX022AN_5.2p3s1_PROD_sey
2. Tune to QAM and playback for 2 minutes
3. Open ESPN+ app
4. Play any live content or can play "Travelers Championship" content
5. Observe for crash after 1 hour
(Please repeat steps multiple times with different contents to observe for crash)

**CallStack:** 
[ 00 ] __mips_syscall6
[ 01 ] _strcpy_s_chk ( strcpy_s.c:108 )
[ 02 ] 0xfffffffa
[ 03 ] JSValueToStringCopy ( JSValueRef.cpp:434 )
[ 04 ] aamp_JSValueToCString ( jsutils.cpp:165 )
[ 05 ] AAMPMediaPlayerJS_load ( jsmediaplayer.cpp:505 )
[ 06 ] call<JSC::JSCallbackFunction> ( APICallbackFunction.h:63 )
[ 07 ] 0x6f9ff034
[ 08 ] profiledCall ( CallData.cpp:62 )
[ 09 ] run ( JSMicrotask.cpp:89 )
[ 10 ] call ( JSExecState.h:92 )
[ 11 ] run ( Function.h:56 )
[ 12 ] performMicrotaskCheckpoint ( Microtasks.cpp:94 )
[ 13 ] didLeaveScriptContext ( JSExecState.cpp:42 )
[ 14 ] handleEvent ( JSExecState.h:145 )
[ 15 ] fireEventListeners ( EventTarget.cpp:292 )
[ 16 ] fireEventListeners ( EventTarget.cpp:234 )
[ 17 ] dispatchEvent ( EventTarget.cpp:193 )
[ 18 ] dispatchProgressEvent ( XMLHttpRequestProgressEventThrottle.cpp:109 )
[ 19 ] callReadyStateChangeListener ( XMLHttpRequest.cpp:316 )
[ 20 ] didFinishLoading ( XMLHttpRequest.cpp:959 )
[ 21 ] didFinishLoading ( DocumentThreadableLoader.cpp:463 )
[ 22 ] checkNotify ( CachedResource.cpp:349 )
[ 23 ] finishLoading ( CachedRawResource.cpp:120 )
[ 24 ] didFinishLoading ( SubresourceLoader.cpp:634 )
[ 25 ] didFinishResourceLoad ( WebResourceLoader.cpp:162 )
[ 26 ] handleMessage<Messages::WebResourceLoader::DidFinishResourceLoad, WebKit::WebResourceLoader, void (WebKit::WebResourceLoader::*)(const WebCore::NetworkLoadMetrics&)> ( HandleMessage.h:41 )
[ 27 ] didReceiveWebResourceLoaderMessage ( WebResourceLoaderMessageReceiver.cpp:65 )
[ 28 ] didReceiveMessage ( NetworkProcessConnection.cpp:71 )
[ 29 ] dispatchMessage ( Connection.cpp:978 )
[ 30 ] dispatchOneIncomingMessage ( Connection.cpp:1047 )
[ 31 ] performWork ( Function.h:56 )
[ 32 ] _FUN ( RunLoopGLib.cpp:68 )
[ 33 ] g_main_context_dispatch ( gmain.c:3216 )
[ 34 ] g_main_context_iterate ( gmain.c:3958 )
[ 35 ] g_main_loop_run ( gmain.c:4152 )
[ 36 ] run ( RunLoopGLib.cpp:96 )
[ 37 ] ChildProcessMain<WebKit::WebProcess, WebKit::WebProcessMain> ( ChildProcessMain.h:63 )
[ 38 ] __libc_start_main ( libc-start.c:308 )
[ 39 ] __start

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
