### ISSUE TITLE
[WPE 2.22] Smoothstreaming content is unwatchable with limited bandwidth

### ISSUE THREAD

**Issue by jakub-gocol-red** [Metrological/WebKitForWayland#917]
When smoothstreaming content is played with bandwidth lower than lowest representation bit rate, video plays in slow motion and audio is not synchronized with video (video might get stuck and audio is playing smoothly or opposite).

Steps to reproduce:
1. Limit bandwidth to 2mbps
2. Put [this](http://amssamples.streaming.mediaservices.windows.net/683f7e47-bd83-4427-b0a3-26a6c4547782/BigBuckBunny.ism/manifest(format=mpd-time-csf)) content in video tag and open it in wpe2.22 browser
3. As soon as it starts playing, limit bandwidth to 0.2mbps
4. Wait for decoder underflow

Expected behavior:
content (both audio and video) pauses for few seconds, after browser downloaded some data it plays for few seconds, then pauses, plays again etc

Actual behavior:
* video plays like bad, choppy slow motion. 
* if there is no video data, but there are audio samples buffered, audio is playing but video is paused
* opposite also can happen

Tested on brcm7218c
Issue is also visible on videoland application

**Comment by rychem** [comment]
@woutermeek in reference to last RDK Browser Working Group and my AP to precise priorities.
We would like to ask to prioritize issue https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/871 (https://jira.rdkcentral.com/jira/browse/WPEBROWSER-7) over this issue (https://jira.rdkcentral.com/jira/browse/WPEBROWSER-9)

**Comment by rychem** [comment]
@woutermeek would you please share whether we have any update on this issue? 
As per our discussion, WPEBROWSER-7 and 9 were to be addressed sequntionally, however the first one was closed ~in mid of Sep

**Comment by rychem** [comment]
@woutermeek is there any update on that ticket?

**Comment by vivienne-w** [comment]
We're currently debugging this

**Comment by rychem** [comment]
Thanks @vivienne-w 
Would you please share whether there is any update on investigation?

**Comment by vivienne-w** [comment]
We can't reliably reproduce the problem, but we've observed some weird behaviour of the WebKit buffering code in MPEG-DASH. The buffering code expects a GstQueue2 element to be in charge of buffering in a centralized way on regular (non-adaptive) live video (where buffering is done in-memory, not on disk). In the case of MPEG-DASH not only there's no GstQueue2, but also one MultiQueue per stream. All those MultiQueues are emitting buffering messages and we suspect that the WebKit buffering code is getting a bit confused.
We're currently analyzing the buffering code and how GstDecodeBin gathers and processes the buffering messages and dimensions the MultiQueues, as well as looking into ways to make that kind of buffering compatible with the WebKit code.

**Comment by vivienne-w** [comment]
@jakub-gocol-red Can you try if the issue persists with https://github.com/vivienne-w/WPEWebKit/tree/issue_917?

**Comment by jakub-gocol-red** [comment]
@vivienne-w to be honest I don't see any difference. Behavior with and without your patch is exactly the same for me.

**Comment by vivienne-w** [comment]
@jakub-gocol-red I just pushed again to that branch, can you send me the logs you get with that commit and `GST_DEBUG="*:WARN,decodebin*:TRACE,multiqueue*:TRACE,webkit*:TRACE"`?

**Comment by jakub-gocol-red** [comment]
Sorry for late response.
I run code from your branch on raspberrypi3. 
First playback started smoothly, then I limited bandwidth to 0.4mb/s. Video froze, audio kept playing. Once every few tens of second displayed video frame changed. I increase bandwidth to 0.8mb/s and video frames started changing quicker (every few seconds). Audio still playing cleanly. Then I disabled bandwidth limit, video tried to catch up with audio, but audio was too far ahead, so I watched slideshow instead of video (~1-2fps). You can see that in logs, there are underruns till the end. 
 
[vivienne-w-rpi3-log.zip](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/10508033/vivienne-w-rpi3-log.zip)

**Comment by eocanha** [comment]
@jakub-gocol-red, sorry for not having had time to focus on this issue for so long. Is it still relevant?

**Comment by modeveci** [comment]
@rychem This ticket seems waiting a long time now. And for 2.22 RPi setup as far as I have seen. The reporter is not from your team now as you stated earlier for another ticket. Shall we close this ticket and if it pops-up for 2.38 to keep in radar again? What do you think?

**Comment by rychem** [comment]
@modeveci my applogizes for missing your question. Yes, lets skip any investments into 2.22. If issue was identified for wpe2.38 we will report seperate ticket.
