### ISSUE TITLE
[2.28] Video poster doesn't disapear with playback start

### ISSUE THREAD

**Issue by asurdej-comcast** [Metrological/WebKitForWayland#919]
Test page: https://asurdej-comcast.github.io/poster.html
1) Press "Load" button (video.load())
2) Press "Async play after 2sec" (video.play() after 2sec timeout)

Once video is started the poster is still there. It doesn't disappear. Behaves differently with different order/timing of load()/play()/autoplay
Video playback works fine in the background but it is covered by poster.
Triggering any repaint (focus change, button press, style change) fixes this issue and the video shows up. Adding "controls" attr to video element also fixes this issue (controls triggers repaint at video start I believe). Looks like everything is fine but there is a missing commit or repaint request from video element.

HTML video display state is correctly set to "Video" (from initial "Poster" state), RenderVideo is updated (updateRenderer()) but no repaint is done and nothing is changed on the screen.

Issue reproduced with x86 Ubuntu 20.04 WPE build from wpe2.28 branch 

EDIT: Video is not composed (RenderLayerBacking is not created) if poster is there. Any call to updateRenderer() does nothing and no repaint is done.

**Comment by magomez** [comment]
@asurdej-comcast , I've just pushed c526579eca9d6c3130c9322da18d77983d0a6039 to the wpe-2.28 branch, that should gix this issue. Could you verify the fix and close this if it works? Thanks!

**Comment by asurdej-comcast** [comment]
@magomez Thanks! Your fix seems to work fine, checked both PC (x86) and wpe device. I will perform final verification tomorrow once I got complete build and will close the issue.

**Comment by magomez** [comment]
@asurdej-comcast were you able to verify this?

**Comment by asurdej-comcast** [comment]
@magomez Yes, it works perfectly fine now. We can close this ticket. Thanks again for your help
