### ISSUE TITLE
WebProcess[JSC] crash with findCommon signature

### ISSUE THREAD

**Issue by cmurug728** [Metrological/WebKitForWayland#932]
It is specific to mips platform , This issue mostly seens in HBO max and paramount app

**Common Scenario among crashes:**
While playing assets in HBO max
Callstack:
`Thread 0 (crashed)
 0  libWPEWebKit-0.1.so.2.2.6!unsigned int WTF::findCommon<WTF::StringView>(WTF::StringView const&, WTF::StringView const&, unsigned int) [StringCommon.h : 520 + 0x8]
 1  libWPEWebKit-0.1.so.2.2.6!WTF::StringView::find(WTF::StringView, unsigned int) const [StringView.cpp : 102 + 0x0]
 2  libWPEWebKit-0.1.so.2.2.6!JSC::stringProtoFuncIndexOf(JSC::ExecState*) [StringPrototype.cpp : 1083 + 0x14]
 3  0x6f6ff1bc
 4  libWPEWebKit-0.1.so.2.2.6!llint_entry + 0xa3b0
 5  libWPEWebKit-0.1.so.2.2.6!vmEntryToJavaScript + 0x174
 6  libWPEWebKit-0.1.so.2.2.6!_fini + 0x365998
 7  libWPEWebKit-0.1.so.2.2.6!mark [APICast.h : 117 + 0x4]
 8  0x7ffd3180
 9  libWPEWebKit-0.1.so.2.2.6!JSC::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) [CallData.cpp : 62 + 0x10]
10  libWPEWebKit-0.1.so.2.2.6!JSC::JSMicrotask::run(JSC::ExecState*) [JSMicrotask.cpp : 89 + 0x0]
11  libWPEWebKit-0.1.so.2.2.6!call [JSExecState.h : 92 + 0x0]
12  libWPEWebKit-0.1.so.2.2.6!WebCore::ActiveDOMCallbackMicrotask::run() [Function.h : 56 + 0x8]
13  libWPEWebKit-0.1.so.2.2.6!WebCore::MicrotaskQueue::performMicrotaskCheckpoint() [Microtasks.cpp : 94 + 0x10]
14  libWPEWebKit-0.1.so.2.2.6!WebCore::JSExecState::didLeaveScriptContext(JSC::ExecState*) [JSExecState.cpp : 42 + 0x18]
15  libWPEWebKit-0.1.so.2.2.6!WebCore::JSCallbackData::invokeCallback(WebCore::JSDOMGlobalObject&, JSC::JSObject*, JSC::JSValue, JSC::MarkedArgumentBuffer&, WebCore::JSCallbackData::CallbackType, JSC::PropertyName, WTF::NakedPtr<JSC::Exception>&) [JSExecState.h : 145 + 0x8]
16  libWPEWebKit-0.1.so.2.2.6!WebCore::JSRequestAnimationFrameCallback::handleEvent(double) [JSCallbackData.h : 89 + 0x24]
17  libWPEWebKit-0.1.so.2.2.6!WebCore::ScriptedAnimationController::serviceScriptedAnimations(double) [ScriptedAnimationController.cpp : 219 + 0xc]
18  libWPEWebKit-0.1.so.2.2.6!WebCore::DocumentAnimationScheduler::displayRefreshFired() [DocumentAnimationScheduler.cpp : 92 + 0x0]
19  libWPEWebKit-0.1.so.2.2.6!WebCore::DisplayRefreshMonitor::displayDidRefresh() [DisplayRefreshMonitor.cpp : 113 + 0x4]
20  libWPEWebKit-0.1.so.2.2.6!WebKit::ThreadedDisplayRefreshMonitor::displayRefreshCallback() [ThreadedDisplayRefreshMonitor.cpp : 102 + 0x0]
21  libWPEWebKit-0.1.so.2.2.6!_FUN [RunLoopGLib.cpp : 170 + 0x4]
22  libglib-2.0.so.0.4800.2!g_main_context_dispatch [gmain.c : 3154 + 0x0]
23  libglib-2.0.so.0.4800.2!g_main_context_iterate [gmain.c : 3844 + 0x4]
24  libglib-2.0.so.0.4800.2!g_main_loop_run [gmain.c : 4038 + 0x8]
25  libWPEWebKit-0.1.so.2.2.6!WTF::RunLoop::run() [RunLoopGLib.cpp : 96 + 0x4]
26  libWPEWebKit-0.1.so.2.2.6!int WebKit::ChildProcessMain<WebKit::WebProcess, WebKit::WebProcessMain>(int, char**) [ChildProcessMain.h : 63 + 0x4]
27  libc-2.24.so!__libc_start_main [libc-start.c : 289 + 0x8]
28  WPEWebProcess!__start + 0x48
`
Webkit version : 
a79319e92cb9d3ee958f2bf9e77724514d034b1c

**Comment by vinaybhat83** [comment]
@cmurug728  If this is specific to MIPS device, we should either close this or deprioritize it.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
