### ISSUE TITLE
[wpe-2.28] progressive player won't auto-recover from pause for buffering

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#940]
In spotify, in podcasts like: https://traffic.megaphone.fm/GLT1088269427.mp3?updated=1658883254 which use progressive player, the seeking results sometimes in pause due to `[Buffering] Pausing stream for buffering.` which - from time to time - won't recover automatically.
The same can be observed in `Progressive Tests` section from YT test suite: https://ytlr-cert.appspot.com/2021/main.html

**Comment by vivienne-w** [comment]
I'm having issues reproducing this on my side, what commit was this happening on for you?

**Comment by Scony** [comment]
This is already fixed in `wpe-2.28`
