### ISSUE TITLE
[wpe-2.28] websocket closure yields wrong close status code - 0

### ISSUE THREAD

**Issue by Scony** [Metrological/WebKitForWayland#944]
In some corner-case triggered by this BBC test case: https://certification.bbctvapps.co.uk/act/test/networking/v1.3.1/websocket-client-initiated-closure/ the websocket closure yields `0` status code.

The `0` status code should not be used as per websocket RFC: https://www.rfc-editor.org/rfc/rfc6455.html#section-7.4.2
```
[7.4.2](https://www.rfc-editor.org/rfc/rfc6455.html#section-7.4.2).  Reserved Status Code Ranges

   0-999

      Status codes in the range 0-999 are not used.
```
The problem with `0` being returned originates in:
https://github.com/WebPlatformForEmbedded/WPEWebKit/blob/a3c865b42cfb8ecc193342d421bd7acfa005de5f/Source/WebKit/NetworkProcess/soup/WebSocketTaskSoup.cpp#L182-L185

which calls `soup_websocket_connection_get_close_code()` function which `Returns: the close code or zero.`, see:
https://github.com/frida/libsoup/blob/f8683845a91d165aaaefa7db5cf3afbf95f06a60/libsoup/soup-websocket-connection.c#L1870-L1891

The above was observed while using `libsoup 2.68.4`.

I've observed the same problem with recent [WebKit](https://github.com/WebKit/WebKit) and with recent Safari.

**Comment by magomez** [comment]
For the record, this is being handled upstream in https://bugs.webkit.org/show_bug.cgi?id=245774

**Comment by magomez** [comment]
I've just backported the patch from the upstream bug and pushed it to the wpe-2.28 branch, in commit 58e3b62900dcfc041419d3e686a0f8f308d95cb2.

@Scony, could you verify the fix and close this if everything is ok?

**Comment by Scony** [comment]
I've tested it and everything is working as expected, thanks @magomez !
