### ISSUE TITLE
WPE image for RPi4 - buildroot errors

### ISSUE THREAD

**Issue by Vexatuspl** [Metrological/WebKitForWayland#947]
When trying to build image with the default config:
`raspberrypi4_wpe_defconfig`

I get the following error:
`Makefile:578: *** wpebackend-fdo is in the dependency of cog that has added it to its _DEPENDENCIES variable without selecting it or depending on it from Confi.in.  Stop.`

After modyfing following lines in ".config":
`# BR2_PACKAGE_COG_PLATFORM_FDO is not set` into
`BR2_PACKAGE_COG_PLATFORM_FDO=y`

`BR2_PACKAGE_COG_PLATFORM_DRM=y` into
`# BR2_PACKAGE_COG_PLATFORM_DRM=y`

`BR2_PACKAGE_WPEBACKEND_RDK=y` into
`# BR2_PACKAGE_WPEBACKEND_RDK=y`

`# BR2_PACKAGE_WPEBACKEND_FDO is not set` into
`BR2_PACKAGE_WPEBACKEND_FDO=y`

I can start the build, after some time I'm gettings this error:
`make: *** No rule to make target 'libwpe' , needed by '/home/osboxes/buildroot/output/build/wpebackend-fdo-1.4.1/.stamp_configured'.  Stop.`

Clearly something's wrong with the pi4 config file.

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
