### ISSUE TITLE
[WPE-2.38] Regression from 2.36 on jQuery FadeIn

### ISSUE THREAD

**Issue by Maigre** [Metrological/WebKitForWayland#962]
Hi,
i am using WPE fullscreen on RPi4 with fullKMS / COG / Weston / Manjaro (Arch) with 1080p/60hz resolution. 

My test app is a page with a thumbnail, when i click on it, it fades on top another full sized black div containing a video player.
The fade-in time is ~1s to let the video load while fading in.  I use the native jquery fadeIn(1000) function. 

with WPE 2.36 // libWPE 1.12 => the fadeIn is smooth 

after full system upgrade today, including WPE 2.38 // libWPE 1.14 => the fadeIn is now very laggy and partialy/enterily skipped

after downgrading only WPE 2.36 // libWPE 1.12 (the rest of the system is kept upgraded) => the fadeIn is smooth again

So it seems WPE related.
Any clue ? 

Thanks !

**Comment by Maigre** [comment]
I tried raplcing jquery.fadeIn with CSS transition and it works ok with WPE 2.38 // libWPE 1.14
so i guess i will stick to CSS animation !

Anyway the previous report might help in some way ? 
Feel free to close the issue if it doesn't.

Best,

**Comment by modeveci** [comment]
Inactive ticket for long time!

Closing the ticket; if you think it is still relevant and/or valid for the latest version/s. Please do not hesitate to re-open!
