### ISSUE TITLE
Canvas rendering problems

### ISSUE THREAD

**Issue by asurdej-comcast** [Metrological/WebKitForWayland#973]
The continuation of https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/969 for platform specific drawing issues

1) Accelerated Canvas 2D context (ImageBufferCairo) doesn't render the latest update but shows previous state. Requires another draw request (e.g. fillRect()) to refresh.
This issue was partially fixed on some platforms with https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/956
but others, like Amlogic requires additional glFinish() after copying canvas buffer into compositor buffer
2) webgl is blinking on some platforms (Amlogic). This can be reproduced with:
https://webglsamples.org/dynamic-cubemap/dynamic-cubemap.html
adding random glFinish() minimize the effect but the blinking seems to be there still. Not sure if this is really connected with cairo but I believe this is the same problem with not finished GL tasks as happens on the same platform as 1) only

Both of my issues are platform specific and happen on Amlogic only

Latest update:
1) Issue seems to be specific to mali driver and happens on Realtek and Amlogic platforms
2) 2D canvas can be fixed by putting glFinish() after copying sufrace texture into compositor texture. glFlush() is not enough here
3) webgl blinking can be fixed by adding glFinish() (glFlush also doesn't work) to
`CoordinatedGraphicsLayer::updatePlatformLayer()` (which eventually calls GC3DLayer::swapBuffersIfNeeded() from NicosiaGC3DLayer)

Only with above 2 glFinishes() both issues are gone. Collecting all together in one place looks like:

> void CoordinatedGraphicsLayer::updatePlatformLayer()
{
    if (!m_shouldUpdatePlatformLayer)
        return;
    m_shouldUpdatePlatformLayer = false;
#if USE(COORDINATED_GRAPHICS) && USE(NICOSIA)
    if (m_nicosia.contentLayer) {
        glFinish();
        downcast<Nicosia::ContentLayerTextureMapperImpl>(m_nicosia.contentLayer->impl()).swapBuffersIfNeeded();
        glFinish();
    }
#endif

First glFinish() fixes webgl, the second one 2D context. Using glFlush() doesn't really make any difference

Any ideas what can be the reason here?

**Comment by magomez** [comment]
This sounds like a problem in the GLES implementation or the video driver.
As I commented in the other issue, when rendering with OpenGL/GLES something that's going to be read from a different thread, a call to glFlush() should be done after we're done rendering, so the commands to render the contents are sent to the OpenGL pipeline, and trying to read afterwards will produce the appropriate result.

glFisnish() could be used as well, but this blocks until all the rendering commands have been processed, which is an overkill and has a performance penalty.

It seems that those platforms have some problem syncing the different operations among threads, and that's why the rendering doesn't seem to be complete when we're trying to access the rendered content, hence the blink. I would just add those glFinish that work for you in these platforms, as can't do much more than that.

**Comment by asurdej-comcast** [comment]
Hi @magomez, thanks for your comment, I tried to fix those issue without glFinish() and I upladed PR https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/976

It uses GLFenceSync for webgl that seems to have a better peformance than glFinish() still fixing webgl blinking
e.g for https://webglsamples.org/dynamic-cubemap/dynamic-cubemap.html
by default it runs ~45-50fps, with glFinish() it's 40fps, with current patch it's ~45fps

I tried doing the same for ImageBufferCairo but in this case we use single compositor buffer so syncing will require some communication between renderer process and main process (to get the latest sync object available). This doesn't look to be safe as ImageBufferData can be destroyed anytime without any info in renderer thread (fix me if i'm wrong) and I'm pretty afraid that this could be the reason for different crashes/hangs. So I left glFinish() in this case.
I could do the same as webgl but this will require pushing new buffer for each swapBufferIfNeeded() that could potentially break some of your fixes from https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/969
(unless there is some other way)...

It would be nice if you could take a look at the patch

**Comment by magomez** [comment]
@asurdej-comcast any news about this? can it be closed?

**Comment by asurdej-comcast** [comment]
Hi @magomez The issues are still there on Amlogic and Realtek devices. I'm trying to work with platform vendors to get some insight from their side (but this is going pretty slow) so currently no support from webkit is needed. Thanks

I think we can close this issue as we probably can't do much here, apart from glFinish() maybe if neccessary, but I want to clarify this with platform side first.
