### ISSUE TITLE
[WPE2.22] [MSE] Handling trackId changing across Initialization Segments

### ISSUE THREAD

**Issue by jacek-skiba-red** [Metrological/WebKitForWayland#983]
Hello,

One of our applications in MSE streaming is using different `trackid` for different resolutions,e eg:
* 64k audio: init segment (track_id == 2), payload segment (track_id == 2)
* 128k audio: init segment (track_id == 3), payload segment (track_id == 3)

This is causing issues on QTDemux level (on gst version 1.18): after representation change qtdemux cannot find new `trackid` in track fragment header box `tfhd`:
```
qtdemux_parse_moof:<qtdemux3> Fragment #6
qtdemux_parse_tfhd:<qtdemux3> unknown stream in tfhd 
qtdemux_parse_moof:<qtdemux3> decode time 1800960 (99:99:99.999999999)
```

Issue seems solved in Webkit upstream: https://github.com/WebKit/WebKit/commit/1cd7262c7aee2fb0451f20177294f77f1bc7785b
However it seems that for WPE port issue still is not fixed because `media-source-trackid-change.html` included in above commit is not working on WPE master branch (https://bugs.webkit.org/show_bug.cgi?id=218317)

Analyzing WPE gstreamer code from 2.22 / 2.28 / master branch it looks like `SourceBuffer::sourceBufferPrivateDidReceiveInitializationSegment` call is triggered only during AppendPipeline setup. Consecutive `appendBuffer` calls with init segment from JS are not recognized by appendPipeline and not pushed to SourceBuffer logic. 

The same behavior is seen on Raspberry Pi 3B+ with gstreamer 1.16.

Looks like root cause is entirly on QTDemux level. QTDemux recognize new caps when init segment with different `track_id` is pushed. The question is how force creation of new pads based on new caps on QTDemux level, to trigger init segment logic on AppendPipeline: `g_signal_connect(m_demux.get(), "pad-added", G_CALLBACK(appendPipelineDemuxerPadAdded), this);`

**Comment by modeveci** [comment]
Test URL: https://developers.canal-plus.com/rx-player/upc/?appTileLocation=[object%20Object]

**Comment by jacek-skiba-red** [comment]
Fix for WPE2.22 which uses Gstreamer 1.10 was done on QTDemux level (via custom LGI property "support-track-id-change"). 
Fix is LGI specific: https://github.com/LibertyGlobal/WPEWebKit/pull/218

Now we are investigating if on yocto 3.1 (which uses gstreamer 1.18) qtdemux handles by default runtime track-id change (we have on yocto 3.1 builds temporary problem to run above testcase due to CORS issue).

**Comment by jacek-skiba-red** [comment]
QTDemux in version 1.18 is supporting by default `track_id` changes. For each `track_id` update, QTDemux is creating new pad. Closing issue, as runtime `track_id` change is supported for WPE2.22 + Gst1.18.
