### ISSUE TITLE
[wpe28] HTMLMediaElement forces player to play even if paused for buffering

### ISSUE THREAD

**Issue by asurdej-comcast** [Metrological/WebKitForWayland#995]
There is a pretty weird behavior when player is entering BUFFERING state (PAUSE). Once updateStates() notices low buffering level it forces player to pause and lowers readyState accordingly to HaveCurrentData. Ready state update is triggered in HTMLMediaElement that that calls updatePlayState() on HTML side and accroding to potentiallyPlaying() player should be playing, but is paused. This forces player->play() method switching back to PLAYING state again. Here player again notices that it should be paused for buffering and now it truly enters PAUSED state as no reasyState or networkState update occures.

There is a race between potentiallyPlaying() and the first pipeline state change to PAUSED makeing this issue not visible sometimes (as pipeline is not yet paused when calling potentiallyPlaying())

We can fix it in MediaPlayer::paused() to return false when there is paused for buffering or inside HTMLMediaElement side to propertly recognize this case.

Logs when issue is reproduced (x86 with random mp4 progressive playback in video tag):

> 0:00:09.553532682 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2208:updateBufferingStatus:<media-player-0> [Buffering] mode: GST_BUFFERING_DOWNLOAD, status: 7.000000%
0:00:09.553586307 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2201:updateMaxTimeLoaded:<media-player-0> [Buffering] Updated maxTimeLoaded: {1053969583/1000000000 = 1.053970}
0:00:09.553606657 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2469:updateStates:<media-player-0> State: PLAYING, pending: VOID_PENDING
0:00:09.553794610 47346 0x56223dba4350 INFO       webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2546:updateStates:<media-player-0> [Buffering] Pausing stream for buffering.
0:00:09.553809296 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:997:changePipelineState:<media-player-0> Changing state change to PAUSED from PLAYING with VOID_PENDING pending
0:00:09.554283477 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2552:updateStates:<media-player-0> Old state: PAUSED, new state: PLAYING (requested: VOID_PENDING)
0:00:09.554310431 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2608:updateStates:<media-player-0> Network State Changed from Loaded to Loading
[WPEWebKit:Media:-] HTMLMediaElement::setNetworkState(9B5FF80BFC332A2A) new state = Loading, current state = NETWORK_IDLE
0:00:09.554368668 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2612:updateStates:<media-player-0> Ready State Changed from HaveEnoughData to HaveCurrentData
[WPEWebKit:Media:-] HTMLMediaElement::setReadyState(9B5FF80BFC332A2A) new state = HaveCurrentData, current state = HAVE_ENOUGH_DATA
[WPEWebKit:Media:-] HTMLMediaElement::updatePlayState(9B5FF80BFC332A2A) shouldBePlaying = true, playerPaused = true
[WPEWebKit:Media:-] MediaElementSession::clientWillBeginPlayback(9B5FF80BFC332A2A) state = Playing
[WPEWebKit:Media:-] PlatformMediaSessionManager::setCurrentSession(0) (9B5FF80BFC332A2A)
[WPEWebKit:Media:-] PlatformMediaSessionManager::sessionWillBeginPlayback(0) (9B5FF80BFC332A2A) returning true
0:00:09.554477865 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:663:setRate:<media-player-0> Setting playback rate to 1.000000
0:00:09.554500487 47346 0x56223dba4350 INFO       webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:1320:isMuted:<media-player-0> Player is muted: false
0:00:09.554515355 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:1822:setVolume:<media-player-0> Setting volume: 1.000000
0:00:09.554548495 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:1850:volumeChangedCallback:<media-player-0> Volume changed to: 1.000000
[WPEWebKit:Media:-] HTMLMediaElement::mediaPlayerVolumeChanged(9B5FF80BFC332A2A) 
0:00:09.554581959 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:997:changePipelineState:<media-player-0> Changing state change to PLAYING from PAUSED with VOID_PENDING pending
0:00:09.555309645 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2830:updateDownloadBufferingFlag:<media-player-0> Download already started, not starting again
0:00:09.555327292 47346 0x56223dba4350 INFO       webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:468:play:<media-player-0> Play
0:00:09.555692219 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2469:updateStates:<media-player-0> State: PLAYING, pending: VOID_PENDING
0:00:09.555858481 47346 0x56223dba4350 INFO       webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2546:updateStates:<media-player-0> [Buffering] Pausing stream for buffering.
0:00:09.555884237 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:997:changePipelineState:<media-player-0> Changing state change to PAUSED from PLAYING with VOID_PENDING pending
0:00:09.556280502 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2552:updateStates:<media-player-0> Old state: PAUSED, new state: PLAYING (requested: VOID_PENDING)
0:00:09.556626285 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2469:updateStates:<media-player-0> State: PAUSED, pending: VOID_PENDING
0:00:09.556801132 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2552:updateStates:<media-player-0> Old state: PLAYING, new state: PAUSED (requested: VOID_PENDING)
0:00:09.557126229 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2469:updateStates:<media-player-0> State: PAUSED, pending: VOID_PENDING
0:00:09.557269493 47346 0x56223dba4350 DEBUG      webkitmediaplayer MediaPlayerPrivateGStreamer.cpp:2552:updateStates:<media-player-0> Old state: PLAYING, new state: PAUSED (requested: VOID_PENDING)

**Comment by calvaris** [comment]
Do you have a use case, stream, to test this?

**Comment by asurdej-comcast** [comment]
My scenario is:
1) Run (simple video tag with mp4 video -> Tubi preview but could be any mp4)
`WEBKIT_DEBUG=Media=debug GST_DEBUG=*mediaplayer*:5,:2 ./run-wpe-x11.txt  "https://asurdej-comcast.github.io/webaudio/video.html?url=https://video-previews-cdn.production-public.tubi.io/videopreview/1d50a387-38f2-4f72-8f64-4788fe6f24cf/1d50a387-38f2-4f72-8f64-4788fe6f24cf-start416-end489_v2.mp4"`
2) Break your internet connection so buffering message is triggered (just unplug eth cable or so)
3) Wait for buffering message

Rate is like 1/2 for me.

Not sure if such behavior is expected or not but looks like HTML element is not aware of potential buffering. Media player lands in PAUSED state finally which is good but via PAUSE->PLAY->PAUSE cycle

Currently we disabled pause of buffering completely (as it was in 2.22 some time ago) so this has no priority for me.

**Comment by calvaris** [comment]
@asurdej-comcast which WebKit version is this?

**Comment by asurdej-comcast** [comment]
Just reproduced with the latest wpe-2.28 branch

**Comment by calvaris** [comment]
@asurdej-comcast are you using disk buffering?

**Comment by asurdej-comcast** [comment]
I don't think so. Default x86 configuration is used

**Comment by calvaris** [comment]
Is this causing any problems other than being "weird"? I am digging a bit more but I don't know how deep I must dig so if it's just weird but it is not causing any problems, I could close this.

**Comment by asurdej-comcast** [comment]
@calvaris Thanks, this flow doesn't cause any problem currently. Player eventually hits PAUSED state as expected (only logs may be confusing). Ok lets just close it
